#!/usr/bin/env node
// Task 138 §2 — enumerate every inference rule and measure the real-player
// scenario, writing docs/INFERENCE-RULES.md.
//
//   npm run audit:inference
//
// The computation lives in `src/lib/inferenceAudit.ts` (so the tests and the app
// share it) and is loaded through Vite's in-process SSR transform (no server).
import { createServer } from 'vite'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const docFile = path.join(root, 'docs/INFERENCE-RULES.md')

const SOURCE_LABEL = {
  catalog: 'Catalog `implies`',
  chain: 'Authored chains (`inferChains.ts`)',
  gate: 'Gates (`gates.ts`)',
  storyline: 'Storylines (`storylines.ts` grants)',
  setup: 'Setup wizard (`applyAnswers`)',
  capture: 'Capture rules (PS5 reads)',
}

function badge(certainty) {
  return certainty === 'certain' ? 'certain' : '**likely**'
}

function renderRuleTable(source, rules) {
  const lines = [
    '| id | trigger | conclusions | class | conf | why | added |',
    '| --- | --- | --- | --- | --- | --- | --- |',
  ]
  for (const r of rules) {
    lines.push(
      `| \`${r.id}\` | \`${r.trigger}\` | ${r.conclusions.map((c) => `\`${c}\``).join(', ') || '—'} | ${badge(r.certainty)} | ${r.confidence} | ${r.why.replace(/\|/g, '\\|')} | ${r.addedBy ?? '—'} |`,
    )
  }
  return lines.join('\n')
}

function renderMissing(rows) {
  const lines = ['| conclusion | class | status | detail |', '| --- | --- | --- | --- |']
  for (const r of rows) {
    lines.push(`| ${r.conclusion} | ${badge(r.certainty)} | ${r.status} | ${r.detail.replace(/\|/g, '\\|')} |`)
  }
  return lines.join('\n')
}

function renderScenario(report) {
  const before = new Set(report.beforeInferred)
  const after = new Set(report.afterInferred)
  const newly = report.afterInferred.filter((id) => !before.has(id))
  const lines = [
    `Scenario: \`urmummytoilet\` — ${report.directCount} certain reads, nothing uncertain applied.`,
    '',
    `- Inferred before Task 138: **${report.beforeInferred.length}**`,
    `- Inferred after Task 138: **${report.afterInferred.length}**`,
    `- Newly inferred by Task 138: **${newly.length}** (${newly.map((id) => `\`${id}\``).join(', ')})`,
    '',
    '### After: every inferred fact with its reason',
    '',
    '| fact | from | class | reason |',
    '| --- | --- | --- | --- |',
  ]
  for (const f of report.afterFacts) {
    lines.push(`| \`${f.fact}\` | ${f.from ? `\`${f.from}\`` : '—'} | ${badge(f.certainty)} | ${f.why.replace(/\|/g, '\\|')} |`)
  }
  return lines.join('\n')
}

async function main() {
  const server = await createServer({ root, server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' })
  try {
    const mod = await server.ssrLoadModule('/src/lib/inferenceAudit.ts')
    const rules = mod.ruleInventory()
    const totals = mod.auditTotals()
    const report = mod.scenarioReport()
    const missing = mod.missingConclusions()
    const beforeRules = rules.filter((r) => r.addedBy !== 138)
    const overreaches = rules.filter((r) => r.source === 'catalog' && r.certainty === 'likely')

    const today = new Date().toISOString().slice(0, 10)
    const bySource = new Map()
    for (const r of rules) {
      const list = bySource.get(r.source) ?? []
      list.push(r)
      bySource.set(r.source, list)
    }

    const sections = []
    for (const [source, list] of bySource) {
      sections.push(`### ${SOURCE_LABEL[source] ?? source} (${list.length})\n\n${renderRuleTable(source, list)}`)
    }

    const doc = `# Inference rules (Task 138 §2)

Generated by \`npm run audit:inference\` from \`src/lib/inferenceAudit.ts\`. This is
the map of every inference the app runs — the authored chain table, the catalog
\`implies\` graph, the gates, the storyline grants, the Setup-wizard seeds and the
PS5 capture rules — plus what the real-player scenario fixture actually proves.

## Totals

| metric | before Task 138 | after Task 138 |
| --- | --- | --- |
| rules enumerated | ${beforeRules.length} | ${totals.rules} |
| certain rules | ${beforeRules.filter((r) => r.certainty === 'certain').length} | ${totals.certain} |
| likely rules | ${beforeRules.filter((r) => r.certainty === 'likely').length} | ${totals.likely} |
| scenario inferred facts | ${report.beforeInferred.length} | ${report.afterInferred.length} |

Task 138 added **${totals.addedBy138}** chain rules.

## Scenario before/after

${renderScenario(report)}

## Missing conclusions — certain vs likely

The conclusions a knowledgeable player would draw that the app did not. \`already\`
means a rule already covered it; \`implemented\` means Task 138 added the rule;
\`likely\` is surfaced for confirmation, never applied; \`not-modelled\` needs an
action only the player can log.

${renderMissing(missing)}

## Existing catalog edges the audit reads as *likely*

These are live today. The audit flags them rather than trusting them; they are
candidates to demote into the confirmation layer.

${overreaches.length ? renderRuleTable('catalog', overreaches) : '_None._'}

## Every rule

${sections.join('\n\n')}

_Regenerated ${today}._
`
    fs.writeFileSync(docFile, doc)
    console.log(`inference doc written: docs/INFERENCE-RULES.md (${totals.rules} rules, ${report.afterInferred.length} scenario facts)`)
  } finally {
    await server.close()
  }
}

main().catch((error) => {
  console.error('inference-audit failed:', error)
  process.exitCode = 1
})
