#!/usr/bin/env node
// Task 144 §4 — the entity-page sweep.
//
//   npm run audit:pages
//
// Every entity in the build-time index (all kinds) is run through the same page
// data the panel renders, and the page-rule faults the live play-test found are
// counted before/after Task 144. Writes `docs/PAGE-AUDIT.md`.
//
// The computation lives in `src/lib/pageAudit.ts` and is loaded through Vite's
// in-process SSR transform (no server).
import { createServer } from 'vite'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const indexFile = path.join(root, 'public/sourced/entity-index.json')
const docFile = path.join(root, 'docs/PAGE-AUDIT.md')

const COLUMNS = [
  ['empty', 'empty'],
  ['rawId', 'raw ids'],
  ['badCasing', 'bad casing'],
  ['genericStatus', 'generic status'],
  ['wrongActions', 'wrong actions'],
  ['wikiNav', 'wiki nav'],
]

function renderTable(report) {
  const lines = [
    '| kind | entities | flagged | ' + COLUMNS.map(([, label]) => label).join(' | ') + ' |',
    '| --- | --- | --- | ' + COLUMNS.map(() => '---').join(' | ') + ' |',
  ]
  for (const k of report.byKind) {
    const cells = COLUMNS.map(([key]) => k[key])
    lines.push(`| ${k.kind} | ${k.total} | ${k.flagged} | ${cells.join(' | ')} |`)
  }
  lines.push(
    `| **total** | **${report.total}** | **${report.flagged}** | ${COLUMNS.map(([key]) =>
      report.byKind.reduce((n, k) => n + k[key], 0),
    ).join(' | ')} |`,
  )
  return lines.join('\n')
}

function renderEmpties(report) {
  if (!report.empties.length) return '_None._'
  const byKind = new Map()
  for (const row of report.empties) {
    const list = byKind.get(row.kind) ?? []
    list.push(row)
    byKind.set(row.kind, list)
  }
  const lines = []
  for (const [kind, rows] of [...byKind.entries()].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`### ${kind} (${rows.length})`)
    lines.push('')
    lines.push(rows.map((r) => `- ${r.name}`).join('\n'))
    lines.push('')
  }
  return lines.join('\n')
}

function renderFlagged(report) {
  const rows = report.flaggedRows
  if (!rows.length) return '_None._'
  const lines = ['| id | kind | issues |', '| --- | --- | --- |']
  for (const row of rows.slice(0, 120)) {
    lines.push(`| \`${row.id}\` | ${row.kind} | ${row.issues.join(', ')} |`)
  }
  if (rows.length > 120) lines.push(`\n_+${rows.length - 120} more._`)
  return lines.join('\n')
}

async function main() {
  const server = await createServer({ root, server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' })
  try {
    const indexMod = await server.ssrLoadModule('/src/lib/entityIndex.ts')
    const auditMod = await server.ssrLoadModule('/src/lib/pageAudit.ts')

    const doc = fs.existsSync(indexFile) ? JSON.parse(fs.readFileSync(indexFile, 'utf8')) : { records: {} }
    indexMod.setEntityIndex(new Map(Object.entries(doc.records ?? {})))

    const before = auditMod.auditPages({ fixed: false })
    const after = auditMod.auditPages({ fixed: true })

    const today = new Date().toISOString().slice(0, 10)
    const markdown = `# Entity page audit (Task 144 §4)

Generated by \`npm run audit:pages\` from \`src/lib/pageAudit.ts\`. It walks every
record in \`public/sourced/entity-index.json\` and applies the page rules the live
play-test exercised: a page must not be empty, must not print a raw fact id or a
map asset code, must use the canonical game spelling, must carry a kind-specific
status, must only offer actions that fit the kind, and must never resolve to a
wiki disambiguation/list/index page.

**Before** reproduces the pre-Task-144 behaviour (raw dump names, the generic
action footer, no navigation filter); **after** is the fixed build.

## Before

${renderTable(before)}

## After

${renderTable(after)}

Task 144 removed **${before.flagged - after.flagged}** flagged pages
(${COLUMNS.map(([, label]) => label).join(', ')}).

## Remaining empty pages — genuine data gaps, by name

These entries have no description, location, stats, drops, sections or image in
any source. They are real gaps in the shipped data, not builder faults, and are
listed so they are visible rather than silently blank.

${renderEmpties(after)}

## Every flagged page (after)

${renderFlagged(after)}

_Regenerated ${today}._
`
    fs.writeFileSync(docFile, markdown)
    console.log(`page audit written: docs/PAGE-AUDIT.md (${after.total} entities, ${after.flagged} flagged; before ${before.flagged})`)
  } finally {
    await server.close()
  }
}

main().catch((error) => {
  console.error('page-audit failed:', error)
  process.exitCode = 1
})
