#!/usr/bin/env node
// Task 144 §4 — run the scenario characters through Overview, Area and Now.
//
//   npm run audit:progress
//
// Asserts: ratios ≤ 1 and drawn from a full set, no raw ids in player text, no
// inference contradictions, lockouts only where relevant, upgrades positive.
// Writes `docs/PROGRESS-AUDIT.md`; exits non-zero on any violation so it can
// guard CI. The computation lives in `src/lib/progressAudit.ts`.
import { createServer } from 'vite'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const indexFile = path.join(root, 'public/sourced/entity-index.json')
const docFile = path.join(root, 'docs/PROGRESS-AUDIT.md')

async function main() {
  const server = await createServer({ root, server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' })
  try {
    const indexMod = await server.ssrLoadModule('/src/lib/entityIndex.ts')
    const auditMod = await server.ssrLoadModule('/src/lib/progressAudit.ts')

    const doc = fs.existsSync(indexFile) ? JSON.parse(fs.readFileSync(indexFile, 'utf8')) : { records: {} }
    indexMod.setEntityIndex(new Map(Object.entries(doc.records ?? {})))

    const report = auditMod.runProgressAudit()
    const today = new Date().toISOString().slice(0, 10)

    const lines = [
      '# Progress audit (Task 144 §4)',
      '',
      'Generated by `npm run audit:progress` from `src/lib/progressAudit.ts`. Runs the',
      'scenario characters through the Overview meters, the Area hub and the Now',
      'advisor, and checks the properties the live play-test broke.',
      '',
      `Scenarios audited: **${report.scenarios.length}** · violations: **${report.violations.length}**`,
      '',
    ]
    for (const s of report.scenarios) {
      lines.push(`## ${s.scenario}`)
      lines.push('')
      lines.push('| meter | have | total | ratio |')
      lines.push('| --- | --- | --- | --- |')
      for (const m of s.ratios) lines.push(`| ${m.id} | ${m.have} | ${m.total} | ${m.ratio.toFixed(3)} |`)
      lines.push('')
      lines.push(`Lockouts at Stormveil: ${s.lockouts.length ? s.lockouts.join(', ') : '_none_'}`)
      lines.push('')
      lines.push(`Positive upgrades surfaced by Now: ${s.upgradeCount}`)
      lines.push('')
    }
    if (report.violations.length) {
      lines.push('## Violations')
      lines.push('')
      lines.push(report.violations.map((v) => `- ${v}`).join('\n'))
    } else {
      lines.push('_All checks passed._')
    }
    lines.push('')
    lines.push(`_Regenerated ${today}._`)

    fs.writeFileSync(docFile, lines.join('\n'))
    console.log(
      report.violations.length
        ? `progress audit FAILED: ${report.violations.length} violations`
        : `progress audit passed (${report.scenarios.length} scenarios)`,
    )
    if (report.violations.length) process.exitCode = 1
  } finally {
    await server.close()
  }
}

main().catch((error) => {
  console.error('progress-audit failed:', error)
  process.exitCode = 1
})
