import type { LoadoutSlot, Stats } from '../types'

export type OpBuild = {
  id: string
  name: string
  tag: string
  why: string
  level: number
  stats: Stats
  kit: LoadoutSlot[]
  need: string[]
}

export const opBuilds: OpBuild[] = [
  {
    id: 'build:rivers',
    name: 'Rivers of Blood',
    tag: 'bleed / arcane',
    why: 'Still deletes most of the Lands Between. Weak to high bleed resist (Malenia is the joke).',
    level: 150,
    stats: { vigor: 50, mind: 20, endurance: 25, strength: 12, dexterity: 40, intelligence: 9, faith: 8, arcane: 45 },
    kit: [
      { id: 'rob', name: 'Rivers of Blood', kind: 'armament', upgrade: 10 },
      { id: 'uchi', name: 'Uchigatana', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Winged Sword Insignia', kind: 'talisman' },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
    ],
    need: ['loot:rivers', 'loot:lord-blood-exul', 'boss:radahn'],
  },
  {
    id: 'build:azur',
    name: 'Comet Azur glass',
    tag: 'intelligence',
    why: 'One-shot setups for dragons and late bosses if you can stand still. Terra Magicus + Graven-Mass + Magic Scorpion.',
    level: 150,
    stats: { vigor: 40, mind: 38, endurance: 20, strength: 8, dexterity: 16, intelligence: 80, faith: 6, arcane: 9 },
    kit: [
      { id: 'azur', name: 'Comet Azur', kind: 'ash' },
      { id: 'lusat', name: "Lusat's Glintstone Staff", kind: 'catalyst', upgrade: 10 },
      { id: 'icon', name: 'Radagon Icon', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
    ],
    need: ['loot:comet-azur', 'loot:radagon-icon', 'loot:godfrey-icon'],
  },
  {
    id: 'build:blasphemous',
    name: 'Blasphemous Blade',
    tag: 'faith / quality',
    why: 'Taker’s Flames heals on every wave. Facetanks most of base game. Falls off vs holy resist in SotE.',
    level: 150,
    stats: { vigor: 55, mind: 25, endurance: 30, strength: 22, dexterity: 15, intelligence: 9, faith: 50, arcane: 8 },
    kit: [
      { id: 'bb', name: 'Blasphemous Blade', kind: 'armament', upgrade: 10 },
      { id: 'fgms', name: 'Flame, Grant Me Strength', kind: 'ash' },
      { id: 'vow', name: 'Golden Vow', kind: 'ash' },
      { id: 'fire-scorp', name: 'Fire Scorpion Charm', kind: 'talisman' },
    ],
    need: ['loot:blasphemous', 'loot:flame-grant', 'loot:golden-vow', 'boss:rykard'],
  },
  {
    id: 'build:heavy-bonk',
    name: 'Heavy Knight bonk',
    tag: 'strength / tarnished pack',
    why: 'The pack’s Heavy Knight already has the poise. Giant-Crusher or Anvil Hammer, lion’s claw / cragblade.',
    level: 150,
    stats: { vigor: 55, mind: 12, endurance: 40, strength: 80, dexterity: 10, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'crusher', name: 'Giant-Crusher', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'anvil', name: 'Anvil Hammer', kind: 'armament', upgrade: 10 },
      { id: 'crag', name: 'Cragblade', kind: 'ash' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
    ],
    need: ['loot:anvil-hammer', 'loot:cragblade', 'loot:shard-alexander'],
  },
  {
    id: 'build:night-comet',
    name: 'Night Comet Sellia',
    tag: 'intelligence',
    why: 'Enemies barely dodge it. Staff of Loss in offhand. Best “I hate lock-on” sorcery.',
    level: 125,
    stats: { vigor: 40, mind: 30, endurance: 20, strength: 8, dexterity: 16, intelligence: 68, faith: 6, arcane: 9 },
    kit: [
      { id: 'nc', name: 'Night Comet', kind: 'ash' },
      { id: 'loss', name: 'Staff of Loss', kind: 'catalyst', upgrade: 25 },
      { id: 'carian', name: 'Carian Regal Scepter', kind: 'catalyst', upgrade: 10 },
    ],
    need: ['loot:night-comet', 'boss:rennala'],
  },
  {
    id: 'build:leontiel',
    name: 'Leontiel matador',
    tag: 'tarnished pack',
    why: 'Pack invader weapon. Reach + stance. Pairs with Heavy Knight or a dex hybrid after Radahn.',
    level: 150,
    stats: { vigor: 50, mind: 18, endurance: 28, strength: 22, dexterity: 50, intelligence: 9, faith: 8, arcane: 14 },
    kit: [
      { id: 'leo', name: "Leontiel's Greatsword", kind: 'armament', upgrade: 10 },
      { id: 'idus', name: 'Idus Sword', kind: 'armament', upgrade: 25 },
    ],
    need: ['loot:leontiel-gs', 'boss:leontiel', 'boss:radahn'],
  },
  // --- Expanded set (Task 40). Stats are recommended target spreads, not extracted
  // numbers. Weapon/skill facts cross-checked against the Fextralife wiki (patch 1.17,
  // Aug 2026); see docs/research/op-builds-pvp-tricks-sources.md for the source list.
  {
    id: 'build:greatsword-lions-claw',
    name: 'Greatsword Lion’s Claw',
    tag: 'strength / colossal',
    why: 'Lion’s Claw is unparryable, has hyper armour, and does real stance damage — on a colossal sword it breaks most bosses in two casts. Pure Strength, no casting stat tax.',
    level: 150,
    stats: { vigor: 60, mind: 12, endurance: 40, strength: 80, dexterity: 14, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'greatsword', name: 'Greatsword', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'lions-claw', name: 'Lion’s Claw', kind: 'ash' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'axe-tal', name: 'Axe Talisman', kind: 'talisman' },
      { id: 'claw-tal', name: 'Claw Talisman', kind: 'talisman' },
    ],
    need: ['loot:lions-claw', 'loot:shard-alexander', 'loot:greatsword'],
  },
  {
    id: 'build:dark-moon',
    name: 'Dark Moon Greatsword',
    tag: 'intelligence / frost',
    why: 'The Moonlight Greatsword beam on the charged heavy is ranged frost damage; Godfrey Icon, Magic Scorpion and Shard of Alexander all stack it. Frostbite then a heavy trade.',
    level: 150,
    stats: { vigor: 55, mind: 30, endurance: 25, strength: 16, dexterity: 12, intelligence: 70, faith: 7, arcane: 9 },
    kit: [
      { id: 'dmgs', name: 'Dark Moon Greatsword', kind: 'armament', upgrade: 10 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
    ],
    need: ['loot:dark-moon', 'loot:magic-scorpion', 'loot:godfrey-icon'],
  },
  {
    id: 'build:moonveil',
    name: 'Moonveil Shinobi',
    tag: 'intelligence / dex',
    why: 'Transient Moonlight is a fast ranged slash that staggers at range. Powerstance with a Cold Uchigatana to stack Hemorrhage and Frostbite off the same L1 chain.',
    level: 125,
    stats: { vigor: 50, mind: 24, endurance: 22, strength: 12, dexterity: 40, intelligence: 50, faith: 7, arcane: 9 },
    kit: [
      { id: 'moonveil', name: 'Moonveil', kind: 'armament', upgrade: 10 },
      { id: 'uchi', name: 'Uchigatana', kind: 'armament', affinity: 'Cold', upgrade: 25 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'carian-crest', name: 'Carian Filigreed Crest', kind: 'talisman' },
    ],
    need: ['loot:moonveil', 'loot:magic-scorpion', 'boss:magma-wyrm'],
  },
  {
    id: 'build:blackflame',
    name: 'Black Flame Godslayer',
    tag: 'faith / incant',
    why: 'Black Flame burns a percentage of max HP on hit, so it keeps pace with boss health pools where flat-AR incantations fall off. The real faith caster build that is not Blasphemous Blade.',
    level: 150,
    stats: { vigor: 55, mind: 35, endurance: 25, strength: 16, dexterity: 18, intelligence: 7, faith: 65, arcane: 9 },
    kit: [
      { id: 'godslayer-seal', name: 'Godslayer’s Seal', kind: 'catalyst', upgrade: 25 },
      { id: 'black-flame', name: 'Black Flame', kind: 'ash' },
      { id: 'scouring', name: 'Scouring Black Flame', kind: 'ash' },
      { id: 'flock', name: 'Flock’s Canvas Talisman', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
    ],
    need: ['loot:black-flame', 'loot:godslayer-seal', 'boss:godskin'],
  },
  {
    id: 'build:dragon-communion',
    name: 'Dragon Communion',
    tag: 'arcane / faith',
    why: 'Dragon Communion Seal scales off Arcane, so one stat feeds every breath. Dragonmaw deletes anything that lets you stand still; Rotten Breath rots the rest. SotE-friendly.',
    level: 150,
    stats: { vigor: 55, mind: 30, endurance: 25, strength: 16, dexterity: 14, intelligence: 7, faith: 30, arcane: 50 },
    kit: [
      { id: 'dc-seal', name: 'Dragon Communion Seal', kind: 'catalyst', upgrade: 10 },
      { id: 'dragonmaw', name: 'Dragonmaw', kind: 'ash' },
      { id: 'greyoll', name: 'Greyoll’s Roar', kind: 'ash' },
      { id: 'rotten-breath', name: 'Rotten Breath', kind: 'ash' },
      { id: 'faithful-canvas', name: 'Faithful’s Canvas Talisman', kind: 'talisman' },
    ],
    need: ['loot:dragon-communion-seal', 'loot:dragonmaw', 'boss:ekzykes'],
  },
  {
    id: 'build:bolt-gransax',
    name: 'Bolt of Gransax sniper',
    tag: 'dexterity / lightning',
    why: 'Ancient Lightning Spear is a long-range nuke with a charged window, so Godfrey Icon and Shard of Alexander both apply. Pair it with a Lightning Nagakiba for the melee.',
    level: 150,
    stats: { vigor: 55, mind: 25, endurance: 30, strength: 20, dexterity: 70, intelligence: 9, faith: 8, arcane: 7 },
    kit: [
      { id: 'gransax', name: 'Bolt of Gransax', kind: 'armament', upgrade: 10 },
      { id: 'nagakiba', name: 'Nagakiba', kind: 'armament', affinity: 'Lightning', upgrade: 25 },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
      { id: 'lightning-scorp', name: 'Lightning Scorpion Charm', kind: 'talisman' },
    ],
    need: ['loot:bolt-gransax', 'loot:godfrey-icon', 'loot:shard-alexander'],
  },
  {
    id: 'build:frost-bleed',
    name: 'Frost-bleed twinblade',
    tag: 'dexterity / status',
    why: 'Twinblade jump L1s build bleed and frost at once; Rotten Winged Sword Insignia and Millicent’s Prosthesis ramp attack power as the chain lands. A dex status build that is not Rivers of Blood.',
    level: 150,
    stats: { vigor: 55, mind: 20, endurance: 30, strength: 16, dexterity: 55, intelligence: 20, faith: 8, arcane: 30 },
    kit: [
      { id: 'peeler', name: 'Godskin Peeler', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'eleonora', name: 'Eleonora’s Poleblade', kind: 'armament', upgrade: 10 },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
      { id: 'millicent', name: 'Millicent’s Prosthesis', kind: 'talisman' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
    ],
    need: ['loot:godskin-peeler', 'loot:eleonora-poleblade', 'loot:millicent-prosthesis'],
  },
  {
    id: 'build:greatshield-poke',
    name: 'Fingerprint poke',
    tag: 'strength / tank',
    why: 'Block with the highest-stability greatshield in the game and poke with a thrusting sword. Safe, boring, and one of the strongest PvE setups there is. Antspur adds Scarlet Rot through the shield.',
    level: 150,
    stats: { vigor: 60, mind: 12, endurance: 45, strength: 48, dexterity: 14, intelligence: 9, faith: 8, arcane: 7 },
    kit: [
      { id: 'fingerprint', name: 'Fingerprint Stone Shield', kind: 'shield', upgrade: 25 },
      { id: 'antspur', name: 'Antspur Rapier', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'greatshield-tal', name: 'Greatshield Talisman', kind: 'talisman' },
      { id: 'spear-tal', name: 'Spear Talisman', kind: 'talisman' },
      { id: 'curved-tal', name: 'Curved Sword Talisman', kind: 'talisman' },
    ],
    need: ['loot:fingerprint-shield', 'loot:antspur-rapier', 'loot:greatshield-talisman'],
  },
]
