import type { LoadoutSlot, Stats } from '../types'

export type PatchFlag = 'still-strong' | 'nerfed-but-works' | 'sote' | 'pre-1.08-dead'

export type OpBuild = {
  id: string
  name: string
  tag: string
  why: string
  level: number
  stats: Stats
  kit: LoadoutSlot[]
  need: string[]
  /**
   * Task 90: the collection order for this kit, as resolved catalog/loot fact
   * ids. `buildHunt` sorts `missing` by it so the first pinnable piece is the
   * right "Show on map" target. Only a handful of kits carry one.
   */
  route?: string[]
  /** Task 65: where the idea came from (title or URL). */
  source?: string
  /** Task 65: honest power state at the current 1.17 regulation line. */
  patch?: PatchFlag
}

export const opBuilds: OpBuild[] = [
  {
    id: 'build:rivers',
    name: 'Rivers of Blood',
    tag: 'bleed / arcane',
    why: 'Still deletes most of the Lands Between. Weak to high bleed resist (Malenia is the joke).',
    level: 150,
    stats: { vigor: 50, mind: 20, endurance: 25, strength: 12, dexterity: 40, intelligence: 9, faith: 8, arcane: 45 },
    kit: [
      { id: 'rob', name: 'Rivers of Blood', kind: 'armament', upgrade: 10 },
      { id: 'uchi', name: 'Uchigatana', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Winged Sword Insignia', kind: 'talisman' },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
    ],
    need: ['loot:rivers', 'loot:lord-blood-exul', 'boss:radahn'],
    route: ['loot:rivers', 'loot:uchigatana', 'loot:lord-blood-exul', 'loot:winged-sword-insignia', 'loot:white-mask', 'boss:radahn'],
  },
  {
    id: 'build:azur',
    name: 'Comet Azur glass',
    tag: 'intelligence',
    why: 'One-shot setups for dragons and late bosses if you can stand still. Terra Magicus + Graven-Mass + Magic Scorpion.',
    level: 150,
    stats: { vigor: 40, mind: 38, endurance: 20, strength: 8, dexterity: 16, intelligence: 80, faith: 6, arcane: 9 },
    kit: [
      { id: 'azur', name: 'Comet Azur', kind: 'ash' },
      { id: 'lusat', name: "Lusat's Glintstone Staff", kind: 'catalyst', upgrade: 10 },
      { id: 'icon', name: 'Radagon Icon', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
    ],
    need: ['loot:comet-azur', 'loot:radagon-icon', 'loot:godfrey-icon'],
    route: ['loot:comet-azur', 'loot:lusats-staff', 'loot:radagon-icon', 'loot:godfrey-icon'],
  },
  {
    id: 'build:blasphemous',
    name: 'Blasphemous Blade',
    tag: 'faith / quality',
    why: 'Taker’s Flames heals on every wave. Facetanks most of base game. Falls off vs holy resist in SotE.',
    level: 150,
    stats: { vigor: 55, mind: 25, endurance: 30, strength: 22, dexterity: 15, intelligence: 9, faith: 50, arcane: 8 },
    kit: [
      { id: 'bb', name: 'Blasphemous Blade', kind: 'armament', upgrade: 10 },
      { id: 'fgms', name: 'Flame, Grant Me Strength', kind: 'ash' },
      { id: 'vow', name: 'Golden Vow', kind: 'ash' },
      { id: 'fire-scorp', name: 'Fire Scorpion Charm', kind: 'talisman' },
    ],
    need: ['loot:blasphemous', 'loot:flame-grant', 'loot:golden-vow', 'boss:rykard'],
    route: ['loot:blasphemous', 'loot:flame-grant', 'loot:golden-vow', 'boss:rykard'],
  },
  {
    id: 'build:heavy-bonk',
    name: 'Heavy Knight bonk',
    tag: 'strength / tarnished pack',
    why: 'The pack’s Heavy Knight already has the poise. Giant-Crusher or Anvil Hammer, lion’s claw / cragblade.',
    level: 150,
    stats: { vigor: 55, mind: 12, endurance: 40, strength: 80, dexterity: 10, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'crusher', name: 'Giant-Crusher', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'anvil', name: 'Anvil Hammer', kind: 'armament', upgrade: 10 },
      { id: 'crag', name: 'Cragblade', kind: 'ash' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
    ],
    need: ['loot:anvil-hammer', 'loot:cragblade', 'loot:shard-alexander'],
    route: ['loot:anvil-hammer', 'loot:giant-crusher', 'loot:cragblade', 'loot:shard-alexander'],
  },
  {
    id: 'build:night-comet',
    name: 'Night Comet Sellia',
    tag: 'intelligence',
    why: 'Enemies barely dodge it. Staff of Loss in offhand. Best “I hate lock-on” sorcery.',
    level: 125,
    stats: { vigor: 40, mind: 30, endurance: 20, strength: 8, dexterity: 16, intelligence: 68, faith: 6, arcane: 9 },
    kit: [
      { id: 'nc', name: 'Night Comet', kind: 'ash' },
      { id: 'loss', name: 'Staff of Loss', kind: 'catalyst', upgrade: 25 },
      { id: 'carian', name: 'Carian Regal Scepter', kind: 'catalyst', upgrade: 10 },
    ],
    need: ['loot:night-comet', 'boss:rennala'],
  },
  {
    id: 'build:leontiel',
    name: 'Leontiel matador',
    tag: 'tarnished pack',
    why: 'Pack invader weapon. Reach + stance. Pairs with Heavy Knight or a dex hybrid after Radahn.',
    level: 150,
    stats: { vigor: 50, mind: 18, endurance: 28, strength: 22, dexterity: 50, intelligence: 9, faith: 8, arcane: 14 },
    kit: [
      { id: 'leo', name: "Leontiel's Greatsword", kind: 'armament', upgrade: 10 },
      { id: 'idus', name: 'Idus Sword', kind: 'armament', upgrade: 25 },
    ],
    need: ['loot:leontiel-gs', 'boss:leontiel', 'boss:radahn'],
  },
  // --- Expanded set (Task 40). Stats are recommended target spreads, not extracted
  // numbers. Weapon/skill facts cross-checked against the Fextralife wiki (patch 1.17,
  // Aug 2026); see docs/research/op-builds-pvp-tricks-sources.md for the source list.
  {
    id: 'build:greatsword-lions-claw',
    name: 'Greatsword Lion’s Claw',
    tag: 'strength / colossal',
    why: 'Lion’s Claw is unparryable, has hyper armour, and does real stance damage — on a colossal sword it breaks most bosses in two casts. Pure Strength, no casting stat tax.',
    level: 150,
    stats: { vigor: 60, mind: 12, endurance: 40, strength: 80, dexterity: 14, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'greatsword', name: 'Greatsword', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'lions-claw', name: 'Lion’s Claw', kind: 'ash' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'axe-tal', name: 'Axe Talisman', kind: 'talisman' },
      { id: 'claw-tal', name: 'Claw Talisman', kind: 'talisman' },
    ],
    need: ['loot:lions-claw', 'loot:shard-alexander', 'loot:greatsword'],
    route: ['loot:greatsword', 'loot:lions-claw', 'loot:shard-alexander', 'loot:axe-talisman', 'loot:claw-talisman'],
  },
  {
    id: 'build:dark-moon',
    name: 'Dark Moon Greatsword',
    tag: 'intelligence / frost',
    why: 'The Moonlight Greatsword beam on the charged heavy is ranged frost damage; Godfrey Icon, Magic Scorpion and Shard of Alexander all stack it. Frostbite then a heavy trade.',
    level: 150,
    stats: { vigor: 55, mind: 30, endurance: 25, strength: 16, dexterity: 12, intelligence: 70, faith: 7, arcane: 9 },
    kit: [
      { id: 'dmgs', name: 'Dark Moon Greatsword', kind: 'armament', upgrade: 10 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
    ],
    need: ['loot:dark-moon', 'loot:magic-scorpion', 'loot:godfrey-icon'],
    route: ['loot:dark-moon-gs', 'loot:magic-scorpion', 'loot:godfrey-icon', 'loot:shard-alexander'],
  },
  {
    id: 'build:moonveil',
    name: 'Moonveil Shinobi',
    tag: 'intelligence / dex',
    why: 'Transient Moonlight is a fast ranged slash that staggers at range. Powerstance with a Cold Uchigatana to stack Hemorrhage and Frostbite off the same L1 chain.',
    level: 125,
    stats: { vigor: 50, mind: 24, endurance: 22, strength: 12, dexterity: 40, intelligence: 50, faith: 7, arcane: 9 },
    kit: [
      { id: 'moonveil', name: 'Moonveil', kind: 'armament', upgrade: 10 },
      { id: 'uchi', name: 'Uchigatana', kind: 'armament', affinity: 'Cold', upgrade: 25 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'carian-crest', name: 'Carian Filigreed Crest', kind: 'talisman' },
    ],
    need: ['loot:moonveil', 'loot:magic-scorpion', 'boss:magma-wyrm'],
    route: ['loot:moonveil', 'loot:uchigatana', 'loot:magic-scorpion', 'loot:carian-filigreed-crest', 'boss:magma-wyrm'],
  },
  {
    id: 'build:blackflame',
    name: 'Black Flame Godslayer',
    tag: 'faith / incant',
    why: 'Black Flame burns a percentage of max HP on hit, so it keeps pace with boss health pools where flat-AR incantations fall off. The real faith caster build that is not Blasphemous Blade.',
    level: 150,
    stats: { vigor: 55, mind: 35, endurance: 25, strength: 16, dexterity: 18, intelligence: 7, faith: 65, arcane: 9 },
    kit: [
      { id: 'godslayer-seal', name: 'Godslayer’s Seal', kind: 'catalyst', upgrade: 25 },
      { id: 'black-flame', name: 'Black Flame', kind: 'ash' },
      { id: 'scouring', name: 'Scouring Black Flame', kind: 'ash' },
      { id: 'flock', name: 'Flock’s Canvas Talisman', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
    ],
    need: ['loot:black-flame', 'loot:godslayer-seal', 'boss:godskin-apostle'],
  },
  {
    id: 'build:dragon-communion',
    name: 'Dragon Communion',
    tag: 'arcane / faith',
    why: 'Dragon Communion Seal scales off Arcane, so one stat feeds every breath. Dragonmaw deletes anything that lets you stand still; Rotten Breath rots the rest. SotE-friendly.',
    level: 150,
    stats: { vigor: 55, mind: 30, endurance: 25, strength: 16, dexterity: 14, intelligence: 7, faith: 30, arcane: 50 },
    kit: [
      { id: 'dc-seal', name: 'Dragon Communion Seal', kind: 'catalyst', upgrade: 10 },
      { id: 'dragonmaw', name: 'Dragonmaw', kind: 'ash' },
      { id: 'greyoll', name: 'Greyoll’s Roar', kind: 'ash' },
      { id: 'rotten-breath', name: 'Rotten Breath', kind: 'ash' },
      { id: 'faithful-canvas', name: 'Faithful’s Canvas Talisman', kind: 'talisman' },
    ],
    need: ['loot:dragon-communion-seal', 'loot:dragonmaw', 'boss:ekzykes'],
  },
  {
    id: 'build:bolt-gransax',
    name: 'Bolt of Gransax sniper',
    tag: 'dexterity / lightning',
    why: 'Ancient Lightning Spear is a long-range nuke with a charged window, so Godfrey Icon and Shard of Alexander both apply. Pair it with a Lightning Nagakiba for the melee.',
    level: 150,
    stats: { vigor: 55, mind: 25, endurance: 30, strength: 20, dexterity: 70, intelligence: 9, faith: 8, arcane: 7 },
    kit: [
      { id: 'gransax', name: 'Bolt of Gransax', kind: 'armament', upgrade: 10 },
      { id: 'nagakiba', name: 'Nagakiba', kind: 'armament', affinity: 'Lightning', upgrade: 25 },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
      { id: 'lightning-scorp', name: 'Lightning Scorpion Charm', kind: 'talisman' },
    ],
    need: ['loot:bolt-gransax', 'loot:godfrey-icon', 'loot:shard-alexander'],
    route: ['loot:bolt-gransax', 'loot:godfrey-icon', 'loot:shard-alexander', 'loot:lightning-scorpion-charm'],
  },
  {
    id: 'build:frost-bleed',
    name: 'Frost-bleed twinblade',
    tag: 'dexterity / status',
    why: 'Twinblade jump L1s build bleed and frost at once; Rotten Winged Sword Insignia and Millicent’s Prosthesis ramp attack power as the chain lands. A dex status build that is not Rivers of Blood.',
    level: 150,
    stats: { vigor: 55, mind: 20, endurance: 30, strength: 16, dexterity: 55, intelligence: 20, faith: 8, arcane: 30 },
    kit: [
      { id: 'peeler', name: 'Godskin Peeler', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'eleonora', name: 'Eleonora’s Poleblade', kind: 'armament', upgrade: 10 },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
      { id: 'millicent', name: 'Millicent’s Prosthesis', kind: 'talisman' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
    ],
    need: ['loot:godskin-peeler', 'loot:eleonora-poleblade', 'loot:millicent-prosthesis'],
  },
  {
    id: 'build:greatshield-poke',
    name: 'Fingerprint poke',
    tag: 'strength / tank',
    why: 'Block with the highest-stability greatshield in the game and poke with a thrusting sword. Safe, boring, and one of the strongest PvE setups there is. Antspur adds Scarlet Rot through the shield.',
    level: 150,
    stats: { vigor: 60, mind: 12, endurance: 45, strength: 48, dexterity: 14, intelligence: 9, faith: 8, arcane: 7 },
    kit: [
      { id: 'fingerprint', name: 'Fingerprint Stone Shield', kind: 'shield', upgrade: 25 },
      { id: 'antspur', name: 'Antspur Rapier', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'greatshield-tal', name: 'Greatshield Talisman', kind: 'talisman' },
      { id: 'spear-tal', name: 'Spear Talisman', kind: 'talisman' },
      { id: 'curved-tal', name: 'Curved Sword Talisman', kind: 'talisman' },
    ],
    need: ['loot:fingerprint-shield', 'loot:antspur-rapier', 'loot:greatshield-talisman'],
  },

  // --- Task 65 additions. Stats are target spreads (legal for the listed RL, not extracted).
  // Every `need` id is a real fact id: it either resolves to a loot/catalog row or is reported
  // in buildHunt()'s `unresolved` list. `why` is one original sentence.
  {
    id: 'build:pest-threads-plus',
    name: 'Pest-Thread Spears faith',
    tag: 'faith / arcane',
    why: 'Pest-Thread Spears hits many times through a big body, and the Dragon Communion Seal turns Arcane into incantation scaling on the same spread.',
    level: 150,
    stats: { vigor: 55, mind: 30, endurance: 25, strength: 16, dexterity: 14, intelligence: 7, faith: 40, arcane: 40 },
    kit: [
      { id: 'pest', name: 'Pest-Thread Spears', kind: 'ash' },
      { id: 'dc-seal', name: 'Dragon Communion Seal', kind: 'catalyst', upgrade: 10 },
      { id: 'faithful-canvas', name: "Faithful's Canvas Talisman", kind: 'talisman' },
      { id: 'flock', name: "Flock's Canvas Talisman", kind: 'talisman' },
    ],
    need: ['loot:pest-threads-plus', 'loot:dragon-communion-seal', 'item:flock-canvas-talisman'],
    patch: 'still-strong',
    source: 'Fextralife, Pest-Thread Spears (patch 1.17).',
  },
  {
    id: 'build:mimic-status',
    name: 'Mimic Tear bleed',
    tag: 'bleed / summon',
    why: 'The Mimic copies your bleed kit and doubles the Hemorrhage pressure, so the fight ends before either of you runs out of flasks.',
    level: 150,
    stats: { vigor: 50, mind: 20, endurance: 25, strength: 12, dexterity: 40, intelligence: 9, faith: 8, arcane: 45 },
    kit: [
      { id: 'mimic', name: 'Mimic Tear Ashes', kind: 'ash', upgrade: 10 },
      { id: 'rob', name: 'Rivers of Blood', kind: 'armament', upgrade: 10 },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
    ],
    need: ['loot:mimic', 'loot:rivers', 'loot:lord-blood-exul', 'loot:white-mask'],
    patch: 'still-strong',
    source: 'Fextralife, Mimic Tear Ashes (patch 1.17).',
  },
  {
    id: 'build:sword-night-flame',
    name: 'Sword of Night and Flame',
    tag: 'int / faith hybrid',
    why: 'Night and Flame stance still gives a ranged magic beam and a close flame sweep, so one weapon covers both ranges without a second catalyst.',
    level: 150,
    stats: { vigor: 55, mind: 25, endurance: 25, strength: 16, dexterity: 16, intelligence: 40, faith: 40, arcane: 8 },
    kit: [
      { id: 'sonaf', name: 'Sword of Night and Flame', kind: 'armament', upgrade: 10 },
      { id: 'carian-crest', name: 'Carian Filigreed Crest', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
      { id: 'old-lords', name: "Old Lord's Talisman", kind: 'talisman' },
    ],
    need: ['loot:sword-night-flame', 'loot:carian-filigreed-crest', 'loot:radagon-icon', 'loot:old-lords-talisman'],
    patch: 'nerfed-but-works',
    source: 'Fextralife, Sword of Night and Flame (patch 1.17).',
  },
  {
    id: 'build:deaths-poker',
    name: "Death's Poker frost",
    tag: 'int / frost',
    why: 'Ghostflame Ignition leaves a patch that keeps ticking, and the charged R2 beam is a safe ranged punish on anything that respects frost.',
    level: 150,
    stats: { vigor: 55, mind: 22, endurance: 25, strength: 14, dexterity: 18, intelligence: 55, faith: 8, arcane: 9 },
    kit: [
      { id: 'deaths-poker', name: "Death's Poker", kind: 'armament', upgrade: 10 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'old-lords', name: "Old Lord's Talisman", kind: 'talisman' },
    ],
    need: ['loot:deaths-poker', 'loot:magic-scorpion', 'loot:shard-alexander', 'loot:old-lords-talisman'],
    patch: 'still-strong',
    source: 'Fextralife, Death\u2019s Poker (patch 1.17).',
  },
  {
    id: 'build:wing-of-astel',
    name: 'Wing of Astel',
    tag: 'int / dex',
    why: 'Nebula is a free ranged burst on a light curved sword, and the weapon still keeps normal dex scaling for the melee you actually land.',
    level: 150,
    stats: { vigor: 55, mind: 25, endurance: 22, strength: 12, dexterity: 40, intelligence: 45, faith: 8, arcane: 9 },
    kit: [
      { id: 'wing-astel', name: 'Wing of Astel', kind: 'armament', upgrade: 10 },
      { id: 'graven-mass', name: 'Graven-Mass Talisman', kind: 'talisman' },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
    ],
    need: ['loot:wing-of-astel', 'loot:graven-mass', 'loot:magic-scorpion', 'loot:ritual-sword'],
    patch: 'still-strong',
    source: 'Fextralife, Wing of Astel (patch 1.17).',
  },
  {
    id: 'build:giant-crusher-jump',
    name: 'Giant-Crusher jump attack',
    tag: 'strength / jump',
    why: 'A jump attack from a colossal greathammer does huge stance damage, and Claw plus Axe Talisman both reward the same jumping R2.',
    level: 150,
    stats: { vigor: 60, mind: 12, endurance: 40, strength: 80, dexterity: 14, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'crusher', name: 'Giant-Crusher', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'claw-tal', name: 'Claw Talisman', kind: 'talisman' },
      { id: 'axe-tal', name: 'Axe Talisman', kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
    ],
    need: ['loot:giant-crusher', 'loot:claw-talisman', 'loot:axe-talisman', 'loot:shard-alexander'],
    patch: 'still-strong',
    source: 'Fextralife, Giant-Crusher (patch 1.17).',
  },
  {
    id: 'build:bloodfiends-arm',
    name: "Bloodfiend's Arm",
    tag: 'arcane / bleed',
    why: 'The Bloodfiend\u2019s Arm builds Hemorrhage on a big arcane-scaled strike, so each opening both procs bleed and heals you back.',
    level: 150,
    stats: { vigor: 55, mind: 20, endurance: 25, strength: 18, dexterity: 20, intelligence: 9, faith: 8, arcane: 50 },
    kit: [
      { id: 'bloodfiend', name: "Bloodfiend's Arm", kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
    ],
    need: ['loot:bloodfiends-arm', 'loot:white-mask', 'loot:lord-blood-exul', 'item:rotten-winged-sword-insignia'],
    patch: 'sote',
    source: 'Fextralife, Bloodfiend\u2019s Arm (SotE, patch 1.17).',
  },
  {
    id: 'build:great-stars-crag',
    name: 'Great Stars Cragblade',
    tag: 'strength / poise',
    why: 'Cragblade adds stamina damage against guards and poise damage in the open, which a heavy Great Stars turns into constant staggers.',
    level: 150,
    stats: { vigor: 60, mind: 12, endurance: 40, strength: 70, dexterity: 14, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'great-stars', name: 'Great Stars', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'crag', name: 'Cragblade', kind: 'ash' },
      { id: 'axe-tal', name: 'Axe Talisman', kind: 'talisman' },
      { id: 'claw-tal', name: 'Claw Talisman', kind: 'talisman' },
    ],
    need: ['loot:great-stars', 'loot:cragblade', 'loot:axe-talisman', 'loot:claw-talisman'],
    patch: 'still-strong',
    source: 'Fextralife, Cragblade (patch 1.17).',
  },
  {
    id: 'build:starscourge',
    name: 'Starscourge pull',
    tag: 'strength / gravity',
    why: 'Starcaller Cry pulls a whole pack into one swing, so the Starscourge Greatsword clears groups and stance-breaks single targets at the same time.',
    level: 150,
    stats: { vigor: 60, mind: 15, endurance: 35, strength: 70, dexterity: 12, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'starscourge', name: 'Starscourge Greatsword', kind: 'armament', upgrade: 10 },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'great-jar', name: "Great-Jar's Arsenal", kind: 'talisman' },
      { id: 'bullgoat', name: "Bull-Goat's Talisman", kind: 'talisman' },
    ],
    need: ['loot:starscourge-greatsword', 'loot:shard-alexander', 'loot:great-jar', 'loot:bullgoat'],
    patch: 'nerfed-but-works',
    source: 'Fextralife, Starscourge Greatsword (patch 1.17).',
  },
  {
    id: 'build:meteoric-ore',
    name: 'Meteoric Ore arcane',
    tag: 'strength / arcane',
    why: 'The Ancient Meteoric Ore Greatsword scales off Arcane as well as Strength, so one spread feeds both the weapon and a bleed-heavy talisman set.',
    level: 150,
    stats: { vigor: 55, mind: 15, endurance: 30, strength: 50, dexterity: 12, intelligence: 9, faith: 8, arcane: 40 },
    kit: [
      { id: 'meteoric-ore', name: 'Ancient Meteoric Ore Greatsword', kind: 'armament', upgrade: 10 },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
    ],
    need: ['loot:ancient-meteoric-ore-gs', 'loot:lord-blood-exul', 'loot:shard-alexander', 'loot:white-mask'],
    patch: 'sote',
    source: 'Fextralife, Ancient Meteoric Ore Greatsword (SotE, patch 1.17).',
  },
  {
    id: 'build:ripple-arc',
    name: 'Ripple arcane',
    tag: 'arcane / status',
    why: 'The Ripple Crescent Halberd scales purely on Arcane, so the whole stat line goes into bleed buildup and Lord of Blood\u2019s Exultation uptime.',
    level: 125,
    stats: { vigor: 50, mind: 15, endurance: 25, strength: 16, dexterity: 30, intelligence: 9, faith: 8, arcane: 45 },
    kit: [
      { id: 'ripple', name: 'Ripple Crescent Halberd', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Winged Sword Insignia', kind: 'talisman' },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
    ],
    need: ['loot:ripple-crescent-halberd', 'loot:lord-blood-exul', 'loot:winged-sword-insignia', 'loot:white-mask'],
    patch: 'still-strong',
    source: 'Fextralife, Ripple Crescent Halberd (patch 1.17).',
  },
  {
    id: 'build:eleonora',
    name: "Eleonora's Poleblade",
    tag: 'dex / arcane bleed',
    why: 'Bloodblade Dance chains fast Hemorrhage on a dex-arcane twinblade, and the two Winged Insignia talismans ramp the damage as the combo lands.',
    level: 125,
    stats: { vigor: 50, mind: 18, endurance: 25, strength: 16, dexterity: 43, intelligence: 9, faith: 8, arcane: 35 },
    kit: [
      { id: 'eleonora', name: "Eleonora's Poleblade", kind: 'armament', upgrade: 10 },
      { id: 'millicent', name: "Millicent's Prosthesis", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
    ],
    need: ['loot:eleonora-poleblade', 'item:millicent-prosthesis', 'item:rotten-winged-sword-insignia', 'loot:lord-blood-exul'],
    patch: 'still-strong',
    source: 'Fextralife, Eleonora\u2019s Poleblade (patch 1.17).',
  },
  {
    id: 'build:helphens',
    name: "Helphen's Steeple",
    tag: 'int / strength death',
    why: 'Helphen\u2019s Steeple buffs itself with ghostflame on the skill, so a strength-int spread gets frostbite pressure and a real melee threat on one weapon.',
    level: 150,
    stats: { vigor: 55, mind: 20, endurance: 28, strength: 16, dexterity: 14, intelligence: 50, faith: 8, arcane: 9 },
    kit: [
      { id: 'helphen', name: "Helphen's Steeple", kind: 'armament', upgrade: 10 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
    ],
    need: ['loot:helphens-steeple', 'loot:magic-scorpion', 'loot:shard-alexander', 'loot:ritual-sword'],
    patch: 'still-strong',
    source: 'Fextralife, Helphen\u2019s Steeple (patch 1.17).',
  },
  {
    id: 'build:marais',
    name: "Marais Executioner's Sword",
    tag: 'arcane / strength',
    why: 'Eochaid\u2019s Dancing Blade spins the sword into a buzzsaw that scales off Arcane, so the arcane-bleed talisman stack lifts the whole skill.',
    level: 150,
    stats: { vigor: 55, mind: 15, endurance: 30, strength: 30, dexterity: 14, intelligence: 9, faith: 8, arcane: 45 },
    kit: [
      { id: 'marais', name: "Marais Executioner's Sword", kind: 'armament', upgrade: 10 },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
    ],
    need: ['loot:marais-executioner-sword', 'loot:shard-alexander', 'loot:lord-blood-exul', 'item:rotten-winged-sword-insignia'],
    patch: 'still-strong',
    source: 'Fextralife, Marais Executioner\u2019s Sword (patch 1.17).',
  },
]
