/**
 * Task 106 — the mechanics glossary.
 *
 * Short, self-contained reference cards for the systems a player asks about
 * between fights: poise, stance, soft caps, flasks, Great Runes, status effects,
 * two-handing, NG+ and the rest. Each card is `mechanic:<slug>` and is registered
 * as a `kind: 'mechanic'` entity by `src/lib/entityGraph.ts`, so a name like
 * "Poise" is a link to a real entity page (docs/USAGE-MODEL.md rule 1).
 *
 * Numbers are quoted from the Fextralife wiki pages and the long-standing
 * community stat tables (patch 1.17 regulation line). Where the repo already
 * owns the authoritative table — `src/lib/softCaps.ts`, `src/knowledge/equipLoad.ts`,
 * `src/lib/blessings.ts` — the card agrees with it rather than duplicating a
 * different value. Prose is deliberately brief: long text belongs in Lore tabs.
 */
export type MechanicCategory =
  | 'combat'
  | 'stats'
  | 'equipment'
  | 'status'
  | 'progression'
  | 'online'
  | 'world'

export type MechanicCard = {
  /** Stable fact id, `mechanic:<slug>`. */
  id: string
  slug: string
  title: string
  category: MechanicCategory
  /** 2–4 sentences. */
  body: string
  /** The numbers a player needs in one line each. */
  numbers: string[]
  /** Related entity ids, linked by the entity graph's `relatedLore` edges. */
  related: string[]
  /** Extra names the term is known by, used by `src/lib/glossary.ts`. */
  aliases: string[]
  source: string
}

const SRC_WIKI = 'Fextralife Elden Ring wiki (patch 1.17).'
const SRC_COMMUNITY = 'Community stat testing, patch 1.17.'

export const mechanics: MechanicCard[] = [
  {
    id: 'mechanic:poise',
    slug: 'poise',
    title: 'Poise',
    category: 'combat',
    body: 'Poise is the hidden stat that decides whether an incoming hit interrupts your attack or cast. Every hit drains poise by that attack’s poise damage; reaching zero staggers you and briefly opens you up. Poise refills on its own after roughly thirty seconds without being hit.',
    numbers: ['51 poise — stops most standard PvE hits', '101 poise — endures heavier attacks', 'Refills about 30s after the last hit'],
    related: ['mechanic:hyperarmor', 'mechanic:stance-break'],
    aliases: ['poise damage'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:stance-break',
    slug: 'stance-break',
    title: 'Stance break',
    category: 'combat',
    body: 'Bosses and large enemies have a separate hidden stance meter that fills as you land charged heavies, jump attacks and many Ashes of War. When it breaks, the enemy is staggered and a glowing weak point lets you take a critical hit. The meter drains slowly, so damage must be delivered in a burst.',
    numbers: ['Charged R2, jump attacks and Ashes deal the most stance damage', 'A break allows one critical hit', 'Stance decays over time between hits'],
    related: ['mechanic:critical-hits', 'mechanic:poise', 'mechanic:jump-attacks'],
    aliases: ['stance', 'stance damage', 'stagger'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:critical-hits',
    slug: 'critical-hits',
    title: 'Backstabs, ripostes & critical hits',
    category: 'combat',
    body: 'A critical hit multiplies your weapon’s attack rating rather than adding a flat amount. Backstabs land from directly behind an unaware or outmanoeuvred enemy, while ripostes follow a successful parry or a stance break. The Misericorde is the classic critical weapon because of its very high critical modifier.',
    numbers: ['Misericorde has the highest critical modifier at 140', 'Most daggers sit around 110–140', 'A stance break or parry opens the riposte window'],
    related: ['mechanic:stance-break', 'mechanic:parry', 'mechanic:stealth'],
    aliases: ['backstab', 'riposte', 'critical hit', 'crit'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:guard-counter',
    slug: 'guard-counter',
    title: 'Guard counter',
    category: 'combat',
    body: 'Block an incoming attack, then press the heavy attack button immediately to launch a guard counter. It deals much more stance damage than a normal heavy and often breaks a boss’s stance in a few uses. The timing is forgiving as long as the block connected first.',
    numbers: ['Input: block, then heavy attack', 'Deals high stance damage', 'Works with any shield or weapon block'],
    related: ['mechanic:guard-boost', 'mechanic:stance-break', 'mechanic:parry'],
    aliases: ['guard counters'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:hyperarmor',
    slug: 'hyperarmor',
    title: 'Hyperarmor',
    category: 'combat',
    body: 'Hyperarmor is temporary immunity to being staggered during specific attack animations. It is granted by the move itself, not by your poise, so a colossal swing can power through a hit that would interrupt a lighter weapon. Your poise still decides whether damage that lands outside those frames staggers you.',
    numbers: ['Granted by certain attacks and Ashes of War', 'Active during startup and part of the swing', 'Independent of the poise stat'],
    related: ['mechanic:poise', 'mechanic:two-handing', 'mechanic:upgrades'],
    aliases: ['hyper armor', 'hyper-armour', 'armor frames'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:two-handing',
    slug: 'two-handing',
    title: 'Two-handing',
    category: 'combat',
    body: 'Holding a weapon in both hands multiplies your effective Strength by one and a half, rounded down. That raises both the Strength scaling of the weapon and your effective Strength for meeting its requirement, letting a lower-Strength build wield heavy armaments. It does not change Dexterity, Intelligence, Faith or Arcane.',
    numbers: ['Effective Strength = floor(Strength × 1.5)', 'Also boosts Strength scaling', 'Lowers the Strength requirement you must meet'],
    related: ['mechanic:stat-requirements', 'mechanic:powerstance', 'mechanic:weapon-scaling'],
    aliases: ['two handing', 'two-hand', '2-handing'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:powerstance',
    slug: 'powerstance',
    title: 'Powerstancing',
    category: 'combat',
    body: 'Equipping two weapons of the same class, one in each hand, unlocks paired attacks that swing both at once. The L1 chain and the jumping L1 hit with both weapons, stacking status buildup and stance damage in a single swing. It costs more stamina than a normal attack line.',
    numbers: ['Same weapon class required in each hand', 'Paired L1 and jumping L1 hit with both weapons', 'Status buildup from both weapons stacks'],
    related: ['mechanic:status-buildup', 'mechanic:two-handing', 'mechanic:stamina'],
    aliases: ['power stance', 'powerstanced', 'dual wield'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:jump-attacks',
    slug: 'jump-attacks',
    title: 'Jump attacks',
    category: 'combat',
    body: 'A jumping heavy attack leaps in, hits hard, does solid stance damage and has a short recovery. It is the safest way to punish a boss because you are already moving out of range as the swing ends. The Claw Talisman boosts jump attack damage and the Raptor’s Black Feathers add another jump-attack bonus.',
    numbers: ['High stance damage with low recovery', 'Claw Talisman: +jump attack damage', 'Raptor’s Black Feathers enhance jump attacks'],
    related: ['mechanic:stance-break', 'mechanic:buff-stacking', 'mechanic:powerstance'],
    aliases: ['jumping attack', 'jump attack'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:parry',
    slug: 'parry',
    title: 'Parrying',
    category: 'combat',
    body: 'A parry deflects an incoming attack during a short window and leaves the attacker open to a riposte. Small shields and the Parry Ash of War have the widest timing, while medium shields and weapons parry poorly or not at all. Some attacks, including many grabs and colossal swings, cannot be parried.',
    numbers: ['Riposte follows a successful parry', 'Small shields have the most forgiving window', 'Not every attack can be parried'],
    related: ['mechanic:critical-hits', 'mechanic:guard-counter', 'mechanic:guard-boost'],
    aliases: ['parries', 'parry window'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:guard-boost',
    slug: 'guard-boost',
    title: 'Blocking & guard boost',
    category: 'combat',
    body: 'Blocking an attack absorbs part of its damage and drains stamina based on your shield’s guard boost. A higher guard boost means less stamina lost per blocked hit, which lets you hold the line and set up guard counters. Greatshields and the Greatshield Talisman push guard boost highest.',
    numbers: ['Guard boost reduces stamina lost per block', 'Greatshield Talisman raises guard boost', 'A broken guard leaves you staggered'],
    related: ['mechanic:guard-counter', 'mechanic:stamina', 'mechanic:defense-negation'],
    aliases: ['guard boost', 'guard', 'shield'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:stamina',
    slug: 'stamina',
    title: 'Stamina',
    category: 'combat',
    body: 'Stamina is spent on attacks, rolls, running, jumping and blocking. It regenerates after a short delay and the rate is raised by the Green Turtle Talisman and similar effects. Running out mid-swing usually means eating the next hit, so manage the bar rather than mashing.',
    numbers: ['Regenerates after a short delay', 'Green Turtle Talisman boosts stamina recovery', 'Endurance 50 is the stamina soft cap'],
    related: ['mechanic:soft-cap-endurance', 'mechanic:equip-load', 'mechanic:guard-boost'],
    aliases: ['stamina recovery', 'stamina regen'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:soft-cap-vigor',
    slug: 'soft-cap-vigor',
    title: 'Vigor soft caps',
    category: 'stats',
    body: 'Vigor is the stat that buys you mistakes, and it is the first one most builds should push. Its HP gains fall off sharply after forty, then again after sixty, so points spent past the second cap return very little. Sixty Vigor is a common endgame target for a comfortable health pool.',
    numbers: ['40 Vigor — first HP soft cap', '60 Vigor — second soft cap', '99 Vigor is the hard cap'],
    related: ['mechanic:soft-cap-mind', 'mechanic:soft-cap-endurance', 'mechanic:soft-cap-offensive'],
    aliases: ['vigor softcap', 'health soft cap'],
    source: SRC_COMMUNITY,
  },
  {
    id: 'mechanic:soft-cap-mind',
    slug: 'soft-cap-mind',
    title: 'Mind soft caps',
    category: 'stats',
    body: 'Mind raises your FP pool and therefore how many spells, Ashes of War and summons you can chain before drinking. The FP gains slow down after forty and nearly stop after sixty. Casters usually stop at forty early and push toward sixty later.',
    numbers: ['40 Mind — first FP soft cap', '60 Mind — second soft cap', 'FP refills with a Flask of Cerulean Tears'],
    related: ['mechanic:soft-cap-vigor', 'mechanic:soft-cap-endurance', 'mechanic:memory-slots'],
    aliases: ['mind softcap', 'fp soft cap', 'fp'],
    source: SRC_COMMUNITY,
  },
  {
    id: 'mechanic:soft-cap-endurance',
    slug: 'soft-cap-endurance',
    title: 'Endurance soft caps',
    category: 'stats',
    body: 'Endurance raises stamina as well as maximum equip load. Stamina gains are largely done past thirty and effectively stop at fifty, but the equip-load curve keeps climbing all the way to ninety-nine. That is why a heavy build may keep investing long after a light one stops.',
    numbers: ['30 Endurance — first stamina soft cap', '50 Endurance — stamina hard cap', 'Equip load keeps rising to 99'],
    related: ['mechanic:stamina', 'mechanic:equip-load', 'mechanic:soft-cap-vigor'],
    aliases: ['endurance softcap', 'stamina soft cap'],
    source: SRC_COMMUNITY,
  },
  {
    id: 'mechanic:soft-cap-offensive',
    slug: 'soft-cap-offensive',
    title: 'Offensive stat soft caps',
    category: 'stats',
    body: 'Strength, Dexterity, Intelligence, Faith and Arcane all scale weapon and spell damage through breakpoints around twenty, sixty and eighty. Points before twenty are the most efficient, the stretch to sixty is the main investment, and gains past eighty are small. Matching the weapon’s own scaling letters is what makes a point pay off.',
    numbers: ['20 — first scaling soft cap', '60 — second soft cap', '80 — third soft cap'],
    related: ['mechanic:weapon-scaling', 'mechanic:stat-requirements', 'mechanic:affinities'],
    aliases: ['offensive soft caps', 'damage soft cap', 'stat soft caps'],
    source: SRC_COMMUNITY,
  },
  {
    id: 'mechanic:equip-load',
    slug: 'equip-load',
    title: 'Equip load classes',
    category: 'equipment',
    body: 'Your equipped weight as a share of maximum equip load decides your roll. Under thirty percent you light roll with the most distance, from thirty to seventy you medium roll, and above seventy you heavy roll with a long recovery. Going over one hundred percent overloads you and slows movement to a crawl.',
    numbers: ['Light: under 30%', 'Medium: 30–70%', 'Heavy: 70–100%', 'Overloaded: over 100%'],
    related: ['mechanic:soft-cap-endurance', 'mechanic:stamina', 'mechanic:talisman-slots'],
    aliases: ['equip load', 'equipment load', 'roll type', 'heavy roll', 'fat roll'],
    source: 'Elden Ring wiki "Equip Load" table; matches src/knowledge/equipLoad.ts.',
  },
  {
    id: 'mechanic:damage-types',
    slug: 'damage-types',
    title: 'Damage types',
    category: 'combat',
    body: 'Physical damage splits into standard, strike, slash and pierce, and enemies resist each differently. Elemental damage comes as magic, fire, lightning and holy, and a weapon can carry a physical component plus one or more elements. The type matters more than the number against a boss with a lopsided negation.',
    numbers: ['Physical: standard, strike, slash, pierce', 'Elemental: magic, fire, lightning, holy', 'Some enemies take bonus damage from one type'],
    related: ['mechanic:defense-negation', 'mechanic:affinities', 'mechanic:status-buildup'],
    aliases: ['damage type', 'physical damage', 'elemental damage'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:defense-negation',
    slug: 'defense-negation',
    title: 'Defense & negation',
    category: 'combat',
    body: 'Defense is the flat number that shaves damage off every hit, while negation is the percentage that reduces what is left. Physical defense comes mostly from your stats and armour, and elemental negation comes from armour and talismans. Because the two apply in sequence, stacking a matching negation talisman can blunt a boss’s signature element.',
    numbers: ['Defense reduces flat damage', 'Negation reduces the remainder by a percentage', 'Armour and talismans supply most negation'],
    related: ['mechanic:damage-types', 'mechanic:guard-boost', 'mechanic:buff-stacking'],
    aliases: ['defense', 'negation', 'damage negation', 'absorption'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:attack-rating',
    slug: 'attack-rating',
    title: 'Attack rating (AR)',
    category: 'equipment',
    body: 'Attack rating, or AR, is the total damage number a weapon shows across every damage type it deals, after the character’s stats are applied through scaling. Buffs, enemy negation and status buildup are not part of the displayed AR. The number the game shows is the summed damage types floored, matching the AR calculator the app uses.',
    numbers: ['AR sums every damage type the weapon deals', 'Scaling letters decide how much your stats add', 'Status buildup and enemy negation are not included'],
    related: ['mechanic:weapon-scaling', 'mechanic:soft-cap-offensive', 'mechanic:affinities'],
    aliases: ['AR', 'attack power', 'attack rating'],
    source: 'Vendored vanilla 1.17 regulation data via the AR engine in src/lib/ar.ts (ThomasJClark calculator, MIT).',
  },
  {
    id: 'mechanic:scaling-letters',
    slug: 'scaling-letters',
    title: 'Scaling letters',
    category: 'equipment',
    body: 'The letter beside a stat on a weapon shows how strongly its AR grows from that stat, running E, D, C, B, A, S from weakest to strongest. The grade is a band of the weapon’s stored scaling coefficient, so S adds far more per point than E. Upgrading a weapon usually raises these coefficients, which is why a weapon can climb a letter as it is reinforced.',
    numbers: ['S: 1.75 and above', 'A: 1.40–1.74', 'B: 0.90–1.39', 'C: 0.60–0.89', 'D: 0.25–0.59', 'E: 0.01–0.24'],
    related: ['mechanic:weapon-scaling', 'mechanic:attack-rating', 'mechanic:soft-cap-offensive'],
    aliases: ['scaling grade', 'letter grade', 'scaling letters'],
    source: 'Vendored vanilla 1.17 regulation scaling tiers (scalingTiers in regulation-vanilla-v1.17.json).',
  },
  {
    id: 'mechanic:weapon-scaling',
    slug: 'weapon-scaling',
    title: 'Weapon scaling',
    category: 'equipment',
    body: 'Every weapon scales its attack rating with one or more stats, shown as a letter grade from E up to S. Levelling the stats the weapon actually uses, and upgrading the weapon, raises that contribution. A weapon with high base damage and poor scaling wants minimum stats, while an S-scaling weapon rewards heavy investment.',
    numbers: ['Grades run E, D, C, B, A, S', 'Upgrades improve scaling on most weapons', 'Two-handing boosts effective Strength scaling'],
    related: ['mechanic:soft-cap-offensive', 'mechanic:two-handing', 'mechanic:upgrades'],
    aliases: ['scaling', 'scaling grade'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:stat-requirements',
    slug: 'stat-requirements',
    title: 'Stat requirements',
    category: 'equipment',
    body: 'Each armament and catalyst lists minimum Strength, Dexterity, Intelligence, Faith and Arcane. Failing a requirement cuts your damage sharply and can make the weapon bounce off enemies, even though you can still swing it. Two-handing lowers the Strength requirement you need to meet.',
    numbers: ['Failing a requirement reduces damage', 'Two-handing covers part of the Strength requirement', 'Catalysts also gate which spells work'],
    related: ['mechanic:two-handing', 'mechanic:weapon-scaling', 'mechanic:affinities'],
    aliases: ['stat requirement', 'requirements'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:affinities',
    slug: 'affinities',
    title: 'Weapon affinities',
    category: 'equipment',
    body: 'An affinity changes a weapon’s damage type and scaling: Heavy favours Strength, Keen favours Dexterity, Quality uses both, and Magic and Cold add Intelligence. Fire and Flame Art add fire with Strength and Faith scaling respectively, Lightning is Dexterity, and Sacred is Faith. Blood, Poison and Occult scale with Arcane.',
    numbers: ['Heavy/Keen/Quality — physical builds', 'Magic/Cold — Intelligence', 'Fire/Flame Art — fire scaling', 'Lightning — Dexterity, Sacred — Faith', 'Blood/Poison/Occult — Arcane'],
    related: ['mechanic:ashes-of-war', 'mechanic:whetblades', 'mechanic:weapon-scaling'],
    aliases: ['affinity', 'weapon affinity', 'infusion'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:ashes-of-war',
    slug: 'ashes-of-war',
    title: 'Ashes of War',
    category: 'equipment',
    body: 'An Ash of War grants a weapon a skill and, on most armaments, lets you choose its affinity. Applying one overwrites the previous skill and affinity, and some Ashes can be duplicated for a second copy with Lost Ashes of War. Unique weapons and many boss weapons cannot take Ashes at all.',
    numbers: ['Sets both a skill and an affinity', 'Lost Ashes of War duplicate an owned Ash', 'Unique and boss weapons usually cannot be changed'],
    related: ['mechanic:affinities', 'mechanic:whetblades', 'mechanic:upgrades'],
    aliases: ['ash of war', 'weapon art', 'skill'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:whetblades',
    slug: 'whetblades',
    title: 'Whetblades',
    category: 'equipment',
    body: 'A Whetblade unlocks extra affinity choices when you apply an Ash of War, regardless of the Ash you use. The Iron Whetblade gives Heavy, Keen and Quality; Glintstone gives Magic and Cold; Red-Hot gives Fire and Flame Art; Sanctified gives Sacred; and the Black Whetblade gives Blood, Poison and Occult.',
    numbers: ['Iron — Heavy, Keen, Quality', 'Glintstone — Magic, Cold', 'Red-Hot — Fire, Flame Art', 'Sanctified — Sacred', 'Black — Blood, Poison, Occult'],
    related: ['mechanic:affinities', 'mechanic:ashes-of-war', 'item:black-whetblade', 'item:sanctified-whetblade'],
    aliases: ['whetblade', 'iron whetblade', 'glintstone whetblade'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:upgrades',
    slug: 'upgrades',
    title: 'Upgrades & smithing',
    category: 'equipment',
    body: 'Regular armaments upgrade to plus twenty-five with Smithing Stones and somber armaments to plus ten with Somber Smithing Stones. The final step of either track needs an Ancient Dragon Smithing Stone from a late-game or optional boss. Spirit Ashes upgrade the same way with Grave Glovewort and Great Grave Glovewort.',
    numbers: ['Regular weapons: +25 with Smithing Stones', 'Somber weapons: +10 with Somber Stones', 'Final step needs an Ancient Dragon Smithing Stone', 'Spirit Ashes: Grave Glovewort tiers'],
    related: ['mechanic:affinities', 'mechanic:spirit-ashes', 'item:ancient-dragon-smithing-stone'],
    aliases: ['smithing', 'upgrade', 'weapon upgrades', 'somber'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:spirit-ashes',
    slug: 'spirit-ashes',
    title: 'Spirit Ashes',
    category: 'combat',
    body: 'Spirit Ashes summon an ally at the gravestone markers found before most boss arenas. You need the Spirit Calling Bell from Renna and enough FP to pay the summon cost. They cannot be used in co-op or in the handful of arenas that disable them.',
    numbers: ['Requires the Spirit Calling Bell', 'Costs FP to summon', 'Unavailable in co-op', 'Upgraded with Grave Glovewort'],
    related: ['mechanic:summoning-pools', 'mechanic:co-op', 'mechanic:upgrades'],
    aliases: ['spirit ash', 'summon', 'summons'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:summoning-pools',
    slug: 'summoning-pools',
    title: 'Summoning pools',
    category: 'online',
    body: 'Each Effigy of the Martyr you activate adds that area to your summoning pool. The Small Golden Effigy then places your sign at every activated pool at once, and the Small Red Effigy does the same for invasions. Pools persist for the whole run once touched.',
    numbers: ['Activate Effigies of the Martyr', 'Small Golden Effigy broadcasts to all pools', 'Small Red Effigy does the same for invasions'],
    related: ['mechanic:co-op', 'mechanic:invasions', 'mechanic:matchmaking'],
    aliases: ['summon pool', 'effigy of the martyr', 'effigies'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:co-op',
    slug: 'co-op',
    title: 'Co-op & Furlcalling Finger Remedy',
    category: 'online',
    body: 'A Furlcalling Finger Remedy reveals summon signs left by other players, which you touch to call a cooperator. A password lets you link with a specific friend regardless of level, and the host’s session is what the group plays in. Co-op disables Torrent and Spirit Ashes and opens the world to invaders.',
    numbers: ['Furlcalling Finger Remedy reveals summon signs', 'Password bypasses level matchmaking', 'No Torrent or Spirit Ashes in co-op'],
    related: ['mechanic:summoning-pools', 'mechanic:invasions', 'mechanic:matchmaking'],
    aliases: ['furlcalling finger remedy', 'coop', 'cooperative'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:matchmaking',
    slug: 'matchmaking',
    title: 'Co-op & PvP matchmaking',
    category: 'online',
    body: 'Summon range is decided by both your rune level and the highest-upgraded weapon you have ever held. That weapon memory means a low-level character who picked up a late-game weapon can only be matched with tougher players. A password overrides both limits and downscales the stronger player to the host.',
    numbers: ['Matches use rune level plus highest weapon upgrade', 'Password ignores the range', 'Password summons are downscaled to the host'],
    related: ['mechanic:co-op', 'mechanic:invasions', 'mechanic:upgrades'],
    aliases: ['summon range', 'level range', 'matchmaking'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:invasions',
    slug: 'invasions',
    title: 'Invasions',
    category: 'online',
    body: 'Bloody Fingers and Recusant Fingers let you invade a host’s world to fight for runes and rewards. The Taunter’s Tongue invites invaders into your own world, and the Blue Cipher Ring calls hunters to defend a host in trouble. Invaders are always outnumbered and downscaled when the host has cooperators.',
    numbers: ['Bloody Finger and Recusant Finger invade', 'Taunter’s Tongue invites invaders', 'Blue Cipher Ring summons hunters'],
    related: ['mechanic:co-op', 'mechanic:matchmaking', 'mechanic:summoning-pools'],
    aliases: ['invasion', 'invader', 'taunter’s tongue', 'taunters tongue'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-buildup',
    slug: 'status-buildup',
    title: 'Status buildup & resistance',
    category: 'status',
    body: 'Status effects fill a hidden bar as hits land, and the effect triggers when the bar fills. After it triggers the bar empties and your resistance to that status rises, so the same effect takes longer the next time. Buildup also decays gradually while you are not being hit.',
    numbers: ['Bar fills with each hit, then triggers the effect', 'Resistance rises after each proc', 'Buildup decays over time'],
    related: ['mechanic:status-bleed', 'mechanic:status-frostbite', 'mechanic:damage-types'],
    aliases: ['status effect', 'status effects', 'buildup'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-bleed',
    slug: 'status-bleed',
    title: 'Blood loss (bleed)',
    category: 'status',
    body: 'Blood loss drains a percentage of the target’s maximum HP plus a flat amount when the bar fills. It scales with Arcane on most blood-affinity weapons and is the fastest way to delete a high-health boss. Because resistance rises after each proc, bleed builds pair best with rapid multi-hit attacks.',
    numbers: ['Deals a percentage of max HP plus a flat chunk', 'Scales with Arcane', 'Resistance rises after each proc'],
    related: ['mechanic:status-buildup', 'mechanic:affinities', 'mechanic:powerstance'],
    aliases: ['bleed', 'blood loss', 'hemorrhage'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-frostbite',
    slug: 'status-frostbite',
    title: 'Frostbite',
    category: 'status',
    body: 'Frostbite deals burst damage and temporarily lowers the target’s absorption, so follow-up hits land harder. It can trigger again after a cooldown, and cold affinity weapons also keep a physical component. Fire damage removes the frost debuff early, so avoid mixing the two.',
    numbers: ['Burst damage plus reduced absorption', 'Can re-proc after a cooldown', 'Fire cleanses the frost debuff'],
    related: ['mechanic:status-buildup', 'mechanic:affinities', 'mechanic:damage-types'],
    aliases: ['frost', 'cold', 'frostbite proc'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-poison',
    slug: 'status-poison',
    title: 'Poison',
    category: 'status',
    body: 'Poison applies a damage-over-time effect that ticks down the target’s HP for a set duration. The stronger variant is Deadly Poison, which does more damage per tick. Poison scales with Arcane and is best used to soften a boss you expect to fight for a while.',
    numbers: ['Damage over time for a fixed duration', 'Deadly Poison ticks harder', 'Scales with Arcane'],
    related: ['mechanic:status-buildup', 'mechanic:status-scarlet-rot', 'mechanic:affinities'],
    aliases: ['poisoned', 'deadly poison'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-scarlet-rot',
    slug: 'status-scarlet-rot',
    title: 'Scarlet rot',
    category: 'status',
    body: 'Scarlet rot is a stronger damage-over-time than poison and is the signature tool of Caelid and the Haligtree. A rot proc ticks for a large share of health over a short window, which makes it ideal against bosses with huge health pools. Boluses and Preserving Boluses cure it.',
    numbers: ['Higher damage per tick than poison', 'Shorter, sharper duration', 'Cured by Preserving Boluses'],
    related: ['mechanic:status-poison', 'mechanic:status-buildup', 'mechanic:damage-types'],
    aliases: ['rot', 'scarlet rot proc'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-sleep',
    slug: 'status-sleep',
    title: 'Sleep',
    category: 'status',
    body: 'Sleep incapacitates the target for a short time, letting you land free hits or reposition. It only works on enemies that are not immune, and any damage wakes them, so it is a control tool rather than a damage tool. Sleep Pots are the usual delivery method.',
    numbers: ['Immobilises susceptible enemies', 'Any damage wakes the target', 'Sleep Pots are the common source'],
    related: ['mechanic:status-buildup', 'mechanic:status-madness', 'mechanic:crafting'],
    aliases: ['sleeping', 'sleep pot'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-madness',
    slug: 'status-madness',
    title: 'Madness',
    category: 'status',
    body: 'Madness damages both HP and FP and staggers the victim when it triggers. It only affects humanoid, Tarnished-descended enemies, so it does nothing to most beasts and monsters. In PvP it is one of the strongest burst windows in the game.',
    numbers: ['Damages HP and FP', 'Humanoid or Tarnished targets only', 'Staggers on proc'],
    related: ['mechanic:status-buildup', 'mechanic:status-sleep', 'mechanic:damage-types'],
    aliases: ['frenzy', 'frenzied flame', 'madness proc'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:status-death-blight',
    slug: 'status-death-blight',
    title: 'Death blight',
    category: 'status',
    body: 'Death blight kills the target outright when the bar fills, with no saving throw. It is rare from the player side and mostly appears on certain enemies and in PvP. Its bar decays quickly, so it must be applied in a burst.',
    numbers: ['Instant death on proc', 'Bar decays quickly', 'Mostly an enemy and PvP threat'],
    related: ['mechanic:status-buildup', 'mechanic:status-madness', 'mechanic:defense-negation'],
    aliases: ['deathblight', 'blight'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:rune-loss',
    slug: 'rune-loss',
    title: 'Rune loss & recovery',
    category: 'progression',
    body: 'When you die you drop all carried runes at the spot where you fell. Return and touch them to recover the lot; die again before that and the first drop is gone for good. A Sacrificial Twig in your inventory prevents the loss once.',
    numbers: ['Carried runes drop on death', 'A second death erases the first drop', 'Sacrificial Twig protects one death'],
    related: ['mechanic:sites-of-grace', 'mechanic:ng-plus', 'mechanic:great-runes'],
    aliases: ['lost runes', 'dropped runes', 'rune recovery'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:great-runes',
    slug: 'great-runes',
    title: 'Great Runes',
    category: 'progression',
    body: 'Great Runes are won from the shardbearers and equipped at any Site of Grace, but they do nothing until activated with a Rune Arc. Each one grants a different boon, from a flat boost to every stat to more health, and the effect ends when you die. They are a run-long buff, not a permanent stat.',
    numbers: ['Equip at a Site of Grace', 'Activate with a Rune Arc', 'Effect ends on death', 'Godrick’s grants +5 to all stats'],
    related: ['mechanic:rune-arc', 'mechanic:rune-loss', 'item:godrick-great-rune', 'item:malenia-great-rune'],
    aliases: ['great rune', 'shardbearer rune'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:rune-arc',
    slug: 'rune-arc',
    title: 'Rune Arc',
    category: 'progression',
    body: 'A Rune Arc activates the Great Rune you have equipped at a Site of Grace. The effect lasts until you die, so a careful player can keep one running for a long stretch. Rune Arcs drop from co-op and invasion wins as well as from enemies.',
    numbers: ['Activates the equipped Great Rune', 'Lasts until death', 'Drops from online wins'],
    related: ['mechanic:great-runes', 'mechanic:co-op', 'mechanic:invasions'],
    aliases: ['rune arcs', 'rune arc activation'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:scadutree-blessing',
    slug: 'scadutree-blessing',
    title: 'Scadutree Blessing',
    category: 'progression',
    body: 'Scadutree Fragments raise your Scadutree Blessing, which increases the damage you deal and reduces the damage you take inside the Realm of Shadow. The blessing only applies in the DLC, and it is the main counter to the region’s inflated enemy scaling. It runs to level twenty with fifty fragments.',
    numbers: ['Levels 1–20', '50 Scadutree Fragments total', 'Only applies in the Realm of Shadow', 'Raises damage dealt and damage negation'],
    related: ['mechanic:revered-spirit-ash', 'item:shadow-realm-blessing', 'region:shadow'],
    aliases: ['scadutree fragment', 'scadutree', 'shadow realm blessing'],
    source: 'Fextralife; matches src/lib/blessings.ts thresholds.',
  },
  {
    id: 'mechanic:revered-spirit-ash',
    slug: 'revered-spirit-ash',
    title: 'Revered Spirit Ash',
    category: 'progression',
    body: 'Revered Spirit Ashes raise the Revered Spirit Ash Blessing, which strengthens your summoned spirits in the Realm of Shadow. It is a separate track from the Scadutree Blessing and only affects summons, not you. It runs to level ten with twenty-five ashes.',
    numbers: ['Levels 1–10', '25 Revered Spirit Ashes total', 'Boosts summoned spirits only', 'DLC only'],
    related: ['mechanic:scadutree-blessing', 'mechanic:spirit-ashes', 'item:revered-ash'],
    aliases: ['revered ash', 'spirit ash blessing'],
    source: 'Fextralife; matches src/lib/blessings.ts thresholds.',
  },
  {
    id: 'mechanic:ng-plus',
    slug: 'ng-plus',
    title: 'NG+ scaling',
    category: 'progression',
    body: 'Starting Journey 2 keeps your level, gear, items and most graces but makes every enemy tougher and worth more runes. The difficulty climbs each cycle up to Journey 7, after which it stops rising. Some quest items and key items are reset, so re-earn anything a quest needs.',
    numbers: ['Keeps level, gear and items', 'Enemies scale harder each cycle', 'Caps at NG+7 (Journey 8)', 'Runes from enemies increase'],
    related: ['mechanic:larval-tears', 'mechanic:rune-loss', 'mechanic:great-runes'],
    aliases: ['new game plus', 'ng+', 'journey 2'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:buff-stacking',
    slug: 'buff-stacking',
    title: 'Buff stacking',
    category: 'combat',
    body: 'Buffs fall into categories such as aura, body, weapon and shield, and two buffs from the same category overwrite each other. Golden Vow is an aura and Flame, Grant Me Strength is a body buff, so they stack with each other and with a weapon grease. The Wondrous Physick supplies another independent layer.',
    numbers: ['Same-category buffs overwrite', 'Aura + body + weapon + Physick stack', 'Golden Vow is an aura, Flame, Grant Me Strength is a body buff'],
    related: ['mechanic:wondrous-physick', 'mechanic:affinities', 'mechanic:damage-types'],
    aliases: ['buff stack', 'buff stacking', 'stacking buffs'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:wondrous-physick',
    slug: 'wondrous-physick',
    title: 'Wondrous Physick',
    category: 'equipment',
    body: 'The Flask of Wondrous Physick holds two Crystal Tears that you choose and mix at a Site of Grace. Drinking it applies both effects at once and the flask refills whenever you rest, so it is a free burst buff each attempt. Tears range from flat stat boosts to the famous Cerulean Hidden Tear that removes FP costs.',
    numbers: ['Two Crystal Tears per mix', 'Refills at every rest', 'Cerulean Hidden Tear removes FP cost for 15 seconds'],
    related: ['mechanic:buff-stacking', 'mechanic:affinities', 'mechanic:sites-of-grace'],
    aliases: ['physick', 'crystal tear', 'flask of wondrous physick'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:memory-slots',
    slug: 'memory-slots',
    title: 'Memory slots & Memory Stones',
    category: 'equipment',
    body: 'Memory slots decide how many sorceries and incantations you can have equipped at once. Each Memory Stone you find adds one slot, and the starting count depends on your class. The cap is ten slots once every stone is collected.',
    numbers: ['Each Memory Stone adds one slot', 'Starting slots vary by class', 'Maximum of 10 slots'],
    related: ['mechanic:soft-cap-mind', 'mechanic:sorcery', 'mechanic:incantation'],
    aliases: ['memory stone', 'spell slots', 'memory slot'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:sorcery',
    slug: 'sorcery',
    title: 'Sorceries',
    category: 'equipment',
    body: 'Sorceries are cast with a staff and scale with Intelligence, with a few exceptions that dip into other stats. They cost FP and are gated by the staff’s stats and upgrade level as well as your own. Glintstone magic is the core family, with frost and gravity branches.',
    numbers: ['Cast with a staff', 'Scale mainly with Intelligence', 'Cost FP per cast', 'Staff upgrade raises damage'],
    related: ['mechanic:incantation', 'mechanic:memory-slots', 'mechanic:affinities'],
    aliases: ['sorceries', 'staff magic', 'glintstone'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:incantation',
    slug: 'incantation',
    title: 'Incantations',
    category: 'equipment',
    body: 'Incantations are cast with a sacred seal and scale with Faith, though dragon and blood incantations can also use Arcane. They cost FP and cover healing, buffs, fire and lightning. Like sorceries, the seal’s stats and upgrade level shape the damage.',
    numbers: ['Cast with a sacred seal', 'Scale mainly with Faith', 'Some Dragon incantations use Arcane', 'Cost FP per cast'],
    related: ['mechanic:sorcery', 'mechanic:memory-slots', 'mechanic:status-frostbite'],
    aliases: ['incantations', 'faith magic', 'seal magic'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:talisman-slots',
    slug: 'talisman-slots',
    title: 'Talisman slots',
    category: 'equipment',
    body: 'You begin with a single talisman slot and expand it with Talisman Pouches found through the run. Four slots is the maximum, which is why a build’s talismans are a real trade-off rather than a checklist. Talismans apply their effect continuously with no FP cost.',
    numbers: ['Start with one slot', 'Four slots at maximum', 'No FP cost to wear'],
    related: ['mechanic:equip-load', 'mechanic:buff-stacking', 'mechanic:soft-cap-vigor'],
    aliases: ['talisman pouch', 'talisman slot'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:larval-tears',
    slug: 'larval-tears',
    title: 'Rebirth & Larval Tears',
    category: 'progression',
    body: 'After defeating Rennala you can ask her to rebirth your character, redistributing every level you have spent. Each rebirth costs one Larval Tear, which are found through the world and bought from a few merchants. Your level total and collected gear do not change, only where the points sit.',
    numbers: ['One Larval Tear per rebirth', 'Available after defeating Rennala', 'Total level stays the same', 'Rebirth also lets you change appearance'],
    related: ['mechanic:ng-plus', 'mechanic:soft-cap-offensive', 'mechanic:stat-requirements'],
    aliases: ['larval tear', 'respec', 'rebirth'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:flask-charges',
    slug: 'flask-charges',
    title: 'Flask charges (Golden Seeds)',
    category: 'equipment',
    body: 'Golden Seeds increase the number of charges in your Flask of Crimson Tears and Flask of Cerulean Tears. The first seed or two cost one each and later upgrades cost more, so a full run needs thirty seeds. The two flask types share the same total charge pool.',
    numbers: ['Up to 14 total flask charges', '30 Golden Seeds in the base game', 'Each upgrade costs an increasing number of seeds', 'Crimson and Cerulean share the pool'],
    related: ['mechanic:flask-potency', 'mechanic:sites-of-grace', 'mechanic:soft-cap-mind'],
    aliases: ['golden seed', 'flask charges', 'crimson flask', 'cerulean flask'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:flask-potency',
    slug: 'flask-potency',
    title: 'Flask potency (Sacred Tears)',
    category: 'equipment',
    body: 'Sacred Tears upgrade the potency of both flasks, healing more per Crimson charge and restoring more FP per Cerulean charge. There are twelve Sacred Tears and each adds one upgrade level. Full potency makes a flask heal roughly twice a starting flask.',
    numbers: ['12 Sacred Tears total', 'Each tear adds one upgrade level', 'Raises HP healed and FP restored'],
    related: ['mechanic:flask-charges', 'mechanic:sites-of-grace', 'mechanic:soft-cap-vigor'],
    aliases: ['sacred tear', 'flask upgrade', 'flask potency'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:torrent',
    slug: 'torrent',
    title: 'Torrent',
    category: 'world',
    body: 'Torrent is the spectral steed summoned with the Spectral Steed Whistle. He can double jump and is much faster than running, which makes open-world travel and many field bosses easier. Torrent is banned inside most legacy dungeons and boss arenas and cannot be used in co-op.',
    numbers: ['Summoned with the Spectral Steed Whistle', 'Double jump and fast travel across open ground', 'Unavailable in legacy dungeons, most bosses and co-op'],
    related: ['mechanic:co-op', 'mechanic:sites-of-grace', 'mechanic:map-fragments'],
    aliases: ['spectral steed', 'horse', 'steed'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:sites-of-grace',
    slug: 'sites-of-grace',
    title: 'Sites of Grace',
    category: 'world',
    body: 'Sites of Grace are the checkpoints you rest at to refill flasks, reset enemies and fast travel. Resting revives normal enemies and respawns bosses you have not killed, so it is also how you retry a fight. The map shows every grace you have discovered and lets you jump between them.',
    numbers: ['Refill flasks and reset enemies', 'Fast travel from the map', 'Respawn point on death'],
    related: ['mechanic:flask-charges', 'mechanic:map-fragments', 'mechanic:rune-loss'],
    aliases: ['site of grace', 'grace', 'bonfire'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:map-fragments',
    slug: 'map-fragments',
    title: 'Map fragments',
    category: 'world',
    body: 'Each region’s map is blank until you collect its Map Fragment from a stele marked on the map edge. Until then you can still travel and explore, but you have no map of the area. Collecting the fragment reveals the terrain, graces and many markers for that region.',
    numbers: ['One fragment per major region', 'Found at a marked stele', 'Reveals terrain and map markers'],
    related: ['mechanic:sites-of-grace', 'mechanic:torrent', 'mechanic:stealth'],
    aliases: ['map fragment', 'maps'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:crafting',
    slug: 'crafting',
    title: 'Crafting & cookbooks',
    category: 'world',
    body: 'The crafting kit lets you turn gathered materials into throwables, pots, greases, arrows and perfumes. Cookbooks unlock new recipes, and each one is found in a specific place or sold by a merchant. Crafted pots and perfumes are among the best status and burst tools in the game.',
    numbers: ['Craft from gathered materials', 'Cookbooks unlock recipes', 'Pots, greases, arrows and perfumes'],
    related: ['mechanic:status-sleep', 'mechanic:status-poison', 'mechanic:affinities'],
    aliases: ['cookbook', 'crafting kit', 'craft'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:stealth',
    slug: 'stealth',
    title: 'Stealth',
    category: 'world',
    body: 'Crouching lowers the noise you make and the distance at which enemies notice you, and tall grass hides you completely. From behind, an unaware enemy can be backstabbed or simply walked past. The Crepus’s Vial and similar talismans improve stealth further.',
    numbers: ['Crouch to reduce detection range', 'Tall grass fully conceals you', 'Backstabs land from directly behind'],
    related: ['mechanic:critical-hits', 'mechanic:map-fragments', 'mechanic:torrent'],
    aliases: ['sneak', 'crouch', 'hidden'],
    source: SRC_WIKI,
  },
  {
    id: 'mechanic:point-of-no-return',
    slug: 'point-of-no-return',
    title: 'Point of no return',
    category: 'world',
    body: 'Resting at the Forge of the Giants and burning the Erdtree permanently changes the world. Leyndell becomes the Ashen Capital, several quest lines close and some items can no longer be obtained. The app warns before this and other gates so you can finish what matters first.',
    numbers: ['Triggered at the Forge of the Giants grace', 'Leyndell becomes the Ashen Capital', 'Several NPC quests lock out', 'Some items become permanently missable'],
    related: ['mechanic:ng-plus', 'mechanic:sites-of-grace', 'mechanic:larval-tears'],
    aliases: ['no return', 'forge of the giants', 'burning the erdtree'],
    source: SRC_WIKI,
  },
]

const byId = new Map(mechanics.map((m) => [m.id, m]))

export function mechanicById(id: string): MechanicCard | undefined {
  return byId.get(id)
}

/**
 * Task 115 — the short tooltip definition for a mechanic term: the card title
 * plus the first one or two sentences of its body, trimmed to a glanceable
 * length. Returns undefined when the id is not an authored mechanic.
 */
export function mechanicSummary(id: string, sentences = 2, max = 240): string | undefined {
  const card = byId.get(id)
  if (!card) return undefined
  const parts = card.body.match(/[^.!?]+[.!?]+/g) ?? [card.body]
  let text = parts.slice(0, sentences).join(' ').trim()
  if (text.length > max) text = `${text.slice(0, max).trimEnd()}…`
  return text
}

/** Every autolink term a mechanic card contributes, keyed by entity id. */
export function mechanicTerms(): { term: string; id: string; label: string }[] {
  const out: { term: string; id: string; label: string }[] = []
  for (const m of mechanics) {
    for (const term of [m.title, ...m.aliases]) {
      if (term.trim()) out.push({ term, id: m.id, label: term })
    }
  }
  return out
}
