/**
 * Player-model/cosmetic data only. NOT combat stats.
 * Do not use for absorb/resistance/damage calculations — see docs/REVIEW.md.
 *
 * Source: EanNewton "ER NPC Levels" public Google Sheet (player-model NPCs).
 * https://docs.google.com/spreadsheets/d/1jZokIy9PcX5UhUPcTe992aP21JiXL015sfP4sjYktu4/
 *
 * These are the level and stat allocation an NPC has as a player model
 * (character-creation numbers). They are display flavor for Codex cards, not
 * enemy combat params. The Build lab's "what should I hit this with" table is
 * ERDB NpcParam (absorb/stance/resistances/status) and is a separate source.
 *
 * Generated by scripts/ingest-npc-display.mjs — do not edit by hand.
 */

export type NpcDisplayStats = {
  vigor: number
  mind: number
  endurance: number
  strength: number
  dexterity: number
  intelligence: number
  faith: number
  arcane: number
}

export type NpcDisplayCard = {
  id: string
  /** Internal NPC row id from the sheet, e.g. "23000". */
  modelId: string
  name: string
  /** Player-model level, not a boss/enemy combat level. */
  level: number
  /** Player-model stat allocation (cosmetic reference only). */
  stats: NpcDisplayStats
}

export const npcDisplayCards: NpcDisplayCard[] = [
  { id: 'npc-display:23000', modelId: '23000', name: "Tanith, Volcano Manor Proprietess", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 10, dexterity: 10, intelligence: 16, faith: 11, arcane: 8 } },
  { id: 'npc-display:23010', modelId: '23010', name: "White Mask Varré", level: 154, stats: { vigor: 28, mind: 6, endurance: 7, strength: 8, dexterity: 16, intelligence: 1, faith: 14, arcane: 24 } },
  { id: 'npc-display:23040', modelId: '23040', name: "Festering Fingerprint Vyke", level: 29, stats: { vigor: 28, mind: 9, endurance: 11, strength: 14, dexterity: 20, intelligence: 4, faith: 18, arcane: 4 } },
  { id: 'npc-display:23041', modelId: '23041', name: "Roundtable Knight Vyke", level: 50, stats: { vigor: 28, mind: 9, endurance: 9, strength: 16, dexterity: 20, intelligence: 4, faith: 18, arcane: 4 } },
  { id: 'npc-display:23070', modelId: '23070', name: "Preceptor Seluvis", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 16, dexterity: 14, intelligence: 9, faith: 8, arcane: 8 } },
  { id: 'npc-display:23090', modelId: '23090', name: "Patches", level: 18, stats: { vigor: 24, mind: 9, endurance: 14, strength: 12, dexterity: 15, intelligence: 8, faith: 8, arcane: 7 } },
  { id: 'npc-display:23091', modelId: '23091', name: "Patches", level: 18, stats: { vigor: 24, mind: 9, endurance: 14, strength: 12, dexterity: 15, intelligence: 8, faith: 8, arcane: 7 } },
  { id: 'npc-display:23092', modelId: '23092', name: "Patches", level: 5, stats: { vigor: 28, mind: 9, endurance: 11, strength: 10, dexterity: 10, intelligence: 7, faith: 4, arcane: 5 } },
  { id: 'npc-display:23100', modelId: '23100', name: "Irina of Morne", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 6, faith: 27, arcane: 12 } },
  { id: 'npc-display:23101', modelId: '23101', name: "Lightseeker Hyetta", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 6, faith: 27, arcane: 12 } },
  { id: 'npc-display:23102', modelId: '23102', name: "Finger Maiden Hyetta (Bloody)", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 6, faith: 27, arcane: 12 } },
  { id: 'npc-display:23110', modelId: '23110', name: "Castellan Edgar", level: 50, stats: { vigor: 22, mind: 9, endurance: 11, strength: 20, dexterity: 20, intelligence: 11, faith: 3, arcane: 1 } },
  { id: 'npc-display:23120', modelId: '23120', name: "Castellan Jerren", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 18, intelligence: 16, faith: 3, arcane: 3 } },
  { id: 'npc-display:23121', modelId: '23121', name: "Castellan Jerren", level: 23, stats: { vigor: 45, mind: 10, endurance: 11, strength: 3, dexterity: 3, intelligence: 10, faith: 10, arcane: 10 } },
  { id: 'npc-display:23122', modelId: '23122', name: "Castellan Jerren", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 18, intelligence: 16, faith: 3, arcane: 3 } },
  { id: 'npc-display:23130', modelId: '23130', name: "Rya the Scout", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 9, faith: 8, arcane: 28 } },
  { id: 'npc-display:23140', modelId: '23140', name: "Knight Diallos", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 12, dexterity: 20, intelligence: 9, faith: 4, arcane: 10 } },
  { id: 'npc-display:23150', modelId: '23150', name: "Lanya", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 16, dexterity: 4, intelligence: 6, faith: 28, arcane: 1 } },
  { id: 'npc-display:23160', modelId: '23160', name: "Sorceress Sellen", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 21, faith: 4, arcane: 4 } },
  { id: 'npc-display:23161', modelId: '23161', name: "Sorceress Sellen", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 21, faith: 4, arcane: 4 } },
  { id: 'npc-display:23162', modelId: '23162', name: "Sorceress Sellen", level: 93, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 21, faith: 4, arcane: 4 } },
  { id: 'npc-display:23163', modelId: '23163', name: "Sorceress Sellen", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 21, faith: 4, arcane: 4 } },
  { id: 'npc-display:23180', modelId: '23180', name: "Yura, Hunter of Bloody Fingers", level: 25, stats: { vigor: 28, mind: 8, endurance: 11, strength: 18, dexterity: 22, intelligence: 7, faith: 4, arcane: 6 } },
  { id: 'npc-display:23181', modelId: '23181', name: "Yura, Hunter of Bloody Fingers", level: 25, stats: { vigor: 28, mind: 8, endurance: 11, strength: 18, dexterity: 22, intelligence: 7, faith: 4, arcane: 6 } },
  { id: 'npc-display:23182', modelId: '23182', name: "Shabriri", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 11, dexterity: 15, intelligence: 6, faith: 20, arcane: 3 } },
  { id: 'npc-display:23183', modelId: '23183', name: "Yura, Hunter of Bloody Fingers", level: 25, stats: { vigor: 28, mind: 8, endurance: 11, strength: 18, dexterity: 22, intelligence: 7, faith: 4, arcane: 6 } },
  { id: 'npc-display:23184', modelId: '23184', name: "Shabriri", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 11, dexterity: 15, intelligence: 6, faith: 20, arcane: 3 } },
  { id: 'npc-display:23190', modelId: '23190', name: "D, Hunter of the Dead", level: 18, stats: { vigor: 21, mind: 5, endurance: 9, strength: 19, dexterity: 19, intelligence: 1, faith: 22, arcane: 1 } },
  { id: 'npc-display:23191', modelId: '23191', name: "D, Hunter of the Dead", level: 18, stats: { vigor: 21, mind: 5, endurance: 9, strength: 19, dexterity: 19, intelligence: 1, faith: 22, arcane: 1 } },
  { id: 'npc-display:23192', modelId: '23192', name: "D's Younger Sibling", level: 18, stats: { vigor: 21, mind: 5, endurance: 9, strength: 19, dexterity: 19, intelligence: 1, faith: 22, arcane: 1 } },
  { id: 'npc-display:23193', modelId: '23193', name: "D, Hunter of the Dead (Bloody)", level: 18, stats: { vigor: 21, mind: 5, endurance: 9, strength: 19, dexterity: 19, intelligence: 1, faith: 22, arcane: 1 } },
  { id: 'npc-display:23194', modelId: '23194', name: "D, Hunter of the Dead", level: 18, stats: { vigor: 21, mind: 5, endurance: 9, strength: 19, dexterity: 19, intelligence: 1, faith: 22, arcane: 1 } },
  { id: 'npc-display:23195', modelId: '23195', name: "D, Hunter of the Dead", level: 18, stats: { vigor: 21, mind: 5, endurance: 9, strength: 19, dexterity: 19, intelligence: 1, faith: 22, arcane: 1 } },
  { id: 'npc-display:23200', modelId: '23200', name: "Heartbroken Maiden", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 16, faith: 18, arcane: 11 } },
  { id: 'npc-display:23201', modelId: '23201', name: "Roderika, Spirit Tuner", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 16, faith: 18, arcane: 11 } },
  { id: 'npc-display:23210', modelId: '23210', name: "Kenneth Haight, Limgrave Heir", level: 20, stats: { vigor: 20, mind: 9, endurance: 11, strength: 8, dexterity: 22, intelligence: 6, faith: 18, arcane: 5 } },
  { id: 'npc-display:23220', modelId: '23220', name: "Fia, Deathbed Companion", level: 18, stats: { vigor: 22, mind: 12, endurance: 11, strength: 10, dexterity: 10, intelligence: 16, faith: 8, arcane: 8 } },
  { id: 'npc-display:23221', modelId: '23221', name: "Fia, Deathbed Companion", level: 18, stats: { vigor: 22, mind: 12, endurance: 11, strength: 10, dexterity: 10, intelligence: 16, faith: 8, arcane: 8 } },
  { id: 'npc-display:23222', modelId: '23222', name: "Fia, Deathbed Companion (Bloody)", level: 18, stats: { vigor: 22, mind: 12, endurance: 11, strength: 10, dexterity: 10, intelligence: 16, faith: 8, arcane: 8 } },
  { id: 'npc-display:23230', modelId: '23230', name: "Dung Eater", level: 18, stats: { vigor: 22, mind: 7, endurance: 11, strength: 15, dexterity: 19, intelligence: 6, faith: 15, arcane: 2 } },
  { id: 'npc-display:23231', modelId: '23231', name: "Dung Eater", level: 71, stats: { vigor: 22, mind: 7, endurance: 11, strength: 15, dexterity: 19, intelligence: 6, faith: 15, arcane: 2 } },
  { id: 'npc-display:23232', modelId: '23232', name: "Dung Eater", level: 63, stats: { vigor: 33, mind: 8, endurance: 4, strength: 28, dexterity: 28, intelligence: 20, faith: 20, arcane: 1 } },
  { id: 'npc-display:23240', modelId: '23240', name: "Sir Gideon Ofnir, the All-Knowing", level: 32, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 8 } },
  { id: 'npc-display:23241', modelId: '23241', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23242', modelId: '23242', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23243', modelId: '23243', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23244', modelId: '23244', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23245', modelId: '23245', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23246', modelId: '23246', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23247', modelId: '23247', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23248', modelId: '23248', name: "Sir Gideon Ofnir, the All-Knowing", level: 36, stats: { vigor: 31, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 15, faith: 20, arcane: 3 } },
  { id: 'npc-display:23249', modelId: '23249', name: "Sir Gideon Ofnir, the All-Knowing", level: 41, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 20, faith: 24, arcane: 8 } },
  { id: 'npc-display:23250', modelId: '23250', name: "Sorcerer Rogier", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 8, dexterity: 24, intelligence: 17, faith: 3, arcane: 3 } },
  { id: 'npc-display:23251', modelId: '23251', name: "Sorcerer Rogier", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 8, dexterity: 24, intelligence: 17, faith: 3, arcane: 3 } },
  { id: 'npc-display:23252', modelId: '23252', name: "Sorcerer Rogier", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 8, dexterity: 24, intelligence: 17, faith: 3, arcane: 3 } },
  { id: 'npc-display:23260', modelId: '23260', name: "Knight Bernahl", level: 29, stats: { vigor: 31, mind: 9, endurance: 11, strength: 15, dexterity: 10, intelligence: 10, faith: 13, arcane: 9 } },
  { id: 'npc-display:23261', modelId: '23261', name: "Recusant Bernahl", level: 29, stats: { vigor: 31, mind: 5, endurance: 11, strength: 24, dexterity: 20, intelligence: 5, faith: 25, arcane: 2 } },
  { id: 'npc-display:23262', modelId: '23262', name: "Recusant Bernahl", level: 131, stats: { vigor: 31, mind: 5, endurance: 11, strength: 24, dexterity: 20, intelligence: 5, faith: 25, arcane: 2 } },
  { id: 'npc-display:23270', modelId: '23270', name: "Eleonora, Violent Bloody Finger", level: 60, stats: { vigor: 31, mind: 5, endurance: 5, strength: 12, dexterity: 21, intelligence: 4, faith: 16, arcane: 19 } },
  { id: 'npc-display:23271', modelId: '23271', name: "Eleonora, Violent Bloody Finger", level: 60, stats: { vigor: 31, mind: 5, endurance: 5, strength: 12, dexterity: 21, intelligence: 4, faith: 16, arcane: 19 } },
  { id: 'npc-display:23290', modelId: '23290', name: "Lionel the Lionhearted", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 16, dexterity: 16, intelligence: 15, faith: 4, arcane: 4 } },
  { id: 'npc-display:23291', modelId: '23291', name: "Lionel the Lionhearted", level: 12, stats: { vigor: 28, mind: 15, endurance: 21, strength: 2, dexterity: 1, intelligence: 6, faith: 8, arcane: 10 } },
  { id: 'npc-display:23310', modelId: '23310', name: "Blackguard", level: 18, stats: { vigor: 22, mind: 9, endurance: 16, strength: 24, dexterity: 23, intelligence: 1, faith: 1, arcane: 1 } },
  { id: 'npc-display:23311', modelId: '23311', name: "Blackguard (Bloody)", level: 18, stats: { vigor: 22, mind: 9, endurance: 16, strength: 24, dexterity: 23, intelligence: 1, faith: 1, arcane: 1 } },
  { id: 'npc-display:23312', modelId: '23312', name: "Blackguard", level: 18, stats: { vigor: 22, mind: 9, endurance: 16, strength: 24, dexterity: 23, intelligence: 1, faith: 1, arcane: 1 } },
  { id: 'npc-display:23320', modelId: '23320', name: "???", level: 18, stats: { vigor: 22, mind: 39, endurance: 11, strength: 6, dexterity: 4, intelligence: 6, faith: 8, arcane: 1 } },
  { id: 'npc-display:23330', modelId: '23330', name: "Sorcerer Thops", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 11, intelligence: 15, faith: 12, arcane: 11 } },
  { id: 'npc-display:23331', modelId: '23331', name: "Sorcerer Thops", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 11, intelligence: 15, faith: 12, arcane: 11 } },
  { id: 'npc-display:23340', modelId: '23340', name: "Nepheli Loux, Warrior", level: 18, stats: { vigor: 22, mind: 9, endurance: 14, strength: 19, dexterity: 15, intelligence: 6, faith: 6, arcane: 6 } },
  { id: 'npc-display:23341', modelId: '23341', name: "Nepheli Loux, Warrior", level: 18, stats: { vigor: 22, mind: 9, endurance: 14, strength: 19, dexterity: 15, intelligence: 6, faith: 6, arcane: 6 } },
  { id: 'npc-display:23342', modelId: '23342', name: "Nepheli Loux, Warrior", level: 63, stats: { vigor: 30, mind: 12, endurance: 19, strength: 43, dexterity: 20, intelligence: 7, faith: 8, arcane: 3 } },
  { id: 'npc-display:23350', modelId: '23350', name: "Reeling Rico", level: 25, stats: { vigor: 22, mind: 7, endurance: 11, strength: 12, dexterity: 20, intelligence: 2, faith: 26, arcane: 4 } },
  { id: 'npc-display:23360', modelId: '23360', name: "Vyke's Finger Maiden", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 5, faith: 8, arcane: 32 } },
  { id: 'npc-display:23380', modelId: '23380', name: "Finger Maiden (Bloody)", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 4, intelligence: 5, faith: 8, arcane: 32 } },
  { id: 'npc-display:23390', modelId: '23390', name: "Ensha of the Royal Remains", level: 16, stats: { vigor: 20, mind: 6, endurance: 5, strength: 8, dexterity: 22, intelligence: 10, faith: 8, arcane: 16 } },
  { id: 'npc-display:23400', modelId: '23400', name: "Bloody Finger Ravenmount", level: 60, stats: { vigor: 22, mind: 4, endurance: 26, strength: 6, dexterity: 27, intelligence: 4, faith: 4, arcane: 4 } },
  { id: 'npc-display:23420', modelId: '23420', name: "Human Boc", level: 25, stats: { vigor: 22, mind: 7, endurance: 11, strength: 12, dexterity: 20, intelligence: 2, faith: 26, arcane: 4 } },
  { id: 'npc-display:23430', modelId: '23430', name: "Bloody Finger Nerijus", level: 38, stats: { vigor: 22, mind: 9, endurance: 15, strength: 10, dexterity: 22, intelligence: 6, faith: 10, arcane: 3 } },
  { id: 'npc-display:23440', modelId: '23440', name: "Great Horned Tragoth", level: 88, stats: { vigor: 31, mind: 6, endurance: 17, strength: 20, dexterity: 8, intelligence: 6, faith: 8, arcane: 8 } },
  { id: 'npc-display:23441', modelId: '23441', name: "Great Horned Tragoth", level: 11, stats: { vigor: 22, mind: 11, endurance: 21, strength: 3, dexterity: 3, intelligence: 10, faith: 10, arcane: 10 } },
  { id: 'npc-display:23450', modelId: '23450', name: "Old Knight Istvan", level: 88, stats: { vigor: 22, mind: 9, endurance: 11, strength: 16, dexterity: 14, intelligence: 9, faith: 8, arcane: 8 } },
  { id: 'npc-display:23460', modelId: '23460', name: "Rileigh the Idle", level: 88, stats: { vigor: 22, mind: 9, endurance: 11, strength: 18, dexterity: 16, intelligence: 6, faith: 7, arcane: 8 } },
  { id: 'npc-display:23470', modelId: '23470', name: "Juno Hoslow, Knight of Blood", level: 110, stats: { vigor: 28, mind: 9, endurance: 15, strength: 10, dexterity: 24, intelligence: 6, faith: 6, arcane: 6 } },
  { id: 'npc-display:23480', modelId: '23480', name: "Millicent", level: 54, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23481', modelId: '23481', name: "Millicent (One-armed)", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23482', modelId: '23482', name: "Millicent (One-armed)", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23483', modelId: '23483', name: "Millicent (Prosthesis)", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23484', modelId: '23484', name: "Millicent (Prosthesis)", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23485', modelId: '23485', name: "Millicent", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23486', modelId: '23486', name: "Millicent (One-armed)", level: 24, stats: { vigor: 28, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23487', modelId: '23487', name: "Millicent (Prosthesis)", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 15, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23488', modelId: '23488', name: "Millicent (Prosthesis)", level: 162, stats: { vigor: 28, mind: 9, endurance: 11, strength: 16, dexterity: 27, intelligence: 5, faith: 4, arcane: 4 } },
  { id: 'npc-display:23490', modelId: '23490', name: "Sage Gowry", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 5, dexterity: 5, intelligence: 9, faith: 32, arcane: 4 } },
  { id: 'npc-display:23510', modelId: '23510', name: "Brother Corhyn", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 13, dexterity: 18, intelligence: 6, faith: 18, arcane: 0 } },
  { id: 'npc-display:23520', modelId: '23520', name: "Preceptor Miriam", level: 29, stats: { vigor: 31, mind: 9, endurance: 11, strength: 4, dexterity: 20, intelligence: 22, faith: 7, arcane: 4 } },
  { id: 'npc-display:23521', modelId: '23521', name: "Preceptor Miriam", level: 29, stats: { vigor: 31, mind: 9, endurance: 11, strength: 4, dexterity: 20, intelligence: 22, faith: 7, arcane: 4 } },
  { id: 'npc-display:23530', modelId: '23530', name: "Anastasia, Tarnished-Eater", level: 54, stats: { vigor: 22, mind: 9, endurance: 11, strength: 10, dexterity: 28, intelligence: 4, faith: 9, arcane: 4 } },
  { id: 'npc-display:23531', modelId: '23531', name: "Anastasia, Tarnished-Eater", level: 71, stats: { vigor: 22, mind: 5, endurance: 11, strength: 16, dexterity: 24, intelligence: 3, faith: 13, arcane: 3 } },
  { id: 'npc-display:23532', modelId: '23532', name: "Anastasia, Tarnished-Eater", level: 141, stats: { vigor: 22, mind: 9, endurance: 11, strength: 16, dexterity: 22, intelligence: 4, faith: 9, arcane: 4 } },
  { id: 'npc-display:23550', modelId: '23550', name: "Bloody Finger Okina", level: 110, stats: { vigor: 28, mind: 8, endurance: 17, strength: 14, dexterity: 14, intelligence: 6, faith: 14, arcane: 6 } },
  { id: 'npc-display:23551', modelId: '23551', name: "Bloody Finger Okina", level: 5, stats: { vigor: 28, mind: 9, endurance: 11, strength: 3, dexterity: 3, intelligence: 10, faith: 10, arcane: 10 } },
  { id: 'npc-display:23560', modelId: '23560', name: "Adan, Thief of Fire", level: 18, stats: { vigor: 22, mind: 7, endurance: 11, strength: 16, dexterity: 18, intelligence: 2, faith: 18, arcane: 3 } },
  { id: 'npc-display:23590', modelId: '23590', name: "Moongrum, Carian Knight", level: 25, stats: { vigor: 28, mind: 7, endurance: 11, strength: 12, dexterity: 20, intelligence: 18, faith: 4, arcane: 4 } },
  { id: 'npc-display:23600', modelId: '23600', name: "Vargram, the Raging Wolf", level: 29, stats: { vigor: 28, mind: 9, endurance: 11, strength: 19, dexterity: 16, intelligence: 8, faith: 8, arcane: 9 } },
  { id: 'npc-display:23610', modelId: '23610', name: "???", level: 24, stats: { vigor: 22, mind: 9, endurance: 11, strength: 23, dexterity: 18, intelligence: 10, faith: 5, arcane: 5 } },
  { id: 'npc-display:23611', modelId: '23611', name: "???", level: 93, stats: { vigor: 35, mind: 13, endurance: 15, strength: 45, dexterity: 44, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23612', modelId: '23612', name: "???", level: 149, stats: { vigor: 49, mind: 17, endurance: 20, strength: 61, dexterity: 61, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23613', modelId: '23613', name: "???", level: 180, stats: { vigor: 57, mind: 19, endurance: 23, strength: 70, dexterity: 70, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23614', modelId: '23614', name: "???", level: 201, stats: { vigor: 62, mind: 21, endurance: 25, strength: 76, dexterity: 76, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23615', modelId: '23615', name: "???", level: 230, stats: { vigor: 67, mind: 22, endurance: 27, strength: 81, dexterity: 82, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23616', modelId: '23616', name: "???", level: 230, stats: { vigor: 70, mind: 23, endurance: 27, strength: 84, dexterity: 85, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23617', modelId: '23617', name: "???", level: 240, stats: { vigor: 72, mind: 24, endurance: 28, strength: 87, dexterity: 88, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23618', modelId: '23618', name: "???", level: 244, stats: { vigor: 73, mind: 24, endurance: 29, strength: 88, dexterity: 89, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23630', modelId: '23630', name: "Finger Maiden Therolina", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 6, dexterity: 20, intelligence: 4, faith: 21, arcane: 4 } },
  { id: 'npc-display:23631', modelId: '23631', name: "Finger Maiden Therolina", level: 63, stats: { vigor: 5, mind: 77, endurance: 8, strength: 12, dexterity: 8, intelligence: 7, faith: 20, arcane: 5 } },
  { id: 'npc-display:23632', modelId: '23632', name: "Finger Maiden Therolina", level: 8, stats: { vigor: 28, mind: 9, endurance: 11, strength: 8, dexterity: 10, intelligence: 6, faith: 10, arcane: 5 } },
  { id: 'npc-display:23640', modelId: '23640', name: "Dolores the Sleeping Arrow", level: 63, stats: { vigor: 15, mind: 30, endurance: 25, strength: 18, dexterity: 30, intelligence: 9, faith: 8, arcane: 7 } },
  { id: 'npc-display:23650', modelId: '23650', name: "Jarwright", level: 63, stats: { vigor: 19, mind: 19, endurance: 19, strength: 19, dexterity: 19, intelligence: 19, faith: 19, arcane: 9 } },
  { id: 'npc-display:23670', modelId: '23670', name: "Inaba, Disciple of Okina", level: 18, stats: { vigor: 22, mind: 7, endurance: 10, strength: 9, dexterity: 21, intelligence: 4, faith: 4, arcane: 20 } },
  { id: 'npc-display:23680', modelId: '23680', name: "Silver Tear", level: 18, stats: { vigor: 17, mind: 2, endurance: 11, strength: 16, dexterity: 14, intelligence: 14, faith: 14, arcane: 9 } },
  { id: 'npc-display:23681', modelId: '23681', name: "Silver Tear", level: 18, stats: { vigor: 17, mind: 2, endurance: 11, strength: 27, dexterity: 9, intelligence: 12, faith: 10, arcane: 9 } },
  { id: 'npc-display:23682', modelId: '23682', name: "Silver Tear", level: 18, stats: { vigor: 17, mind: 2, endurance: 11, strength: 20, dexterity: 20, intelligence: 4, faith: 4, arcane: 19 } },
  { id: 'npc-display:23683', modelId: '23683', name: "Silver Tear", level: 18, stats: { vigor: 17, mind: 2, endurance: 16, strength: 30, dexterity: 16, intelligence: 6, faith: 6, arcane: 4 } },
  { id: 'npc-display:23690', modelId: '23690', name: "Recusant Henricus", level: 17, stats: { vigor: 22, mind: 8, endurance: 11, strength: 20, dexterity: 6, intelligence: 10, faith: 10, arcane: 10 } },
  { id: 'npc-display:23700', modelId: '23700', name: "???", level: 18, stats: { vigor: 22, mind: 9, endurance: 21, strength: 16, dexterity: 14, intelligence: 5, faith: 5, arcane: 5 } },
  { id: 'npc-display:23701', modelId: '23701', name: "???", level: 93, stats: { vigor: 35, mind: 13, endurance: 15, strength: 45, dexterity: 44, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23702', modelId: '23702', name: "???", level: 149, stats: { vigor: 49, mind: 17, endurance: 20, strength: 61, dexterity: 61, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23703', modelId: '23703', name: "???", level: 180, stats: { vigor: 57, mind: 19, endurance: 23, strength: 70, dexterity: 70, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23704', modelId: '23704', name: "???", level: 201, stats: { vigor: 62, mind: 21, endurance: 25, strength: 76, dexterity: 76, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23705', modelId: '23705', name: "???", level: 220, stats: { vigor: 67, mind: 22, endurance: 27, strength: 81, dexterity: 82, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23706', modelId: '23706', name: "???", level: 230, stats: { vigor: 70, mind: 23, endurance: 27, strength: 84, dexterity: 85, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23707', modelId: '23707', name: "???", level: 240, stats: { vigor: 72, mind: 24, endurance: 28, strength: 87, dexterity: 88, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23708', modelId: '23708', name: "???", level: 244, stats: { vigor: 73, mind: 24, endurance: 29, strength: 88, dexterity: 89, intelligence: 7, faith: 5, arcane: 8 } },
  { id: 'npc-display:23710', modelId: '23710', name: "???", level: 18, stats: { vigor: 22, mind: 5, endurance: 11, strength: 10, dexterity: 17, intelligence: 28, faith: 2, arcane: 2 } },
  { id: 'npc-display:23711', modelId: '23711', name: "???", level: 93, stats: { vigor: 26, mind: 26, endurance: 12, strength: 10, dexterity: 20, intelligence: 59, faith: 7, arcane: 12 } },
  { id: 'npc-display:23712', modelId: '23712', name: "???", level: 150, stats: { vigor: 49, mind: 38, endurance: 16, strength: 10, dexterity: 23, intelligence: 83, faith: 7, arcane: 12 } },
  { id: 'npc-display:23713', modelId: '23713', name: "???", level: 180, stats: { vigor: 47, mind: 44, endurance: 19, strength: 10, dexterity: 25, intelligence: 95, faith: 7, arcane: 12 } },
  { id: 'npc-display:23714', modelId: '23714', name: "???", level: 200, stats: { vigor: 57, mind: 48, endurance: 20, strength: 10, dexterity: 26, intelligence: 99, faith: 7, arcane: 12 } },
  { id: 'npc-display:23715', modelId: '23715', name: "???", level: 220, stats: { vigor: 70, mind: 52, endurance: 22, strength: 10, dexterity: 27, intelligence: 99, faith: 7, arcane: 12 } },
  { id: 'npc-display:23716', modelId: '23716', name: "???", level: 230, stats: { vigor: 77, mind: 54, endurance: 23, strength: 10, dexterity: 27, intelligence: 99, faith: 7, arcane: 12 } },
  { id: 'npc-display:23717', modelId: '23717', name: "???", level: 240, stats: { vigor: 83, mind: 57, endurance: 23, strength: 10, dexterity: 28, intelligence: 99, faith: 7, arcane: 12 } },
  { id: 'npc-display:23718', modelId: '23718', name: "???", level: 245, stats: { vigor: 86, mind: 58, endurance: 24, strength: 10, dexterity: 28, intelligence: 99, faith: 7, arcane: 12 } },
  { id: 'npc-display:23720', modelId: '23720', name: "Maleigh Marais, Shaded Castle Castellan", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 16, dexterity: 20, intelligence: 5, faith: 6, arcane: 8 } },
  { id: 'npc-display:23730', modelId: '23730', name: "Knight of the Great Jar", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 12, dexterity: 27, intelligence: 7, faith: 5, arcane: 4 } },
  { id: 'npc-display:23731', modelId: '23731', name: "Knight of the Great Jar", level: 131, stats: { vigor: 46, mind: 20, endurance: 15, strength: 31, dexterity: 73, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23732', modelId: '23732', name: "Knight of the Great Jar", level: 160, stats: { vigor: 53, mind: 22, endurance: 18, strength: 39, dexterity: 82, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23733', modelId: '23733', name: "Knight of the Great Jar", level: 180, stats: { vigor: 58, mind: 24, endurance: 19, strength: 45, dexterity: 88, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23734', modelId: '23734', name: "Knight of the Great Jar", level: 200, stats: { vigor: 63, mind: 25, endurance: 21, strength: 51, dexterity: 94, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23735', modelId: '23735', name: "Knight of the Great Jar", level: 220, stats: { vigor: 69, mind: 26, endurance: 23, strength: 57, dexterity: 99, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23736', modelId: '23736', name: "Knight of the Great Jar", level: 232, stats: { vigor: 71, mind: 27, endurance: 24, strength: 65, dexterity: 99, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23737', modelId: '23737', name: "Knight of the Great Jar", level: 240, stats: { vigor: 74, mind: 28, endurance: 25, strength: 68, dexterity: 99, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23738', modelId: '23738', name: "Knight of the Great Jar", level: 245, stats: { vigor: 75, mind: 28, endurance: 25, strength: 72, dexterity: 99, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23740', modelId: '23740', name: "Knight of the Great Jar", level: 26, stats: { vigor: 22, mind: 9, endurance: 11, strength: 28, dexterity: 12, intelligence: 4, faith: 16, arcane: 3 } },
  { id: 'npc-display:23741', modelId: '23741', name: "Knight of the Great Jar", level: 131, stats: { vigor: 46, mind: 20, endurance: 25, strength: 78, dexterity: 16, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23742', modelId: '23742', name: "Knight of the Great Jar", level: 160, stats: { vigor: 53, mind: 22, endurance: 28, strength: 86, dexterity: 25, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23743', modelId: '23743', name: "Knight of the Great Jar", level: 180, stats: { vigor: 58, mind: 24, endurance: 29, strength: 92, dexterity: 31, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23744', modelId: '23744', name: "Knight of the Great Jar", level: 200, stats: { vigor: 63, mind: 25, endurance: 31, strength: 98, dexterity: 37, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23745', modelId: '23745', name: "Knight of the Great Jar", level: 220, stats: { vigor: 73, mind: 26, endurance: 33, strength: 99, dexterity: 43, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23746', modelId: '23746', name: "Knight of the Great Jar", level: 230, stats: { vigor: 78, mind: 27, endurance: 34, strength: 99, dexterity: 46, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23747', modelId: '23747', name: "Knight of the Great Jar", level: 241, stats: { vigor: 84, mind: 28, endurance: 35, strength: 99, dexterity: 49, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23748', modelId: '23748', name: "Knight of the Great Jar", level: 245, stats: { vigor: 87, mind: 28, endurance: 35, strength: 99, dexterity: 50, intelligence: 7, faith: 10, arcane: 8 } },
  { id: 'npc-display:23750', modelId: '23750', name: "Knight of the Great Jar", level: 19, stats: { vigor: 22, mind: 9, endurance: 11, strength: 11, dexterity: 17, intelligence: 19, faith: 4, arcane: 5 } },
  { id: 'npc-display:23751', modelId: '23751', name: "Knight of the Great Jar", level: 130, stats: { vigor: 46, mind: 15, endurance: 25, strength: 27, dexterity: 27, intelligence: 47, faith: 10, arcane: 12 } },
  { id: 'npc-display:23752', modelId: '23752', name: "Knight of the Great Jar", level: 160, stats: { vigor: 53, mind: 22, endurance: 27, strength: 28, dexterity: 28, intelligence: 53, faith: 16, arcane: 12 } },
  { id: 'npc-display:23753', modelId: '23753', name: "Knight of the Great Jar", level: 180, stats: { vigor: 58, mind: 26, endurance: 29, strength: 28, dexterity: 28, intelligence: 58, faith: 20, arcane: 12 } },
  { id: 'npc-display:23754', modelId: '23754', name: "Knight of the Great Jar", level: 200, stats: { vigor: 63, mind: 30, endurance: 30, strength: 29, dexterity: 29, intelligence: 62, faith: 24, arcane: 12 } },
  { id: 'npc-display:23755', modelId: '23755', name: "Knight of the Great Jar", level: 210, stats: { vigor: 68, mind: 24, endurance: 32, strength: 29, dexterity: 29, intelligence: 67, faith: 28, arcane: 12 } },
  { id: 'npc-display:23756', modelId: '23756', name: "Knight of the Great Jar", level: 230, stats: { vigor: 70, mind: 37, endurance: 33, strength: 29, dexterity: 29, intelligence: 69, faith: 30, arcane: 12 } },
  { id: 'npc-display:23757', modelId: '23757', name: "Knight of the Great Jar", level: 240, stats: { vigor: 73, mind: 39, endurance: 33, strength: 30, dexterity: 30, intelligence: 70, faith: 32, arcane: 12 } },
  { id: 'npc-display:23758', modelId: '23758', name: "Knight of the Great Jar", level: 245, stats: { vigor: 74, mind: 40, endurance: 34, strength: 30, dexterity: 30, intelligence: 71, faith: 33, arcane: 12 } },
  { id: 'npc-display:23760', modelId: '23760', name: "Necromancer Garris", level: 32, stats: { vigor: 29, mind: 5, endurance: 11, strength: 14, dexterity: 18, intelligence: 16, faith: 16, arcane: 2 } },
  { id: 'npc-display:23770', modelId: '23770', name: "Nameless White Mask", level: 18, stats: { vigor: 22, mind: 9, endurance: 14, strength: 10, dexterity: 22, intelligence: 6, faith: 8, arcane: 6 } },
  { id: 'npc-display:23800', modelId: '23800', name: "Errant Sorcerer Wilhelm", level: 29, stats: { vigor: 28, mind: 9, endurance: 14, strength: 7, dexterity: 20, intelligence: 18, faith: 6, arcane: 6 } },
  { id: 'npc-display:23820', modelId: '23820', name: "Chief Guardian Arganthy", level: 33, stats: { vigor: 31, mind: 9, endurance: 11, strength: 5, dexterity: 20, intelligence: 4, faith: 28, arcane: 4 } },
  { id: 'npc-display:23830', modelId: '23830', name: "Flame Guardian", level: 3, stats: { vigor: 2, mind: 9, endurance: 11, strength: 20, dexterity: 15, intelligence: 5, faith: 16, arcane: 4 } },
  { id: 'npc-display:23840', modelId: '23840', name: "Inquisitor Ghiza", level: 88, stats: { vigor: 22, mind: 14, endurance: 11, strength: 13, dexterity: 13, intelligence: 8, faith: 8, arcane: 8 } },
  { id: 'npc-display:23850', modelId: '23850', name: "Mad Tongue Alberich", level: 42, stats: { vigor: 31, mind: 7, endurance: 11, strength: 14, dexterity: 14, intelligence: 15, faith: 15, arcane: 1 } },
  { id: 'npc-display:23860', modelId: '23860', name: "Esgar, Priest of Blood", level: 18, stats: { vigor: 22, mind: 8, endurance: 11, strength: 6, dexterity: 22, intelligence: 4, faith: 20, arcane: 4 } },
  { id: 'npc-display:23870', modelId: '23870', name: "Mary, Eldest Sister", level: 18, stats: { vigor: 22, mind: 11, endurance: 11, strength: 13, dexterity: 16, intelligence: 5, faith: 15, arcane: 4 } },
  { id: 'npc-display:23880', modelId: '23880', name: "Maureen, Second Sister", level: 18, stats: { vigor: 22, mind: 9, endurance: 17, strength: 16, dexterity: 14, intelligence: 6, faith: 5, arcane: 8 } },
  { id: 'npc-display:23890', modelId: '23890', name: "Amy, Third Sister", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 14, dexterity: 19, intelligence: 6, faith: 10, arcane: 6 } },
  { id: 'npc-display:23900', modelId: '23900', name: "Polyanna, Youngest Sister", level: 18, stats: { vigor: 22, mind: 9, endurance: 11, strength: 10, dexterity: 20, intelligence: 2, faith: 20, arcane: 3 } },
]

/** Cosmetic display lookup by (case-insensitive) name. Never for combat math. */
export function findNpcDisplay(name: string): NpcDisplayCard | undefined {
  const n = name.trim().toLowerCase()
  return npcDisplayCards.find((c) => c.name.toLowerCase() === n) ||
    npcDisplayCards.find((c) => c.name.toLowerCase().includes(n))
}
