import type { OpBuild } from './builds'

/**
 * PvP is a separate concern from the PvE `opBuilds` list: poise, stance and
 * invade-vs-host asymmetry matter more than raw damage, and PvP has its own
 * balance layer (patch 1.07+ scales skills/status separately against players).
 *
 * Task 116 §1–2. Every build now carries a full loadout (weapons with affinity
 * and ash of war, armour, four talismans, spells, consumables and buff order),
 * a playstyle, combos, and an honest beats/loses-to. Stat spreads are exact:
 * `statsTotal(stats) - 79 === level`, so every build is a legal character at its
 * bracketed level. Brackets are the four the task names — `RL30-50`, `RL60-90`,
 * `RL125`, `RL150` — with at least four builds each, plus SotE-era variants.
 *
 * Sources (patch 1.17, Aug 27 2026 — the Tarnished Pack regulation line this
 * project is stamped against):
 *  - https://eldenring.wiki.fextralife.com/PvP_Builds  (the four wiki-tagged PvP builds)
 *  - individual Fextralife build pages, listed per entry below
 *  - https://eldenring.wiki.fextralife.com/Community_Builds  (Heavy Turtle, Elden Wizard, Blood-Red Falling Star, Fingerprint Acolyte)
 *  - https://eldenring.wiki.fextralife.com/PvP   (PvP-exclusive scaling rules)
 *  - https://eldenring.wiki.fextralife.com/Patch+Notes  (1.17 PvP changes)
 * Entries that are community-standard archetypes rather than wiki-tagged builds
 * are marked `source` accordingly. Stat lines are target spreads, not extracted
 * numbers. See docs/research/op-builds-pvp-tricks-sources.md.
 */

export type PvpMode = 'invade' | 'duel' | 'both'

/** The four brackets Task 116 §1 groups PvP builds into. */
export type PvpBracket = 'RL30-50' | 'RL60-90' | 'RL125' | 'RL150'

/** The full loadout a build wants, as human-readable pieces (not fact ids). */
export type PvpLoadout = {
  /** Main-hand weapons, with affinity and upgrade where relevant. */
  weapons: string[]
  /** Off-hand weapons, shields or catalysts. */
  offhand: string[]
  /** Armour pieces, head to feet. */
  armor: string[]
  /** Exactly four talismans. */
  talismans: string[]
  /** Spells/memorised slots, or "None". */
  spells: string[]
  /** Consumables and flasks to carry. */
  consumables: string[]
}

export type PvpBuild = OpBuild & {
  mode: PvpMode
  /** Balance bracket the build is tuned for. */
  bracket: PvpBracket
  /** Router keywords for "what's good for pvp / sleep / poke" style asks. */
  keywords: string[]
  /** How the build is actually played moment to moment. */
  playstyle: string
  /** Bread-and-butter strings and punishes. */
  combos: string[]
  /** What this build punishes. */
  beats: string
  /** The honest weakness. */
  losesTo: string
  /** Full loadout, beyond the resolvable `kit` ids. */
  loadout: PvpLoadout
  /** Buff/consume order, first to last. */
  buffOrder: string[]
  /** Where the data came from. */
  source: string
}

export const pvpBuilds: PvpBuild[] = [
  {
    id: 'build:pvp-wretch',
    name: 'Poison/Bleed Wretch (RL30)',
    tag: 'pvp / invade / status',
    why: 'Low-level invasion build. Status buildup outpaces the tiny health pools hosts have at RL30, and the Reduvia bleed proc is lethal before anyone has Vigor.',
    level: 30,
    stats: { vigor: 26, mind: 9, endurance: 11, strength: 10, dexterity: 11, intelligence: 9, faith: 9, arcane: 24 },
    kit: [
      { id: 'reduvia', name: 'Reduvia', kind: 'armament', upgrade: 2 },
      { id: 'warhawk-talon', name: "Warhawk's Talon", kind: 'armament', affinity: 'Blood', upgrade: 2 },
      { id: 'cane-sword', name: 'Cane Sword', kind: 'armament', upgrade: 2 },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Winged Sword Insignia', kind: 'talisman' },
      { id: 'radagon-soreseal', name: "Radagon's Soreseal", kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
    ],
    need: ['loot:reduvia'],
    mode: 'invade',
    bracket: 'RL30-50',
    keywords: ['low level', 'low-level', 'twink', 'poison', 'bleed'],
    playstyle: 'Stay at range and stack bleed, then close only to finish. Never trade — the host has more HP than you can chew through in one combo.',
    combos: ['Reduvia L2 to force a roll, roll-catch with the off-hand Talon', 'Poison the host, then bleed-proc while they panic-roll the DoT'],
    beats: 'Low-Vigor hosts and players still learning roll timing.',
    losesTo: 'Over-levelled password-summon phantoms with poise and Vigor.',
    loadout: {
      weapons: ['Reduvia +2', "Warhawk's Talon +2 (Blood)", 'Cane Sword +2'],
      offhand: ['Buckler (parry option)'],
      armor: ['White Mask', 'Light bleed-friendly set for a fast roll'],
      talismans: ["Lord of Blood's Exultation", 'Winged Sword Insignia', "Radagon's Soreseal", 'Green Turtle Talisman'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Boiled Prawn', 'Kukri / throwing knives', 'Bone darts'],
    },
    buffOrder: ['Boiled Prawn', 'Reduvia bleed proc first', 'Winged Insignia ramp on the second hit'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/PvP_Builds',
  },
  {
    id: 'build:pvp-frenzy-low',
    name: 'Low-level Flame of Frenzy (RL40)',
    tag: 'pvp / invade / frenzy',
    why: 'At RL40 a single clean Flame of Frenzy channel takes most of a host\'s bar, and Madness buildup makes every hit worth far more than its listed damage.',
    level: 40,
    stats: { vigor: 30, mind: 15, endurance: 15, strength: 12, dexterity: 12, intelligence: 9, faith: 17, arcane: 9 },
    kit: [
      { id: 'finger-seal', name: 'Finger Seal', kind: 'catalyst', upgrade: 3 },
      { id: 'black-flame', name: 'Black Flame', kind: 'ash' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
      { id: 'okina', name: 'Okina Mask', kind: 'armor' },
    ],
    need: ['loot:finger-seal', 'loot:black-flame'],
    mode: 'invade',
    bracket: 'RL30-50',
    keywords: ['frenzy', 'madness', 'low level', 'faith', 'incant'],
    playstyle: 'Hold the Finger Seal, channel at a host locked into PvE, and only step in when the madness bar is filling. The build is a caster with a melee weapon it rarely needs.',
    combos: ['Flame of Frenzy into a roll-catch', 'Black Flame to chip through a shield', 'Burst the madness bar, then chase the panic-roll'],
    beats: 'Hosts and phantoms who try to face-tank a Madness channel to finish a combo.',
    losesTo: 'Anyone who breaks line of sight and closes during the long recovery.',
    loadout: {
      weapons: ['Finger Seal +3'],
      offhand: ['Short sword or Misericorde for a panic punish'],
      armor: ['Okina Mask', 'Light set to keep a fast roll'],
      talismans: ["Lord of Blood's Exultation", 'Ritual Sword Talisman', 'Green Turtle Talisman', 'Radagon Icon'],
      spells: ['The Flame of Frenzy', 'Frenzied Burst', 'Black Flame'],
      consumables: ['Crimson Tears', 'Cerulean Tears', 'Boiled Prawn'],
    },
    buffOrder: ['Boiled Prawn', 'Cast Frenzied Burst to open', 'Channel Flame of Frenzy once they commit'],
    patch: 'still-strong',
    source: 'Community-standard archetype (author-encoded); cf. Fextralife Frenzied Flame pages.',
  },
  {
    id: 'build:pvp-lightning-low',
    name: 'Low-level Lightning poke (RL45)',
    tag: 'pvp / invade / dex',
    why: 'Bolt of Gransax\'s Ancient Lightning Spear is a ranged nuke even at low upgrade, and a Dex poke weapon punishes the roll it forces without committing to the long animation.',
    level: 45,
    stats: { vigor: 24, mind: 11, endurance: 18, strength: 14, dexterity: 30, intelligence: 9, faith: 9, arcane: 9 },
    kit: [
      { id: 'gransax', name: 'Bolt of Gransax', kind: 'armament', upgrade: 3 },
      { id: 'estoc', name: 'Estoc', kind: 'armament', affinity: 'Keen', upgrade: 5 },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'radagon-soreseal', name: "Radagon's Soreseal", kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
    ],
    need: ['loot:bolt-gransax', 'loot:estoc'],
    mode: 'invade',
    bracket: 'RL30-50',
    keywords: ['lightning', 'poke', 'dex', 'low level', 'burst'],
    playstyle: 'Poke at the edge of Estoc range and punish every roll with the Gransax skill. Low Vigor means one clean trade is a losing trade.',
    combos: ['Estoc R1 into a Gransax skill as they roll out', 'Whiff an R1 to bait a roll, then Gransax the recovery'],
    beats: 'Hosts who respect the poke too much and never close distance.',
    losesTo: 'Poise monsters that walk through the poke and trade once.',
    loadout: {
      weapons: ['Bolt of Gransax +3', 'Estoc +5 (Keen)'],
      offhand: ['None or a Buckler for the parry read'],
      armor: ['Light set for a fast roll'],
      talismans: ['Godfrey Icon', 'Shard of Alexander', "Radagon's Soreseal", 'Green Turtle Talisman'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Lightningproof Dried Liver', 'Throwing pots'],
    },
    buffOrder: ['Lightningproof Dried Liver', 'Poke to force the roll', 'Gransax skill on the recovery'],
    patch: 'still-strong',
    source: 'Community-standard archetype (author-encoded); cf. Fextralife Bolt of Gransax page.',
  },
  {
    id: 'build:pvp-fingerprint-acolyte',
    name: 'Fingerprint Acolyte (RL50)',
    tag: 'pvp / both / tank',
    why: 'Themed after Vyke: block behind a greatshield and answer with a thrusting poke and Frenzied Flame incantations, so the build controls every range of the fight.',
    level: 50,
    stats: { vigor: 34, mind: 12, endurance: 20, strength: 20, dexterity: 14, intelligence: 9, faith: 12, arcane: 8 },
    kit: [
      { id: 'antspur', name: 'Antspur Rapier', kind: 'armament', affinity: 'Blood', upgrade: 5 },
      { id: 'finger-seal', name: 'Finger Seal', kind: 'catalyst', upgrade: 4 },
      { id: 'black-flame', name: 'Black Flame', kind: 'ash' },
      { id: 'greatshield-tal', name: 'Greatshield Talisman', kind: 'talisman' },
      { id: 'spear-tal', name: 'Spear Talisman', kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
      { id: 'ritual-shield', name: 'Ritual Shield Talisman', kind: 'talisman' },
    ],
    need: ['loot:antspur-rapier', 'loot:finger-seal', 'loot:black-flame'],
    mode: 'both',
    bracket: 'RL30-50',
    keywords: ['tank', 'shield', 'poke', 'frenzy', 'host'],
    playstyle: 'Hold the block and poke when they commit; if they back off, cast a frenzy spell into the space they are trying to reset.',
    combos: ['Block a running attack, guard-counter with the rapier', 'Antspur rot through the shield', 'Flame of Frenzy as they disengage'],
    beats: 'Aggressive invaders who think a greatshield is free pressure and run out of stamina first.',
    losesTo: 'Cragblade chip, guard-break tools and anything that punishes a static block.',
    loadout: {
      weapons: ['Antspur Rapier +5 (Blood)'],
      offhand: ['Fingerprint Stone Shield (or medium shield until then)', 'Finger Seal +4'],
      armor: ['As heavy as the endurance allows while still mid-rolling'],
      talismans: ['Greatshield Talisman', 'Spear Talisman', 'Green Turtle Talisman', 'Ritual Shield Talisman'],
      spells: ['The Flame of Frenzy', 'Frenzied Burst', 'Black Flame'],
      consumables: ['Crimson Tears', 'Cerulean Tears', 'Stimulating Boluses', 'Boiled Prawn'],
    },
    buffOrder: ['Boiled Prawn', 'Black Flame for percentage chip', 'Frenzied Burst only at range'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/Community_Builds (Fingerprint Acolyte, Level 50+).',
  },
  {
    id: 'build:pvp-trinitas',
    name: "St. Trina's Confessor (RL60)",
    tag: 'pvp / invade / sleep+frost',
    why: 'Powerstanced Swords of St Trina proc Sleep fast; in PvP Sleep does not open a crit but leaves a long stance-break window, then Ghostflame Ignition detonates the trade.',
    level: 60,
    stats: { vigor: 40, mind: 15, endurance: 20, strength: 17, dexterity: 18, intelligence: 14, faith: 8, arcane: 7 },
    kit: [
      { id: 'st-trina-l', name: 'Sword of St Trina', kind: 'armament', upgrade: 3 },
      { id: 'st-trina-r', name: 'Sword of St Trina', kind: 'armament', upgrade: 3 },
      { id: 'deaths-poker', name: "Death's Poker", kind: 'armament', upgrade: 3 },
      { id: 'pulley-xbow', name: 'Pulley Crossbow', kind: 'armament', upgrade: 3 },
      { id: 'radagon-soreseal', name: "Radagon's Soreseal", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
    ],
    need: ['loot:sword-st-trina', 'loot:deaths-poker'],
    mode: 'invade',
    bracket: 'RL60-90',
    keywords: ['sleep', 'trina', 'frost', 'confessor'],
    playstyle: 'Poke with crossbow fire to build Sleep, then swap to the powerstanced swords when the bar is near. Ghostflame Ignition is the pay-off, not the opener.',
    combos: ['Pulley Crossbow burst into powerstanced L1', 'Sleep proc into Ghostflame Ignition', 'Freeze then a full L1 chain'],
    beats: 'Passive players who eat the L1 chain and give up the stance-break window.',
    losesTo: 'Anyone who rolls out of Sleep and punishes the Ghostflame recovery.',
    loadout: {
      weapons: ['Sword of St Trina +3 (right)', 'Sword of St Trina +3 (left)', "Death's Poker +3"],
      offhand: ['Pulley Crossbow +3'],
      armor: ['Light set for a fast roll, sleep-resist where possible'],
      talismans: ["Radagon's Soreseal", 'Rotten Winged Sword Insignia', 'Ritual Sword Talisman', 'Green Turtle Talisman'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Sleeping Pots (mirror the archetype)', 'Boluses for frost'],
    },
    buffOrder: ['Boluses for frost', 'Crossbow burst to build Sleep', 'Ghostflame Ignition on the proc'],
    patch: 'still-strong',
    source: "https://eldenring.wiki.fextralife.com/Level_60_St._Trina%27s_Confessor_Build",
  },
  {
    id: 'build:pvp-lightning-assassin',
    name: 'Sanguine Lightning Assassin (RL70)',
    tag: 'pvp / invade / burst',
    why: 'Concealing Veil keeps you invisible at range, Bolt of Gransax and Dragon King\'s Cragblade deliver the one-shot, Bloodhound\'s Step is the escape. Built to delete the host before the gank reacts.',
    level: 70,
    stats: { vigor: 38, mind: 12, endurance: 18, strength: 20, dexterity: 38, intelligence: 9, faith: 7, arcane: 7 },
    kit: [
      { id: 'gransax', name: 'Bolt of Gransax', kind: 'armament', upgrade: 8 },
      { id: 'cragblade', name: "Dragon King's Cragblade", kind: 'armament', upgrade: 8 },
      { id: 'okina', name: 'Okina Mask', kind: 'armor' },
      { id: 'concealing-veil', name: 'Concealing Veil', kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
    ],
    need: ['loot:bolt-gransax', 'loot:concealing-veil', 'loot:dragon-king-cragblade'],
    mode: 'invade',
    bracket: 'RL60-90',
    keywords: ['assassin', 'stealth', 'burst', 'gransax', 'lightning'],
    playstyle: 'Open from concealment with a full-charge skill; if it fails, Bloodhound Step out and reset instead of brawling the gank.',
    combos: ['Charged Ancient Lightning Spear from cover', 'Cragblade running R2 into the follow-up', 'Step out of a whiffed combo and re-open'],
    beats: 'Hosts who walk open ground and never check behind them.',
    losesTo: 'Sustained 2v1 pressure once the ambush fails and the co-op players group up.',
    loadout: {
      weapons: ['Bolt of Gransax +8', "Dragon King's Cragblade +8"],
      offhand: ['Dagger with Bloodhound\'s Step'],
      armor: ['Okina Mask', 'Light set for a fast roll'],
      talismans: ['Concealing Veil', 'Shard of Alexander', 'Godfrey Icon', 'Radagon Icon'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Lightningproof Dried Liver', 'Boiled Prawn'],
    },
    buffOrder: ['Lightningproof Dried Liver', 'Boiled Prawn', 'Charged skill from concealment'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/Level_75_Sanguine_Lightning_Assassin_Build',
  },
  {
    id: 'build:pvp-parry',
    name: 'Buckler parry punish (RL80)',
    tag: 'pvp / both / parry',
    why: 'A Buckler parry into a dagger riposte is the cheapest way a mid-level host turns an invader\'s first greedy swing into a full health bar.',
    level: 80,
    stats: { vigor: 45, mind: 10, endurance: 18, strength: 16, dexterity: 40, intelligence: 9, faith: 9, arcane: 12 },
    kit: [
      { id: 'buckler', name: 'Buckler', kind: 'shield', upgrade: 5 },
      { id: 'parrying-dagger', name: 'Parrying Dagger', kind: 'armament', upgrade: 5 },
      { id: 'dagger', name: 'Dagger', kind: 'armament', affinity: 'Keen', upgrade: 8 },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
      { id: 'claw-tal', name: 'Claw Talisman', kind: 'talisman' },
      { id: 'axe-tal', name: 'Axe Talisman', kind: 'talisman' },
    ],
    need: ['loot:buckler', 'loot:parrying-dagger', 'loot:ritual-sword'],
    mode: 'both',
    bracket: 'RL60-90',
    keywords: ['parry', 'buckler', 'riposte', 'daggers'],
    playstyle: 'Stand just inside their swing range, bait one predictable attack and parry it. Everything else is footwork and not over-committing.',
    combos: ['Buckler parry into a Misericorde riposte', 'Whiff an R1 to bait their running attack', 'Roll-catch the panic roll with the dagger'],
    beats: 'Players who throw out predictable running attacks and rolling R1s.',
    losesTo: 'Lag, jumping attacks and anything that cannot be parried.',
    loadout: {
      weapons: ['Parrying Dagger +5', 'Dagger +8 (Keen)'],
      offhand: ['Buckler +5'],
      armor: ['Light-to-mid set that keeps a fast roll'],
      talismans: ['Ritual Sword Talisman', 'Green Turtle Talisman', 'Claw Talisman', 'Axe Talisman'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Boiled Prawn', 'Throwing knives'],
    },
    buffOrder: ['Boiled Prawn', 'Bait one predictable swing', 'Riposte, then reset spacing'],
    patch: 'still-strong',
    source: 'Community-standard archetype (author-encoded); cf. Fextralife PvP.',
  },
  {
    id: 'build:pvp-sorcerer-duelist',
    name: 'Sorcerer Duelist (RL90)',
    tag: 'pvp / duel / caster',
    why: 'Azur\'s Staff plus Radagon Icon reaches the cast-speed cap, Carian Slicer staggers anyone under ~30 poise, and two Magic Glintblades into Collapsing Stars is close to a guaranteed one-shot.',
    level: 90,
    stats: { vigor: 38, mind: 24, endurance: 14, strength: 12, dexterity: 16, intelligence: 50, faith: 7, arcane: 8 },
    kit: [
      { id: 'azur-staff', name: "Azur's Glintstone Staff", kind: 'catalyst', upgrade: 25 },
      { id: 'carian-slicer', name: 'Carian Slicer', kind: 'ash' },
      { id: 'swift-shard', name: 'Swift Glintstone Shard', kind: 'ash' },
      { id: 'graven-mass', name: 'Graven-Mass Talisman', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
      { id: 'stargazer', name: 'Stargazer Heirloom', kind: 'talisman' },
      { id: 'great-jar', name: "Great-Jar's Arsenal", kind: 'talisman' },
    ],
    need: ['loot:carian-slicer', 'boss:rennala', 'loot:radagon-icon'],
    mode: 'duel',
    bracket: 'RL60-90',
    keywords: ['mage', 'sorcerer', 'spell', 'duel', 'caster', 'int'],
    playstyle: 'Control the spacing: Slicer when they step in, Glintblades when they reset, and never stand still long enough to eat a punish.',
    combos: ['Magic Glintblade x2 into Collapsing Stars', 'Carian Slicer to stagger anyone under 30 poise', 'Cast-speed Swift Shard to roll-catch'],
    beats: 'Low-poise melee players who try to wade through Slicer and Glintblades.',
    losesTo: 'Eternal Darkness users and anyone who closes distance during cast recovery.',
    loadout: {
      weapons: ["Azur's Glintstone Staff +25"],
      offhand: ['Carian Regal Scepter or a second staff for the passive boost'],
      armor: ['Light set for a fast roll'],
      talismans: ['Graven-Mass Talisman', 'Radagon Icon', 'Stargazer Heirloom', "Great-Jar's Arsenal"],
      spells: ['Carian Slicer', 'Swift Glintstone Shard', 'Magic Glintblade', 'Collapsing Stars'],
      consumables: ['Cerulean Tears', 'Starlight Shards', 'Boiled Prawn'],
    },
    buffOrder: ['Starlight Shards', 'Open with Glintblades', 'Slicer the moment they commit'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/Level_80-90_Sorcerer_Duelist_Build',
  },
  {
    id: 'build:pvp-heavy-turtle',
    name: 'Heavy Turtle (RL125)',
    tag: 'pvp / both / strength',
    why: 'A Heavy Greatsword with Bloodhound\'s Step and max stamina regeneration: whiff-punish with enormous damage, and step out of anything you cannot tank.',
    level: 125,
    stats: { vigor: 56, mind: 9, endurance: 27, strength: 74, dexterity: 12, intelligence: 7, faith: 8, arcane: 11 },
    kit: [
      { id: 'greatsword', name: 'Greatsword', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'bhs', name: "Ash of War: Bloodhound's Step", kind: 'ash' },
      { id: 'bullgoat-armor', name: 'Bull-Goat Armor', kind: 'armor' },
      { id: 'great-jar', name: "Great-Jar's Arsenal", kind: 'talisman' },
      { id: 'bullgoat', name: "Bull-Goat's Talisman", kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
      { id: 'dragoncrest-gc', name: 'Dragoncrest Greatshield Talisman', kind: 'talisman' },
    ],
    need: ['loot:greatsword', 'loot:bloodhound-step', 'loot:great-jar', 'loot:bullgoat'],
    mode: 'both',
    bracket: 'RL125',
    keywords: ['turtle', 'strength', 'greatsword', 'poise', 'dogfighter'],
    playstyle: 'Pool stamina, never swing first into open air. Step to dodge, then punish the recovery with one heavy swing and back to neutral.',
    combos: ['Bloodhound Step out of a combo, R1 on the recovery', 'Jumping R2 as a roll-catch', 'Poise-tank one hit to land the trade'],
    beats: 'Fast weapons that expect to out-trade a colossal and cannot.',
    losesTo: 'Patient thrusting pokes and anything that forces a long roll.',
    loadout: {
      weapons: ['Greatsword +25 (Heavy, Bloodhound\'s Step)'],
      offhand: ['Great Turtle Shell or a medium shield for the odd block'],
      armor: ['Bull-Goat Armor and helm', 'Fire Prelate Greaves', 'as heavy as the roll allows'],
      talismans: ["Great-Jar's Arsenal", "Bull-Goat's Talisman", 'Green Turtle Talisman', 'Dragoncrest Greatshield Talisman'],
      spells: ['None'],
      consumables: ['Greenburst Crystal Tear + Stonebarb Cracked Tear', 'Cerulean Tears', 'Crimson Tears', 'Boiled Crab', 'Fan Daggers'],
    },
    buffOrder: ['Wondrous Physick (Greenburst + Stonebarb)', 'Boiled Crab', 'Step in and punish the first whiff'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/Community_Builds (Heavy Turtle, Level 125).',
  },
  {
    id: 'build:pvp-bleed-katana',
    name: 'Bleed katana duelist (RL125)',
    tag: 'pvp / both / bleed',
    why: 'Corpse Piler and powerstanced Blood katanas still punish passive play: bleed pressure forces a reaction, and Lord of Blood\'s Exultation turns the proc into a damage window. Corpse Piler has been nerfed repeatedly since launch, so this archetype depends on a nerfed patch and is flagged as such.',
    level: 125,
    stats: { vigor: 60, mind: 16, endurance: 25, strength: 12, dexterity: 40, intelligence: 9, faith: 9, arcane: 33 },
    kit: [
      { id: 'rob', name: 'Rivers of Blood', kind: 'armament', upgrade: 10 },
      { id: 'nagakiba', name: 'Nagakiba', kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
      { id: 'millicent', name: "Millicent's Prosthesis", kind: 'talisman' },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
    ],
    need: ['loot:rivers', 'loot:lord-blood-exul', 'item:millicent-prosthesis'],
    mode: 'both',
    bracket: 'RL125',
    keywords: ['bleed', 'rivers', 'rob', 'corpse piler', 'katana'],
    playstyle: 'Pressure with Corpse Piler, but learn to stop on the third hit: the follow-up is where passive players die, and where you get parried if you are greedy.',
    combos: ['Corpse Piler L2 x3, roll out before the recovery', 'Powerstanced L1 chain into Lord of Blood proc', 'Running R2 to roll-catch'],
    beats: 'Players who back off instead of rolling through the third Corpse Piler hit.',
    losesTo: 'Bleed-resistant armour, shields, and roll-catch spacing that punishes the L2 recovery.',
    loadout: {
      weapons: ['Rivers of Blood +10', 'Nagakiba +25 (Blood)'],
      offhand: ['Second katana or a shield for the bleed-resistant matchup'],
      armor: ['White Mask', 'Light bleed-friendly set for a fast roll'],
      talismans: ["Lord of Blood's Exultation", 'Rotten Winged Sword Insignia', "Millicent's Prosthesis", 'Ritual Sword Talisman'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Boiled Prawn', 'Throwing pots to force movement'],
    },
    buffOrder: ['Boiled Prawn', 'Open with a running R1', 'Corpse Piler only once they are in a corner'],
    patch: 'nerfed-but-works',
    source: 'Community-standard archetype (author-encoded); cf. Sanguine Samurai build, Fextralife.',
  },
  {
    id: 'build:pvp-faith-poke',
    name: 'Faith poke (RL125)',
    tag: 'pvp / both / faith',
    why: 'A Coded Sword and Blade of Calling poke behind a shield, with the Erdtree Seal buffing holy damage, punishes passivity without ever committing to a long animation.',
    level: 125,
    stats: { vigor: 55, mind: 22, endurance: 25, strength: 14, dexterity: 18, intelligence: 9, faith: 52, arcane: 9 },
    kit: [
      { id: 'coded-sword', name: 'Coded Sword', kind: 'armament', upgrade: 10 },
      { id: 'blade-calling', name: 'Blade of Calling', kind: 'armament', upgrade: 10 },
      { id: 'erdtree-seal', name: 'Erdtree Seal', kind: 'catalyst', upgrade: 10 },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
      { id: 'spear-tal', name: 'Spear Talisman', kind: 'talisman' },
      { id: 'ritual-shield', name: 'Ritual Shield Talisman', kind: 'talisman' },
    ],
    need: ['loot:coded-sword', 'item:blade-of-calling', 'loot:erdtree-seal', 'loot:ritual-sword'],
    mode: 'both',
    bracket: 'RL125',
    keywords: ['faith', 'poke', 'holy', 'shield'],
    playstyle: 'Hold the block, punish every poke with a faster one, and only cast when they have committed to a long recovery.',
    combos: ['Guard-poke with the Coded Sword', 'Blade of Calling to roll-catch', 'Ritual Sword window after a safe trade'],
    beats: 'Shield turtles and players who expect a slow incantation.',
    losesTo: 'Anyone who parries the poke or punishes the buff window.',
    loadout: {
      weapons: ['Coded Sword +10', 'Blade of Calling +10'],
      offhand: ['Erdtree Seal +10', 'a medium shield for the poke'],
      armor: ['Mid set that keeps stamina regen high'],
      talismans: ['Ritual Sword Talisman', 'Green Turtle Talisman', 'Spear Talisman', 'Ritual Shield Talisman'],
      spells: ['Golden Vow', 'Black Flame', 'Rotten Breath solution for rot mirrors'],
      consumables: ['Crimson Tears', 'Cerulean Tears', 'Stimulating Boluses', 'Boiled Prawn'],
    },
    buffOrder: ['Golden Vow', 'Boiled Prawn', 'Poke from behind block'],
    patch: 'still-strong',
    source: 'Community-standard archetype (author-encoded); cf. Fextralife PvP.',
  },
  {
    id: 'build:pvp-frost',
    name: 'Zamor frost duelist (RL125)',
    tag: 'pvp / duel / frost',
    why: 'Frostbite cuts stamina regen and amplifies the next hit, so a Zamor curved sword\'s fast chains win the duel before the proc even lands twice.',
    level: 125,
    stats: { vigor: 55, mind: 19, endurance: 25, strength: 16, dexterity: 34, intelligence: 38, faith: 8, arcane: 9 },
    kit: [
      { id: 'zamor', name: 'Zamor Curved Sword', kind: 'armament', upgrade: 10 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'graven-mass', name: 'Graven-Mass Talisman', kind: 'talisman' },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
    ],
    need: ['loot:zamor-curved-sword', 'loot:magic-scorpion', 'loot:graven-mass', 'loot:ritual-sword'],
    mode: 'duel',
    bracket: 'RL125',
    keywords: ['frost', 'duel', 'curved sword', 'int'],
    playstyle: 'Hit the frostbite proc, then back off just long enough for them to clear it and re-engage on a stamina deficit.',
    combos: ['Fast curved-sword R1 chains to force the proc', 'Roll-catch on the frostbite stamina drop', 'Glintstone shard to punish a disengage'],
    beats: 'Trading opponents who eat a second chain to clear the frostbite proc.',
    losesTo: 'Frost-resistant builds and anyone who out-ranges the curved sword.',
    loadout: {
      weapons: ['Zamor Curved Sword +10', 'Carian Glintstone Staff off-hand'],
      offhand: ['Carian Glintstone Staff for shard pressure'],
      armor: ['Light set for a fast roll'],
      talismans: ['Magic Scorpion Charm', 'Graven-Mass Talisman', 'Ritual Sword Talisman', 'Radagon Icon'],
      spells: ['Glintstone Icecrag', 'Zamor Ice Storm', 'Adula\'s Moonblade'],
      consumables: ['Cerulean Tears', 'Crimson Tears', 'Boluses for their frost'],
    },
    buffOrder: ['Open with a fast chain', 'Cast to punish the disengage', 'Re-chain on the frostbite proc'],
    patch: 'still-strong',
    source: 'Community-standard archetype (author-encoded); cf. Fextralife PvP.',
  },
  {
    id: 'build:pvp-elden-wizard',
    name: 'Elden Wizard (RL150)',
    tag: 'pvp / both / int+faith',
    why: 'A pure caster that switches between Prince of Death sorcery and Golden Order incantations, so the duel is fought at whichever range the opponent is worst at.',
    level: 150,
    stats: { vigor: 30, mind: 30, endurance: 20, strength: 11, dexterity: 20, intelligence: 60, faith: 40, arcane: 18 },
    kit: [
      { id: 'lusat', name: "Lusat's Glintstone Staff", kind: 'catalyst', upgrade: 25 },
      { id: 'carian', name: 'Carian Regal Scepter', kind: 'catalyst', upgrade: 10 },
      { id: 'azur', name: 'Comet Azur', kind: 'ash' },
      { id: 'nc', name: 'Night Comet', kind: 'ash' },
      { id: 'graven-mass', name: 'Graven-Mass Talisman', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
      { id: 'godfrey-icon', name: 'Godfrey Icon', kind: 'talisman' },
      { id: 'stargazer', name: 'Stargazer Heirloom', kind: 'talisman' },
    ],
    need: ['loot:lusats-staff', 'loot:comet-azur', 'loot:night-comet', 'loot:radagon-icon'],
    mode: 'both',
    bracket: 'RL150',
    keywords: ['caster', 'wizard', 'int', 'faith', 'glass'],
    playstyle: 'Stay at max range, use the faster spell for the matchup and punish every cast recovery. Low Vigor means the first clean trade ends the round.',
    combos: ['Night Comet to open through a lock-on', 'Comet Azur when they stand still', 'Incantation swap to punish a magic-resistant target'],
    beats: 'Players who let a caster get to full range and never pressure the recovery.',
    losesTo: 'Eternal Darkness, gap-closers and anyone who trades once.',
    loadout: {
      weapons: ["Lusat's Glintstone Staff +25", 'Carian Regal Scepter +10'],
      offhand: ["Prince of Death's Staff", 'Golden Order Seal for the faith half'],
      armor: ['Commoner\'s Headband (Altered)', 'Lazuli Robe', 'Zamor Bracelets', 'Zamor Legwraps — light load only'],
      talismans: ['Graven-Mass Talisman', 'Radagon Icon', 'Godfrey Icon', 'Stargazer Heirloom'],
      spells: ['Comet Azur', 'Night Comet', 'Glintstone Icecrag', 'Golden Order incantations', 'Magic Glintblade'],
      consumables: ['Cerulean Tears x many', 'Starlight Shards', 'Crimson Tears'],
    },
    buffOrder: ['Terra Magica on a set-up', 'Starlight Shards', 'Open with the fast spell, not the beam'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/Community_Builds (Elden Wizard build, Level 150-400).',
  },
  {
    id: 'build:pvp-frost-knight',
    name: 'Magic Frost Knight (RL150)',
    tag: 'pvp / both / int+quality',
    why: 'A Dark Moon Greatsword beam at range and a charged frost trade in melee, backed by the Carian Regal Scepter — one build that is dangerous at every distance.',
    level: 150,
    stats: { vigor: 40, mind: 40, endurance: 25, strength: 20, dexterity: 29, intelligence: 60, faith: 6, arcane: 9 },
    kit: [
      { id: 'dmgs', name: 'Dark Moon Greatsword', kind: 'armament', upgrade: 10 },
      { id: 'carian', name: 'Carian Regal Scepter', kind: 'catalyst', upgrade: 10 },
      { id: 'magic-scorp', name: 'Magic Scorpion Charm', kind: 'talisman' },
      { id: 'graven-mass', name: 'Graven-Mass Talisman', kind: 'talisman' },
      { id: 'radagon-icon', name: 'Radagon Icon', kind: 'talisman' },
      { id: 'dragoncrest-gc', name: 'Dragoncrest Greatshield Talisman', kind: 'talisman' },
    ],
    need: ['loot:dark-moon', 'loot:carian-regal-scepter', 'loot:magic-scorpion'],
    mode: 'both',
    bracket: 'RL150',
    keywords: ['frost', 'int', 'dark moon', 'quality', 'knight'],
    playstyle: 'Open with a beam or Comet, then buff the sword and take the melee when they are low. Never open with the slow charged heavy into a fast weapon.',
    combos: ['Moonlight beam into a roll-catch', 'Adula\'s Moonblade at melee range', 'Charged R2 as a punish after a whiff'],
    beats: 'Players who respect the beam too much and give up all the space.',
    losesTo: 'Fast pressure that never lets the beam charge, and magic negation.',
    loadout: {
      weapons: ['Dark Moon Greatsword +10'],
      offhand: ['Carian Regal Scepter +10'],
      armor: ['Crucible Tree set or Night\'s Cavalry set for the mid roll'],
      talismans: ['Magic Scorpion Charm', 'Graven-Mass Talisman', 'Radagon Icon', 'Dragoncrest Greatshield Talisman'],
      spells: ['Adula\'s Moonblade', 'Comet', 'Comet Azur', 'Loretta\'s Greatbow', 'Zamor Ice Storm'],
      consumables: ['Cerulean Tears', 'Crimson Tears', 'Boiled Prawn'],
    },
    buffOrder: ['Moonlight Greatsword skill', 'Boiled Prawn', 'Beam at range, sword in melee'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/Community_Builds (Magic Frost Knight, Level 150).',
  },
  {
    id: 'build:pvp-colossal',
    name: 'Colossal poise monster (RL150)',
    tag: 'pvp / both / poise',
    why: 'Max poise plus hyper-armour trades win the neutral game: Lion\'s Claw cannot be parried, and the opponent eats the follow-up if they try to interrupt.',
    level: 150,
    stats: { vigor: 60, mind: 12, endurance: 41, strength: 80, dexterity: 14, intelligence: 7, faith: 8, arcane: 7 },
    kit: [
      { id: 'crusher', name: 'Giant-Crusher', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'greatsword', name: 'Greatsword', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'lions-claw', name: 'Lion\'s Claw', kind: 'ash' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'great-jar', name: "Great-Jar's Arsenal", kind: 'talisman' },
      { id: 'bullgoat', name: "Bull-Goat's Talisman", kind: 'talisman' },
      { id: 'claw-tal', name: 'Claw Talisman', kind: 'talisman' },
    ],
    need: ['loot:giant-crusher', 'loot:lions-claw', 'loot:bullgoat'],
    mode: 'both',
    bracket: 'RL150',
    keywords: ['colossal', 'poise', 'strength', 'bonk', 'hyper armor', 'hyperarmour'],
    playstyle: 'Walk forward, take one hit on the armour, and let Lion\'s Claw finish the exchange. The build loses to patience, not to damage.',
    combos: ['Lion\'s Claw trade', 'Jumping R2 roll-catch', 'Charged R2 into the wake-up'],
    beats: 'Fast weapons that try to trade into hyper armour.',
    losesTo: 'Thrusting-sword poke, Giant Hunt (parryable) and patient whiff-punishing.',
    loadout: {
      weapons: ['Giant-Crusher +25 (Heavy, Lion\'s Claw)', 'Greatsword +25 (Heavy)'],
      offhand: ['Dagger with Bloodhound\'s Step for the escape'],
      armor: ['Bull-Goat set (or as heavy as the roll allows)'],
      talismans: ['Shard of Alexander', "Great-Jar's Arsenal", "Bull-Goat's Talisman", 'Claw Talisman'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Boiled Crab', 'Ironjar Aromatic', 'Fan Daggers'],
    },
    buffOrder: ['Ironjar Aromatic', 'Boiled Crab', 'Lion\'s Claw into a trade'],
    patch: 'still-strong',
    source: 'Community-standard archetype (author-encoded); cf. Colossal Crusher build, Fextralife.',
  },
  {
    id: 'build:pvp-falling-star',
    name: 'Blood-Red Falling Star (RL150)',
    tag: 'pvp / both / strength+bleed',
    why: 'Great Stars heals on hit and builds blood loss, so a pure Strength spread that trades constantly wins the attrition fight and re-heals through every exchange.',
    level: 150,
    stats: { vigor: 45, mind: 14, endurance: 41, strength: 80, dexterity: 14, intelligence: 7, faith: 18, arcane: 10 },
    kit: [
      { id: 'great-stars', name: 'Great Stars', kind: 'armament', affinity: 'Heavy', upgrade: 25 },
      { id: 'crag', name: 'Cragblade', kind: 'ash' },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
      { id: 'great-jar', name: "Great-Jar's Arsenal", kind: 'talisman' },
      { id: 'ritual-sword', name: 'Ritual Sword Talisman', kind: 'talisman' },
    ],
    need: ['loot:great-stars', 'loot:cragblade', 'loot:lord-blood-exul', 'loot:great-jar'],
    mode: 'both',
    bracket: 'RL150',
    keywords: ['strength', 'bleed', 'great stars', 'lifesteal', 'pressure'],
    playstyle: 'Apply Cragblade and trade every exchange; the heal-on-hit and the bleed proc mean losing trades still move the bar in your favour.',
    combos: ['Cragblade-buffed R1 trade', 'Charged R2 stamina pressure', 'Jump attack on the guard'],
    beats: 'Shield pokes and anyone who cannot out-burst the sustain.',
    losesTo: 'Burst casters who never let you close, and parries on the slow swing.',
    loadout: {
      weapons: ['Great Stars +25 (Heavy, Cragblade)'],
      offhand: ['Sacrificial Axe for the FP-on-kill or a seal for buffs'],
      armor: ['White Mask', 'Bull-Goat set for poise while still mid-rolling'],
      talismans: ["Lord of Blood's Exultation", 'Rotten Winged Sword Insignia', "Great-Jar's Arsenal", 'Ritual Sword Talisman'],
      spells: ['Flame, Grant Me Strength', 'Bloodflame Blade', 'Bestial Vitality', 'Golden Vow'],
      consumables: ['Crimson Tears', 'Boiled Prawn', 'Starlight Shards'],
    },
    buffOrder: ['Golden Vow', 'Flame, Grant Me Strength', 'Cragblade', 'Trade immediately'],
    patch: 'still-strong',
    source: 'https://eldenring.wiki.fextralife.com/Community_Builds (Blood-Red Falling Star, Level 150).',
  },
  {
    id: 'build:pvp-meteoric-sote',
    name: 'Meteoric Ore arcane (RL150, SotE)',
    tag: 'pvp / both / strength+arcane',
    why: 'The Ancient Meteoric Ore Greatsword scales off Arcane as well as Strength, so a bleed-heavy talisman set lifts a colossal that normally ignores status.',
    level: 150,
    stats: { vigor: 55, mind: 15, endurance: 30, strength: 60, dexterity: 12, intelligence: 9, faith: 8, arcane: 40 },
    kit: [
      { id: 'meteoric-ore', name: 'Ancient Meteoric Ore Greatsword', kind: 'armament', upgrade: 10 },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'alex', name: 'Shard of Alexander', kind: 'talisman' },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
      { id: 'great-jar', name: "Great-Jar's Arsenal", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
    ],
    need: ['loot:ancient-meteoric-ore-gs', 'loot:lord-blood-exul', 'loot:shard-alexander', 'loot:white-mask'],
    mode: 'both',
    bracket: 'RL150',
    keywords: ['arcane', 'strength', 'sote', 'bleed', 'colossal'],
    playstyle: 'Play it like a strength colossal but expect the blood proc to matter in long fights; the skill trades well and the arcane scaling keeps the damage honest.',
    combos: ['Skill into an L1 trade', 'Jumping R2 roll-catch', 'Bleed proc into a punish'],
    beats: 'Poise stackers who think a greatsword cannot build status.',
    losesTo: 'Fast poke and bleed-resistant shields.',
    loadout: {
      weapons: ['Ancient Meteoric Ore Greatsword +10'],
      offhand: ['Dagger with Bloodhound\'s Step'],
      armor: ['White Mask', 'heavy set for the mid roll'],
      talismans: ["Lord of Blood's Exultation", 'Shard of Alexander', "Great-Jar's Arsenal", 'Rotten Winged Sword Insignia'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Boiled Prawn', 'Exalted Flesh'],
    },
    buffOrder: ['Exalted Flesh', 'Boiled Prawn', 'Skill into a trade'],
    patch: 'sote',
    source: 'Fextralife, Ancient Meteoric Ore Greatsword (SotE, patch 1.17).',
  },
  {
    id: 'build:pvp-bloodfiend-sote',
    name: "Bloodfiend's Arm (RL125, SotE)",
    tag: 'pvp / invade / arcane bleed',
    why: "The Bloodfiend's Arm builds Hemorrhage on a big arcane-scaled strike, so each opening both procs bleed and heals you back.",
    level: 125,
    stats: { vigor: 55, mind: 20, endurance: 25, strength: 18, dexterity: 20, intelligence: 9, faith: 8, arcane: 49 },
    kit: [
      { id: 'bloodfiend', name: "Bloodfiend's Arm", kind: 'armament', affinity: 'Blood', upgrade: 25 },
      { id: 'white-mask', name: 'White Mask', kind: 'armor' },
      { id: 'exult', name: "Lord of Blood's Exultation", kind: 'talisman' },
      { id: 'winged', name: 'Rotten Winged Sword Insignia', kind: 'talisman' },
      { id: 'millicent', name: "Millicent's Prosthesis", kind: 'talisman' },
      { id: 'green-turtle', name: 'Green Turtle Talisman', kind: 'talisman' },
    ],
    need: ['loot:bloodfiends-arm', 'loot:white-mask', 'loot:lord-blood-exul', 'item:rotten-winged-sword-insignia'],
    mode: 'invade',
    bracket: 'RL125',
    keywords: ['arcane', 'bleed', 'sote', 'colossal', 'lifesteal'],
    playstyle: 'Invade with the PvE mobs as cover; the bleed proc and the heal make a 2v1 more survivable than the stat line suggests.',
    combos: ['Running R2 to open', 'Bleed proc into a roll-catch', 'Jump attack to force the roll'],
    beats: 'Hosts who try to trade with an arcane colossal and eat the proc.',
    losesTo: 'Bleed-resistant armour and patient parries on the slow swing.',
    loadout: {
      weapons: ["Bloodfiend's Arm +25 (Blood)"],
      offhand: ['Dagger with Bloodhound\'s Step'],
      armor: ['White Mask', 'mid set for the roll'],
      talismans: ["Lord of Blood's Exultation", 'Rotten Winged Sword Insignia', "Millicent's Prosthesis", 'Green Turtle Talisman'],
      spells: ['None'],
      consumables: ['Crimson Tears', 'Boiled Prawn', 'Throwing pots'],
    },
    buffOrder: ['Boiled Prawn', 'Seppuku if running a bleed variant', 'Open with a running R2'],
    patch: 'sote',
    source: "Fextralife, Bloodfiend's Arm (SotE, patch 1.17).",
  },
]

export type PvpMatchup = {
  id: string
  /** The archetype being countered. */
  threat: string
  /** Router keywords that name this archetype. */
  aliases: string[]
  /** How to recognise it. */
  tell: string
  /** Real, concrete counter-tech. */
  counters: string[]
  /** A gear swap to have ready. */
  gearSwap: string
  note: string
}

/**
 * Matchup advice for the archetypes that actually show up. Counter-tech is
 * grounded in the wiki mechanics cited per line (parry flags, Cragblade stamina
 * damage, Eternal Darkness, PvP status scaling); see the module header.
 */
export const pvpMatchups: PvpMatchup[] = [
  {
    id: 'matchup:bleed',
    threat: 'Bleed / Rivers of Blood',
    aliases: ['bleed', 'rivers of blood', 'rivers', 'rob', 'corpse piler', 'blood'],
    tell: 'Katana or twinblade fishing for a multi-hit L2 to proc Hemorrhage.',
    counters: [
      'Roll through the third Corpse Piler hit rather than away from it — that hit is the proc.',
      'PvP scales status buildup down, so one bleed proc rarely kills a high-Vigor build; do not panic-roll into the follow-up.',
      'A shield or high bleed-resist armour blunts the whole plan; pressure the recovery after the L2 whiffs.',
    ],
    gearSwap: 'Swap in the most bleed-resistant armour you own and a shield for the L2.',
    note: 'PvP-exclusive status scaling has applied since patch 1.07 (Fextralife PvP).',
  },
  {
    id: 'matchup:bleed-katana',
    threat: 'Bleed katanas / powerstanced',
    aliases: ['bleed katana', 'powerstanced katana', 'dual katana', 'blood katana', 'nagakiba'],
    tell: 'Two katanas or a Seppuku buff, poking L1s to build Hemorrhage fast.',
    counters: [
      'Do not trade L1s; powerstanced katanas win the DPS race, so play it at range or on the parry.',
      'Carian Retaliation or a Buckler punishes the predictable running R1 both katanas share.',
      'Bleed resistance and a shield turn the matchup into a stamina fight you can win.',
    ],
    gearSwap: 'Carian Retaliation shield or Buckler; bleed-resist armour.',
    note: 'Powerstanced status application and PvP scaling from the Fextralife Bleed and PvP pages.',
  },
  {
    id: 'matchup:colossal',
    threat: 'Colossal / poise monster',
    aliases: ['colossal', 'poise', 'bonk', 'giant crusher', 'hyper armor', 'hyperarmour', 'strength'],
    tell: 'Greatsword or greathammer walking you down behind hyper armour.',
    counters: [
      'Bait the slow R1 and whiff-punish; never trade into hyper armour with a fast weapon.',
      'Giant Hunt and Cragblade can be parried; Lion\'s Claw cannot — learn which one they use.',
      'Thrusting damage (Spear Talisman) and roll-catching beat the recovery frames.',
    ],
    gearSwap: 'Spear Talisman and a thrusting weapon; or a Buckler for Giant Hunt.',
    note: 'Parry flags from the Fextralife Lion\'s Claw / Giant Hunt / Cragblade pages.',
  },
  {
    id: 'matchup:colossal-jump',
    threat: 'Colossal jump attacks',
    aliases: ['colossal jump', 'jump attack', 'jumping colossal', 'axes of godfrey', 'claw talisman'],
    tell: 'A colossal user leaping in with a jumping R2 as their whole neutral game.',
    counters: [
      'Jumps have a long airborne commitment: roll late under the swing and punish the recovery.',
      'Stay off the line of the jump; the attack cannot turn after launch.',
      'A thrusting poke out-ranges the landing frames and wins the trade every time.',
    ],
    gearSwap: 'Long thrusting weapon; Spear Talisman.',
    note: 'Jump-attack commitment is wiki combat mechanics (Fextralife Combat page).',
  },
  {
    id: 'matchup:mage',
    threat: 'Mage / spellspam',
    aliases: ['mage', 'sorcer', 'spellspam', 'spell', 'caster', 'glintstone'],
    tell: 'Staff out, chaining fast projectiles and keeping range.',
    counters: [
      'Eternal Darkness pulls in incoming spells and eats a whole volley.',
      'Close the gap during cast recovery instead of trying to out-range them.',
      'Patch 1.17 reduced Meteorite/Meteorite of Astel cast time and buffed Carian Retaliation — respect the faster pressure.',
    ],
    gearSwap: 'A shield with Carian Retaliation, or Eternal Darkness.',
    note: 'Eternal Darkness as anti-caster is from the Fextralife Sorcerer Duelist page; 1.17 changes from Patch Notes.',
  },
  {
    id: 'matchup:comet-azur',
    threat: 'Comet Azur / one-shot beam',
    aliases: ['comet azur', 'azur', 'beam', 'one shot', 'oneshot', 'cerulean'],
    tell: 'A staff user drinking a Wondrous Physick and charging a long blue beam.',
    counters: [
      'The beam is channelled and cannot track a target strafing behind cover; break line of sight immediately.',
      'Close during the channel — the caster is committed and cannot cancel into a roll quickly.',
      'Never stand still in the open once a caster has the physick buff active.',
    ],
    gearSwap: 'No special gear needed; use terrain and any fast weapon.',
    note: 'Cerulean Hidden Tear removes FP cost for the channel (Fextralife Comet Azur page).',
  },
  {
    id: 'matchup:freezing-mist',
    threat: 'Freezing Mist / frost spam',
    aliases: ['freezing mist', 'frost mist', 'mist spam', 'cold mist', 'frostbite'],
    tell: 'A caster laying Freezing Mist on a doorway or choke point and hiding behind it.',
    counters: [
      'Do not chase through the mist; circle around and force them to fight in the open.',
      'A Preserving Boluse or frost-resistant armour stops the bite from cutting your stamina.',
      'The caster has no pressure without the mist, so staying patient wins.',
    ],
    gearSwap: 'Frost-resist armour; Preserving Boluses.',
    note: 'Frostbite stamina effect from the Fextralife Frostbite page.',
  },
  {
    id: 'matchup:poke',
    threat: 'Thrusting-sword poke',
    aliases: ['poke', 'thrust', 'estoc', 'rapier', 'naginata', 'spear', 'greatshield poke', 'turtle'],
    tell: 'Fast thrusting sword poking from just outside your swing range.',
    counters: [
      'Cragblade adds +50% stamina damage against guarding enemies for 60s — the anti-shield tool.',
      'Parry the predictable thrust; the 1.17 Parry improvement widened the window.',
      'Out-poise the poke or out-range it with a longer weapon; guard counters punish blocked pokes.',
    ],
    gearSwap: 'Cragblade, or a longer weapon; a Buckler for the parry read.',
    note: 'Cragblade and Parry values from their Fextralife pages and the 1.17 Patch Notes.',
  },
  {
    id: 'matchup:greatshield',
    threat: 'Greatshield turtle',
    aliases: ['greatshield', 'fingerprint', 'shield poke', 'shield', 'guard'],
    tell: 'Blocking behind a tower shield and poking from safety.',
    counters: [
      'Cragblade\'s +50% stamina damage against guarding enemies is the direct answer.',
      'Scarlet Rot or bleed through the shield (Antspur Rapier) ignores the block entirely.',
      'Patch 1.17 buffed greatshield guard boost and cut weight on many shields, so they are tankier now — do not assume chip damage will do it.',
    ],
    gearSwap: 'Antspur Rapier with Blood; Cragblade.',
    note: '1.17 greatshield changes from the Patch Notes; Cragblade from its Fextralife page.',
  },
  {
    id: 'matchup:invader',
    threat: 'Invader / host asymmetry',
    aliases: ['invader', 'invade', 'invasion', 'host', 'gank', '2v1', 'co-op'],
    tell: 'Deciding who has the advantage before the fight starts.',
    counters: [
      'The host has flasks, a Great Rune and co-op summons; the invader has the PvE mobs and cannot enter boss fog.',
      'Invaders should use enemies as cover and pick off the summon before the host.',
      'Taunter\'s Tongue shortens the invasion window and allows a second invader (limits the host to one summon).',
    ],
    gearSwap: 'Taunter\'s Tongue to control invade timing; Festering Bloody Finger to invade.',
    note: 'Invasion rules and Taunter\'s Tongue behaviour from the Fextralife PvP page.',
  },
  {
    id: 'matchup:frost',
    threat: 'Frost / cold weapons and spells',
    aliases: ['frost', 'cold', 'zamor', 'ghostflame'],
    tell: 'Fast curved swords or a caster fishing for a Frostbite proc to cut your stamina.',
    counters: [
      'Carry a frost-resistant talisman or armour for the matchup; the proc amplifies the hit that follows, so never eat the second chain.',
      'Clear the frostbite bar with a boluse before re-engaging rather than letting it linger.',
      'Punish the caster between Glintstone Icecrag casts; the frost weapons have to come to you.',
    ],
    gearSwap: 'Frost-resist armour and a Preserving Boluse.',
    note: 'Frostbite stamina effect and damage amplification are wiki mechanics (Fextralife, Frostbite).',
  },
  {
    id: 'matchup:rot',
    threat: 'Scarlet Rot pressure',
    aliases: ['rot', 'scarlet rot', 'antspur', 'rotten'],
    tell: 'An Antspur Rapier or a rot breath ticking both a damage-over-time and a heal cut.',
    counters: [
      'Preserving Boluses clear Scarlet Rot; keep two on the quick bar in any late-game invasion.',
      'Pressure the rot applier immediately — the build needs time to win, so deny it.',
      'Do not trade into a bleed-rot rapier; poke from outside its range or parry the thrust.',
    ],
    gearSwap: 'Preserving Boluses; a shield or parry tool.',
    note: 'Rot cures from the Fextralife Preserving Boluses page; status stacking from the PvP page.',
  },
  {
    id: 'matchup:frenzy',
    threat: 'Frenzied Flame burst',
    aliases: ['frenzy', 'madness', 'frenzied flame', 'unendurable'],
    tell: 'A caster charging Unendurable Frenzy or Flame of Frenzy at range.',
    counters: [
      'Break line of sight and close during the long channel; the stream cannot turn fast enough.',
      'Madness procs hurt far more than the listed damage, so do not face-tank the burst to trade.',
      'Once you are in, stay in — the frenzy caster has no melee answer at close range.',
    ],
    gearSwap: 'Focus-boosting gear to resist Madness; any gap-closer.',
    note: 'Madness buildup and the channel behaviour are from the Fextralife Frenzied Flame pages.',
  },
  {
    id: 'matchup:sleep',
    threat: 'Sleep / St Trina',
    aliases: ['sleep', 'st trina', 'trina', 'sword of st trina'],
    tell: 'Dual St Trina swords or a sleep pot fishing for a stance-break window.',
    counters: [
      'Sleep does not open a critical in PvP, but the stance-break window it leaves is where the damage goes.',
      'Keep moving; the proc only lands if you stand in the L1 chain.',
      'Stimulating Boluses or a sleep-resistant set blunts the whole plan.',
    ],
    gearSwap: 'Stimulating Boluses; sleep-resist armour.',
    note: 'PvP sleep behaviour from the Fextralife PvP page.',
  },
  {
    id: 'matchup:bhs',
    threat: 'Bloodhound\'s Step escape',
    aliases: ['bloodhound step', 'bhs', 'step', 'mobility'],
    tell: 'An opponent who resets every exchange with a step and never commits to a combo.',
    counters: [
      'Do not chase the step; hold the centre and force them to come to you.',
      'Punish the recovery frames after the step, not the step itself.',
      'A thrusting weapon or a long poke catches the step-back better than a wide swing.',
    ],
    gearSwap: 'A long thrusting weapon; Spear Talisman.',
    note: 'Community-standard counter-tech (author-encoded); cf. Fextralife PvP.',
  },
  {
    id: 'matchup:dualspear',
    threat: 'Dual-spear poke',
    aliases: ['dual spear', 'spears', 'cross-naginata', 'naginata', 'powerstance'],
    tell: 'Powerstanced spears poking from just outside your swing range.',
    counters: [
      'Close the gap during the L1 recovery rather than trying to out-range it.',
      'Parry the predictable thrust; the spears cannot mix up the timing much.',
      'Cragblade or a shield counter punishes the poke if you cannot out-space it.',
    ],
    gearSwap: 'Buckler or Carian Retaliation; Cragblade.',
    note: 'Community-standard counter-tech (author-encoded); cf. Fextralife PvP.',
  },
  {
    id: 'matchup:blasphemous',
    threat: 'Blasphemous Blade / Taker\'s Flames',
    aliases: ['blasphemous', 'taker\'s flames', 'takers flames', 'blasphemous blade'],
    tell: 'A faith player spamming Taker\'s Flames, healing through every wave.',
    counters: [
      'The wave is a fixed, slow projectile: sidestep, do not roll backwards into the follow-up.',
      'Pressure during the recovery; the skill heals but leaves the user planted.',
      'Holy resistance and a fast weapon deny the heal-on-hit race.',
    ],
    gearSwap: 'Holy-resist talisman/armour; a fast roll.',
    note: 'Taker\'s Flames healing and projectile behaviour from the Fextralife Blasphemous Blade page.',
  },
  {
    id: 'matchup:carian-slicer',
    threat: 'Carian Slicer',
    aliases: ['carian slicer', 'slicer', 'melee mage'],
    tell: 'A staff user closing distance and spamming the fast, cheap melee slash.',
    counters: [
      'Slicer has short range: back off just outside it and punish the whiffed swipe.',
      'It staggers under ~30 poise, so trade with something heavy or stack poise.',
      'A shield or Carian Retaliation eats the predictable slash.',
    ],
    gearSwap: 'A shield with Carian Retaliation; poise gear.',
    note: 'Slicer range and stagger from the Fextralife Carian Slicer page.',
  },
  {
    id: 'matchup:pots',
    threat: 'Pot / consumable builds',
    aliases: ['pot', 'pots', 'sleep pot', 'frenzy pot', 'throwing', 'perfume'],
    tell: 'An opponent opening with crafted pots and perfume bottles instead of a weapon.',
    counters: [
      'Pots are slow lobs: keep moving laterally and close the throw arc.',
      'Sleep pots set the stance-break window rather than doing damage; stay mobile through the cloud.',
      'Perfume bottles are fast but short-ranged; out-space them and punish the recovery.',
    ],
    gearSwap: 'High immunity/resistance armour; Stimulating Boluses.',
    note: 'Pot and perfume behaviour from the Fextralife Sleep Pot / Perfume Bottle pages.',
  },
  {
    id: 'matchup:moonveil',
    threat: 'Moonveil / Transient Moonlight',
    aliases: ['moonveil', 'transient moonlight', 'moonlight'],
    tell: 'A katana user firing vertical and horizontal Transient Moonlight beams at range.',
    counters: [
      'The beams are telegraphed: roll through the horizontal, sidestep the vertical.',
      'Close during the skill recovery; Moonveil users rely on the ranged stagger to reset.',
      'Magic resistance and a shield blunt the beam damage.',
    ],
    gearSwap: 'Magic-resist talisman; a fast pressure weapon.',
    note: 'Transient Moonlight behaviour from the Fextralife Moonveil page.',
  },
  {
    id: 'matchup:waterfowl',
    threat: 'Hand of Malenia / Waterfowl Dance',
    aliases: ['waterfowl', 'hand of malenia', 'malenia', 'waterfowl dance'],
    tell: 'A katana user winding up the multi-hit spinning Waterfowl Dance.',
    counters: [
      'If caught, roll through the third flurry toward the user, not away.',
      'The skill has a long commitment: bait it out and punish the recovery.',
      'Bleed resistance and a shield soften the multi-hit chip.',
    ],
    gearSwap: 'Bleed-resist armour; a shield for the chip.',
    note: 'Waterfowl Dance behaviour from the Fextralife Hand of Malenia page.',
  },
  {
    id: 'matchup:mimic-gank',
    threat: 'Mimic Tear / summon ganks',
    aliases: ['mimic', 'mimic tear', 'summon', 'spirit ash'],
    tell: 'A host who has summoned a Mimic Tear or a co-op squad and doubles the pressure.',
    counters: [
      'A Mimic copies the host\'s build, so the counter to the host also counters the Mimic.',
      'Burst the summon first if it is the weaker copy; do not let it buff-stack.',
      'Use PvE mobs and terrain to split the squad rather than fighting two at once.',
    ],
    gearSwap: 'Crowd tools (Starscourge pull, hoarfrost) to hit both.',
    note: 'Mimic Tear copy behaviour from the Fextralife Mimic Tear Ashes page.',
  },
  {
    id: 'matchup:blackflame',
    threat: 'Black Flame / percentage chip',
    aliases: ['black flame', 'blackflame', 'godslayer', 'scouring'],
    tell: 'A caster throwing Black Flame and Scouring Black Flame for percentage damage.',
    counters: [
      'Black Flame does percentage damage, so stacking HP does not save you; break the cast rhythm.',
      'Close during the cast recovery; the caster wants the fight at range.',
      'A shield or Eternal Darkness eats the projectile.',
    ],
    gearSwap: 'A shield or Eternal Darkness; gap-closer.',
    note: 'Black Flame percentage damage from the Fextralife Black Flame page.',
  },
  {
    id: 'matchup:gank-squad',
    threat: 'Gank squads / 3v1',
    aliases: ['gank squad', 'gank', '3v1', 'co-op squad', 'overleveled'],
    tell: 'A host with two password-summon phantoms camping an open arena.',
    counters: [
      'Never fight the whole squad in the open; retreat through PvE and force them to split.',
      'Pick the weakest player and burst them before the others arrive.',
      'Use the invade timer: you do not have to win every fight, only find a pick.',
    ],
    gearSwap: 'Mobility (Bloodhound\'s Step) and burst damage.',
    note: 'Invasion asymmetry and gank tactics from the Fextralife PvP page.',
  },
  {
    id: 'matchup:gravity',
    threat: 'Gravity / Starscourge pull',
    aliases: ['gravity', 'starscourge', 'starcaller cry', 'pull', 'radahn'],
    tell: 'A colossal greatsword user winding up Starcaller Cry to pull you into the follow-up.',
    counters: [
      'The pull has a fixed radius: back off as soon as you see the wind-up.',
      'If caught, the follow-up is a slow swing you can roll late.',
      'Punish the long recovery after a whiffed pull.',
    ],
    gearSwap: 'A long weapon; no special gear needed.',
    note: 'Starcaller Cry behaviour from the Fextralife Starscourge Greatsword page.',
  },
  {
    id: 'matchup:parry-spam',
    threat: 'Parry fishing / Buckler',
    aliases: ['parry', 'parry spam', 'buckler', 'carian retaliation', 'golden parry'],
    tell: 'An opponent who stands still and throws out parries hoping you attack into them.',
    counters: [
      'Use jumping attacks, two-handed heavy swings and unparryable ashes until the parry habit breaks.',
      'Whiff a light attack just outside range to bait a parry, then punish the whiffed parry.',
      'Kick or guard-break tools punish a static parry stance.',
    ],
    gearSwap: 'A jump-attack setup or an unparryable ash (Lion\'s Claw).',
    note: 'Parry windows and unparryable skills from the Fextralife Parry / Lion\'s Claw pages.',
  },
  {
    id: 'matchup:jar-cannon',
    threat: 'Jar Cannon / greatbow sniping',
    aliases: ['jar cannon', 'cannon', 'greatbow', 'snipe', 'ballista'],
    tell: 'A ranged weapon lobbing explosive bolts or great arrows from a distant perch.',
    counters: [
      'Close the distance using cover; the reload is long and the projectile arcs.',
      'The Jar Cannon cannot hit a target right under the shooter — hug the wall and climb.',
      'Punish the reload window every time.',
    ],
    gearSwap: 'No special gear; use cover and mobility.',
    note: 'Jar Cannon arcs and reload from the Fextralife Jar Cannon page.',
  },
]
