import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import type { EntityRecord } from './entityIndex'

/**
 * Task 148 — regression guards for the audit fixes. The index is generated by
 * `src/lib/entityIndexBuild.ts` and committed as
 * `public/sourced/entity-index.json`; the alias plane by `scripts/gen-aliases.mjs`
 * as `public/sourced/aliases.json`. These read those snapshots, exactly as the
 * page/coverage guards do.
 */

const indexPath = fileURLToPath(new URL('../../public/sourced/entity-index.json', import.meta.url))
const aliasPath = fileURLToPath(new URL('../../public/sourced/aliases.json', import.meta.url))
const dropsPath = fileURLToPath(new URL('../../public/sourced/open/enemy-drops.json', import.meta.url))
const wikiWeaponPath = fileURLToPath(new URL('../../public/sourced/open/wiki-db/weapon.json', import.meta.url))
const legacyPath = fileURLToPath(new URL('../../src/data/legacy-entity-ids.json', import.meta.url))
const legacyExceptionsPath = fileURLToPath(new URL('../../src/data/legacy-alias-exceptions.json', import.meta.url))

const records = (JSON.parse(readFileSync(indexPath, 'utf8')) as { records?: Record<string, EntityRecord> }).records ?? {}
const list = Object.values(records)
const aliases = JSON.parse(readFileSync(aliasPath, 'utf8')) as { engineId: string; slug: string }[]

/** Parenthetical-preserving normal form (the enemy merge key). */
function rawNorm(value: unknown): string {
  return String(value ?? '')
    .toLowerCase()
    .replace(/[\u2019']s\b/g, '')
    .replace(/[^a-z0-9+]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

describe('Task 148 §1 — one page per enemy', () => {
  const enemies = list.filter((record) => record.kind === 'enemy')

  it('has no enemy display name twice', () => {
    const seen = new Map<string, string>()
    const duplicates: string[] = []
    for (const record of enemies) {
      const previous = seen.get(record.name)
      if (previous) duplicates.push(`${record.name}: ${previous} vs ${record.id}`)
      else seen.set(record.name, record.id)
    }
    expect(duplicates, duplicates.slice(0, 20).join('\n')).toEqual([])
  })

  it('resolves every old enemy:<npcParamId> drop id to its merged page', () => {
    const enemyByName = new Map<string, string>()
    for (const record of enemies) {
      const key = rawNorm(record.name)
      if (key && !enemyByName.has(key)) enemyByName.set(key, record.id)
    }
    const slugByEngineId = new Map<string, string>()
    for (const alias of aliases) if (!slugByEngineId.has(alias.engineId)) slugByEngineId.set(alias.engineId, alias.slug)

    const drops = JSON.parse(readFileSync(dropsPath, 'utf8')) as { rows: { npcParamId: number; name: string }[] }
    const offenders: string[] = []
    let checked = 0
    for (const row of drops.rows) {
      // Only ids that named a real enemy record before the merge must resolve.
      const target = enemyByName.get(rawNorm(row.name))
      if (!target) continue
      checked++
      const engineId = `enemy:${row.npcParamId}`
      const resolved = records[engineId] ? engineId : slugByEngineId.get(engineId)
      if (resolved !== target) offenders.push(`${engineId} -> ${resolved ?? 'unresolved'} (want ${target})`)
    }
    expect(checked).toBeGreaterThan(500)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })
})

describe('Task 148 §2 — placeholder junk is gone', () => {
  it('has no description matching /^The is a|^\\w+$/', () => {
    const offenders = list.filter((record) => /^The is a|^\w+$/.test(record.description ?? '')).map((record) => record.id)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('has no Dummy Entity, Type N or test gem record', () => {
    const junk = list.filter(
      (record) => /^dummy entity$/i.test(record.name) || /^type \d+$/i.test(record.name) || /^test gem/i.test(record.name),
    )
    expect(junk.map((record) => `${record.id} (${record.name})`)).toEqual([])
  })
})

describe('Task 148 follow-up — wiki template sentences are gone', () => {
  it('has no description matching /in Elden Ring\\.|a melee armament/', () => {
    const offenders = list
      .filter((record) => /in Elden Ring\.|a melee armament/.test(record.description ?? ''))
      .map((record) => `${record.id}: ${record.description}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })
})

describe('Task 148 §4 — cut content is flagged, not deleted', () => {
  it('flags the wiki Weapon Cut pages', () => {
    const wiki = JSON.parse(readFileSync(wikiWeaponPath, 'utf8')) as { records: { title: string; infobox: string }[] }
    const cutTitles = wiki.records.filter((record) => /\bcut\b/i.test(record.infobox)).map((record) => rawNorm(record.title))
    expect(cutTitles.length).toBeGreaterThan(0)
    const cut = list.filter((record) => record.cut)
    expect(cut.length, 'no record carries cut: true').toBeGreaterThan(0)
    expect(cut.every((record) => record.stats?.Status === 'Cut content (not obtainable)')).toBe(true)
    const covered = cutTitles.filter((title) => cut.some((record) => rawNorm(record.name) === title))
    expect(covered, `cut weapon pages not flagged: ${cutTitles.filter((t) => !covered.includes(t)).join(', ')}`).not.toEqual([])
  })
})

describe('Task 150 §2 — no place-only descriptions', () => {
  it('never stores the region or location verbatim as the description', () => {
    const offenders = list
      .filter((record) => {
        const description = String(record.description ?? '').trim()
        if (!description) return false
        return (
          (!!record.region && rawNorm(description) === rawNorm(record.region)) ||
          (!!record.location && rawNorm(description) === rawNorm(record.location))
        )
      })
      .map((record) => `${record.id}: ${record.description}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('still keeps the template guard', () => {
    const offenders = list.filter((record) => /in Elden Ring\.|a melee armament/.test(record.description ?? ''))
    expect(offenders.map((record) => record.id).slice(0, 20)).toEqual([])
  })

  it('gives the four named bosses a real description', () => {
    for (const id of ['boss:radahn', 'boss:mohg-omen', 'boss:malenia', 'boss:astel']) {
      const record = records[id]
      expect(record, `${id} is missing`).toBeTruthy()
      const description = String(record.description ?? '').trim()
      expect(description.length, `${id} has no description`).toBeGreaterThan(20)
      expect(/in Elden Ring\.|a melee armament/.test(description), `${id} is a template`).toBe(false)
      expect(rawNorm(description) === rawNorm(record.region ?? ''), `${id} is a place-only description`).toBe(false)
      expect(rawNorm(description) === rawNorm(record.location ?? ''), `${id} is a place-only description`).toBe(false)
    }
  })
})

describe('Task 150 §3 — dead legacy ids stay bounded', () => {
  it('resolves every old id except the documented exceptions', () => {
    const legacy = JSON.parse(readFileSync(legacyPath, 'utf8')) as { id: string; kind: string; name: string }[]
    const exceptions = JSON.parse(readFileSync(legacyExceptionsPath, 'utf8')) as string[]
    const exceptionSet = new Set(exceptions)
    const aliasEngineIds = new Set(aliases.map((alias) => alias.engineId))
    const dead = legacy.filter((row) => !records[row.id] && !aliasEngineIds.has(row.id))
    expect(dead.length).toBeLessThanOrEqual(exceptionSet.size)
    // The exceptions must be genuinely unresolvable — no mapped id may hide there.
    const unmapped = dead.filter((row) => !exceptionSet.has(row.id)).map((row) => row.id)
    expect(unmapped, unmapped.slice(0, 20).join('\n')).toEqual([])
  })
})
