import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import type { EntityRecord } from './entityIndex'

/**
 * Task 148 — regression guards for the audit fixes. The index is generated by
 * `src/lib/entityIndexBuild.ts` and committed as
 * `public/sourced/entity-index.json`; the alias plane by `scripts/gen-aliases.mjs`
 * as `public/sourced/aliases.json`. These read those snapshots, exactly as the
 * page/coverage guards do.
 */

const indexPath = fileURLToPath(new URL('../../public/sourced/entity-index.json', import.meta.url))
const aliasPath = fileURLToPath(new URL('../../public/sourced/aliases.json', import.meta.url))
const dropsPath = fileURLToPath(new URL('../../public/sourced/open/enemy-drops.json', import.meta.url))
const wikiWeaponPath = fileURLToPath(new URL('../../public/sourced/open/wiki-db/weapon.json', import.meta.url))
const nightreignPath = fileURLToPath(new URL('../../public/sourced/open/wiki-db/nightreign.json', import.meta.url))
const legacyPath = fileURLToPath(new URL('../../src/data/legacy-entity-ids.json', import.meta.url))
const legacyExceptionsPath = fileURLToPath(new URL('../../src/data/legacy-alias-exceptions.json', import.meta.url))

const records = (JSON.parse(readFileSync(indexPath, 'utf8')) as { records?: Record<string, EntityRecord> }).records ?? {}
const list = Object.values(records)
const aliases = JSON.parse(readFileSync(aliasPath, 'utf8')) as { engineId: string; slug: string }[]

/** Parenthetical-preserving normal form (the enemy merge key). */
function rawNorm(value: unknown): string {
  return String(value ?? '')
    .toLowerCase()
    .replace(/[\u2019']s\b/g, '')
    .replace(/[^a-z0-9+]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

describe('Task 148 §1 — one page per enemy', () => {
  const enemies = list.filter((record) => record.kind === 'enemy')

  it('has no enemy display name twice', () => {
    const seen = new Map<string, string>()
    const duplicates: string[] = []
    for (const record of enemies) {
      const previous = seen.get(record.name)
      if (previous) duplicates.push(`${record.name}: ${previous} vs ${record.id}`)
      else seen.set(record.name, record.id)
    }
    expect(duplicates, duplicates.slice(0, 20).join('\n')).toEqual([])
  })

  it('resolves every old enemy:<npcParamId> drop id to its merged page', () => {
    const enemyByName = new Map<string, string>()
    for (const record of enemies) {
      const key = rawNorm(record.name)
      if (key && !enemyByName.has(key)) enemyByName.set(key, record.id)
    }
    const slugByEngineId = new Map<string, string>()
    for (const alias of aliases) if (!slugByEngineId.has(alias.engineId)) slugByEngineId.set(alias.engineId, alias.slug)

    const drops = JSON.parse(readFileSync(dropsPath, 'utf8')) as { rows: { npcParamId: number; name: string }[] }
    const offenders: string[] = []
    let checked = 0
    for (const row of drops.rows) {
      // Only ids that named a real enemy record before the merge must resolve.
      const target = enemyByName.get(rawNorm(row.name))
      if (!target) continue
      checked++
      const engineId = `enemy:${row.npcParamId}`
      const resolved = records[engineId] ? engineId : slugByEngineId.get(engineId)
      if (resolved !== target) offenders.push(`${engineId} -> ${resolved ?? 'unresolved'} (want ${target})`)
    }
    expect(checked).toBeGreaterThan(500)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })
})

describe('Task 148 §2 — placeholder junk is gone', () => {
  it('has no description matching /^The is a|^\\w+$/', () => {
    const offenders = list.filter((record) => /^The is a|^\w+$/.test(record.description ?? '')).map((record) => record.id)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('has no Dummy Entity, Type N or test gem record', () => {
    const junk = list.filter(
      (record) => /^dummy entity$/i.test(record.name) || /^type \d+$/i.test(record.name) || /^test gem/i.test(record.name),
    )
    expect(junk.map((record) => `${record.id} (${record.name})`)).toEqual([])
  })
})

describe('Task 148 follow-up — wiki template sentences are gone', () => {
  it('has no description matching /in Elden Ring\\.|a melee armament/', () => {
    const offenders = list
      .filter((record) => /in Elden Ring\.|a melee armament/.test(record.description ?? ''))
      .map((record) => `${record.id}: ${record.description}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })
})

describe('Task 148 §4 — cut content is flagged, not deleted', () => {
  it('flags the wiki Weapon Cut pages', () => {
    const wiki = JSON.parse(readFileSync(wikiWeaponPath, 'utf8')) as { records: { title: string; infobox: string }[] }
    const cutTitles = wiki.records.filter((record) => /\bcut\b/i.test(record.infobox)).map((record) => rawNorm(record.title))
    expect(cutTitles.length).toBeGreaterThan(0)
    const cut = list.filter((record) => record.cut)
    expect(cut.length, 'no record carries cut: true').toBeGreaterThan(0)
    expect(cut.every((record) => record.stats?.Status === 'Cut content (not obtainable)')).toBe(true)
    const covered = cutTitles.filter((title) => cut.some((record) => rawNorm(record.name) === title))
    expect(covered, `cut weapon pages not flagged: ${cutTitles.filter((t) => !covered.includes(t)).join(', ')}`).not.toEqual([])
  })
})

describe('Task 150 §2 — no place-only descriptions', () => {
  it('never stores the region or location verbatim as the description', () => {
    const offenders = list
      .filter((record) => {
        const description = String(record.description ?? '').trim()
        if (!description) return false
        return (
          (!!record.region && rawNorm(description) === rawNorm(record.region)) ||
          (!!record.location && rawNorm(description) === rawNorm(record.location))
        )
      })
      .map((record) => `${record.id}: ${record.description}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('still keeps the template guard', () => {
    const offenders = list.filter((record) => /in Elden Ring\.|a melee armament/.test(record.description ?? ''))
    expect(offenders.map((record) => record.id).slice(0, 20)).toEqual([])
  })

  it('gives the four named bosses a real description', () => {
    for (const id of ['boss:radahn', 'boss:mohg-omen', 'boss:malenia', 'boss:astel']) {
      const record = records[id]
      expect(record, `${id} is missing`).toBeTruthy()
      const description = String(record.description ?? '').trim()
      expect(description.length, `${id} has no description`).toBeGreaterThan(20)
      expect(/in Elden Ring\.|a melee armament/.test(description), `${id} is a template`).toBe(false)
      expect(rawNorm(description) === rawNorm(record.region ?? ''), `${id} is a place-only description`).toBe(false)
      expect(rawNorm(description) === rawNorm(record.location ?? ''), `${id} is a place-only description`).toBe(false)
    }
  })
})

describe('Task 150 §3 — dead legacy ids stay bounded', () => {
  it('resolves every old id except the documented exceptions', () => {
    const legacy = JSON.parse(readFileSync(legacyPath, 'utf8')) as { id: string; kind: string; name: string }[]
    const exceptions = JSON.parse(readFileSync(legacyExceptionsPath, 'utf8')) as string[]
    const exceptionSet = new Set(exceptions)
    const aliasEngineIds = new Set(aliases.map((alias) => alias.engineId))
    const dead = legacy.filter((row) => !records[row.id] && !aliasEngineIds.has(row.id))
    expect(dead.length).toBeLessThanOrEqual(exceptionSet.size)
    // The exceptions must be genuinely unresolvable — no mapped id may hide there.
    const unmapped = dead.filter((row) => !exceptionSet.has(row.id)).map((row) => row.id)
    expect(unmapped, unmapped.slice(0, 20).join('\n')).toEqual([])
  })
})

describe('Task 151 §3 — the builder writes no filler, and shares no prose family', () => {
  /**
   * The game's own text for a category, repeated verbatim by design. These are
   * the only descriptions allowed to appear on more than 25 records:
   *  - Ash of War: the "Grants affinities and skills to an armament" caption the
   *    game itself prints for every Ash of War.
   *  - Gesture: the "Locks the player character in place during the animation."
   *    animation label the wiki carries for every gesture that has no cutscene.
   * Nothing else may repeat: a shared sentence means the builder invented it.
   */
  const ALLOWED_SHARED_FAMILIES = [
    'grants affinities and skills to an armament',
    'locks the player character in place during the animation',
  ]

  it('has no generated enemy, place or item-access sentence', () => {
    const offenders = list
      .filter((record) => /is a hostile creature encountered|is a location in [A-Z]|for new item access/.test(record.description ?? ''))
      .map((record) => `${record.id}: ${record.description}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('shares no normalised description across more than 25 records except the game-caption families', () => {
    const groups = new Map<string, string[]>()
    for (const record of list) {
      const description = String(record.description ?? '').trim()
      if (!description) continue
      const name = rawNorm(record.name)
      let key = rawNorm(description)
      if (name) key = key.split(name).join('x').trim()
      const ids = groups.get(key) ?? []
      ids.push(record.id)
      groups.set(key, ids)
    }
    const offenders = [...groups.entries()]
      .filter(([key, ids]) => ids.length > 25 && !ALLOWED_SHARED_FAMILIES.includes(key))
      .sort((a, b) => b[1].length - a[1].length)
      .map(([key, ids]) => `${key} × ${ids.length}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })
})

describe('Task 172 — description hygiene guards', () => {
  /** The wiki category frame: "X is an optional boss in Shadow of the Erdtree". */
  const TEMPLATE_FRAME = /\b(is|are|was) (a|an|the|one of the)\b[^.]{0,80}\bin (Elden Ring|Shadow of the Erdtree|the Lands Between)\b/i
  /** A deictic lead the extraction cut the subject off the front of. */
  const THIS_IS = /^This is an? /
  /** A fragment the extraction cut the subject from ("s are Enemies…", ", also…"). */
  const LEADING_FRAGMENT = /^[,.;:)]|^s are /

  it('has no category template, "This is a" lead or cut-off fragment', () => {
    const offenders = list
      .filter((record) => {
        const description = String(record.description ?? '')
        if (!description.trim()) return false
        return TEMPLATE_FRAME.test(description) || THIS_IS.test(description) || LEADING_FRAGMENT.test(description)
      })
      .map((record) => `${record.id}: ${record.description}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })
})

describe('Task 176 §1 — Nightreign text never describes a base page', () => {
  /**
   * `/sourced/open/wiki-db/nightreign.json` is the separate game. Its record
   * titles, plus the Nightreign-only place names the file is missing (the wiki's
   * own words: Limveld, the Shifting Earth events, Deep of Night), must never
   * render in an Elden Ring description.
   */
  const nightreignTerms = (() => {
    const terms = new Set<string>(['Limveld', 'Shifting Earth', 'Deep of Night', 'Everdark'])
    const nightreign = JSON.parse(readFileSync(nightreignPath, 'utf8')) as { records?: { title?: string }[] }
    for (const record of nightreign.records ?? []) if (record.title) terms.add(record.title)
    return [...terms]
  })()

  it('writes no description naming Nightreign or a Nightreign-only term', () => {
    const offenders = list
      .filter((record) => {
        const description = String(record.description ?? '')
        if (!description.trim()) return false
        return nightreignTerms.some((term) => {
          const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
          return new RegExp(`\\b${escaped}\\b`, 'i').test(description)
        })
      })
      .map((record) => `${record.id}: ${record.description}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('drops the Nightreign prose the audit found on base records', () => {
    for (const id of [
      'enemy:rat',
      'enemy:rat-leyndell',
      'enemy:rat-siofra-river',
      'grace:61433800',
      'grace:61453300',
      'region:mountaintop-minor-erdtree',
    ]) {
      const record = records[id]
      if (!record) continue
      const description = String(record.description ?? '')
      expect(
        /limveld|shifting earth|crater shifting|deep of night|everdark/i.test(description),
        `${id} still carries Nightreign text: ${description}`,
      ).toBe(false)
    }
  })
})

describe('Task 176 §2 — a description comes only from the record’s own page', () => {
  /**
   * The examples from the Task 171 audit, Batch A item 4. Each record shared its
   * name (fuzzily or exactly) with an unrelated wiki page; the fix leaves them
   * without that page's prose rather than quoting a spell, a boss or a dungeon.
   */
  const examples: [string, RegExp][] = [
    ['grace:200104', /spell|incantation/i],
    ['grace:130000', /is not an optional boss|Maliketh must/i],
    ['grace:130001', /Dragonlord Placidusax.*Elden Lord|prehistoric era/i],
    ['grace:410100', /gaol is|is a dungeon|dungeon in/i],
    ['enemy:poison-claw-elder-albinauric', /status effect|Poison is a/i],
    ['enemy:winter-lantern', /crafting material/i],
    ['enemy:flying-dragon-small', /Agheel/i],
  ]

  it('never quotes another page for those records', () => {
    for (const [id, otherPage] of examples) {
      const record = records[id]
      expect(record, `${id} is missing`).toBeTruthy()
      const description = String(record.description ?? '')
      expect(otherPage.test(description), `${id} carries another page's prose: ${description}`).toBe(false)
    }
  })
})

/** A bare place type is a kind word, never a location ("Church", "Subregion"). */
const BARE_PLACE_TYPE = /^(?:church|shack|village|tower|rise|fort|subregion|grace|site of grace|sites of grace|ruins?|cave|tunnel|catacombs?|mausoleum|evergaol|capital|manor|castle|town|city|bridge|gate|mine|gaol|keep|palace|academy|dungeon|well|square|grounds|region|location|area)$/i

describe('Task 177 §6 — region/location is never a bare place type', () => {
  it('has no bare type word in a region or location field', () => {
    const offenders = list
      .filter((record) => [record.location, record.region].some((value) => typeof value === 'string' && BARE_PLACE_TYPE.test(value.trim())))
      .map((record) => `${record.id}: ${record.location ?? record.region}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('keeps the real parent region for a location whose wiki row only carried a type', () => {
    expect(records['region:ailing-village']?.location).toBe('Weeping Peninsula')
    expect(records['region:church-of-benediction']?.location).toBe('Gravesite Plain')
  })
})

describe('Task 177 §7 — location holds a place, never an acquisition paragraph', () => {
  it('has no multi-line paragraph or "Location:"/"Loot:" label in location', () => {
    const offenders = list
      .filter((record) => {
        const location = record.location
        if (typeof location !== 'string') return false
        return location.includes('\n') || /^(?:loot|location|guaranteed drop|dragon communion|purchase|quest item|remembrance item|reward|drop)\s*[:：]/i.test(location.trim())
      })
      .map((record) => `${record.id}: ${JSON.stringify(record.location).slice(0, 80)}`)
    expect(offenders, offenders.slice(0, 20).join('\n')).toEqual([])
  })

  it('keeps the place and drops the paragraph from a labelled blob', () => {
    expect(records['item:about-adding-affinities']?.location).toBe('Gatefront Ruins')
  })

  it('has no merchant placeholder as a location', () => {
    expect(list.filter((record) => (record.location ?? '').trim().toLowerCase() === 'merchant').map((record) => record.id)).toEqual([])
  })
})

describe('Task 177 §8 — name/id/format mismatches', () => {
  it("shows Rellana's in-game name and keeps Rennala a separate record", () => {
    // The catalog id slug is the graph's canonical `boss:rennala-sote` (owned by
    // catalog.ts and the generated roster/alias plane); the index must display the
    // real boss name, not derive it from the stale slug or mix up Rennala.
    expect(records['boss:rennala-sote']?.name).toBe('Rellana, Twin Moon Knight')
    expect(records['boss:rennala']?.name).toBe('Rennala, Queen of the Full Moon')
    expect(aliases.some((row) => row.engineId === 'hunt:rellana-twin-moon-knight' && row.slug === 'boss:rennala-sote')).toBe(true)
  })

  it('gives the generic medallion facts their own catalog name, not a half', () => {
    expect(records['item:dusk-medallion']?.name).toBe('Dectus Medallion')
    expect(records['item:haligtree-secret-medallion']?.name).toBe('Haligtree Secret Medallion')
  })

  it('has no within-kind duplicate display name (the two medallion pairs)', () => {
    // The same normal form the page guard uses (apostrophes dropped, not the
    // trailing "s"), so "Old Sorcerer's" and "Old Sorcerer" stay distinct.
    const nameKey = (value: unknown): string =>
      String(value ?? '')
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .toLowerCase()
        .replace(/[\u2019'`"]/g, '')
        .replace(/[^a-z0-9]+/g, ' ')
        .trim()
    const groups = new Map<string, string[]>()
    for (const record of list) {
      const key = `${record.kind}|${nameKey(record.name)}`
      const ids = groups.get(key) ?? []
      ids.push(record.id)
      groups.set(key, ids)
    }
    const dups = [...groups.entries()].filter(([, ids]) => ids.length > 1).map(([key, ids]) => `${key}: ${ids.join(', ')}`)
    expect(dups, dups.slice(0, 20).join('\n')).toEqual([])
  })

  it('fixes the comma typo and strips leaked markdown headings from locations', () => {
    expect(records['grace:350003']?.location).toBe('Subterranean Shunning-Grounds')
    const headings = list.filter((record) => typeof record.location === 'string' && record.location.trim().startsWith('#'))
    expect(headings.map((record) => record.id)).toEqual([])
  })
})

