import raw from '../data/dungeons.json'

/**
 * Task 104 — the complete minor-dungeon index for the Area hub.
 *
 * `src/data/dungeons.json` is generated by `scripts/gen-dungeons.mjs` from the
 * in-repo dumps (hunts, map-extras, coords, acquisition, aliases) and covers
 * every catacomb, cave, tunnel, hero's grave, evergaol, divine tower,
 * ruins-with-cellar, gaol and legacy dungeon in base + Shadow of the Erdtree.
 *
 * This module is the pure read layer: `dungeonsInRegion` scopes the index to an
 * Area-hub region label with the same relaxed containment rule `areaHub` uses.
 * The entity graph registers every row + boss from `dungeonBosses` so
 * `EntityLink`/`GetEntity` resolve them like any other fact.
 */

export type DungeonKind =
  | 'catacomb'
  | 'cave'
  | 'tunnel'
  | 'hero-grave'
  | 'evergaol'
  | 'divine-tower'
  | 'ruins'
  | 'gaol'
  | 'legacy'

export type DungeonBoss = { id: string; name: string }
export type DungeonLoot = { id: string; name: string }

export type Dungeon = {
  id: string
  name: string
  kind: DungeonKind
  region: string
  world: string
  x: number | null
  y: number | null
  bosses: DungeonBoss[]
  loot: DungeonLoot[]
  keys: string[]
  levers: number
  impSeals: number
  dlc: boolean
}

export const DUNGEON_KINDS: DungeonKind[] = [
  'catacomb',
  'cave',
  'tunnel',
  'hero-grave',
  'evergaol',
  'divine-tower',
  'ruins',
  'gaol',
  'legacy',
]

export const dungeons = raw as Dungeon[]

function norm(s: string | null | undefined): string {
  return (s ?? '').toLowerCase().replace(/[^a-z0-9+]+/g, ' ').trim()
}

/** Two region labels refer to the same place when one contains the other (≥4 chars). */
export function regionMatches(region: string | null | undefined, area: string | null | undefined): boolean {
  const r = norm(region)
  const a = norm(area)
  if (r.length < 4 || a.length < 4) return false
  return r.includes(a) || a.includes(r)
}

/** Every dungeon whose region matches this Area-hub region label. */
export function dungeonsInRegion(region: string | null | undefined): Dungeon[] {
  return dungeons.filter((d) => regionMatches(d.region, region))
}

/** One row per unique boss across the index, for entity registration. */
export const dungeonBosses: DungeonBoss[] = (() => {
  const byId = new Map<string, DungeonBoss>()
  for (const d of dungeons) for (const b of d.bosses) if (b.id && !byId.has(b.id)) byId.set(b.id, b)
  return [...byId.values()].sort((a, b) => a.name.localeCompare(b.name))
})()
