import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { searchGameText } from './gameText'

// The corpus is generated by scripts/extract-game-text.py from the local game.
// These assertions guard the shipped artifact itself (like idIntegrity.test.ts),
// so a stale or truncated dump fails loudly instead of silently shrinking.
const DIR = path.join(process.cwd(), 'public', 'sourced', 'open', 'text')
const readJson = (name: string) =>
  JSON.parse(fs.readFileSync(path.join(DIR, name), 'utf8')) as Record<string, string>

type Manifest = {
  locale: string
  tableCount: number
  stringCount: number
  tables: { table: string; count: number; sources: string[] }[]
}

describe('game-text corpus', () => {
  const manifest = JSON.parse(
    fs.readFileSync(path.join(DIR, 'manifest.json'), 'utf8'),
  ) as Manifest

  it('manifest counts match the table files', () => {
    const sum = manifest.tables.reduce((n, t) => n + t.count, 0)
    expect(sum).toBe(manifest.stringCount)
    expect(manifest.tables.length).toBe(manifest.tableCount)
    for (const t of manifest.tables) {
      const rows = readJson(`${t.table}.json`)
      expect(Object.keys(rows).length).toBe(t.count)
    }
  })

  it('carries the verbatim dialogue tables, base and DLC merged', () => {
    const talk = readJson('TalkMsg.json')
    const values = Object.values(talk)
    expect(values.length).toBeGreaterThan(9000)
    // A real, famous line (White Mask Varre) — proves it is dialogue, not names.
    expect(values).toContain('But you, I am afraid, are maidenless.')
    // The dlc02 bundle contributed too.
    const talkRow = manifest.tables.find((t) => t.table === 'TalkMsg')!
    expect(talkRow.sources).toContain('menu.msgbnd.dcx')
    expect(talkRow.sources).toContain('menu_dlc02.msgbnd.dcx')
  })

  it('has no placeholder rows leaking into real ids', () => {
    for (const table of ['TalkMsg', 'GoodsName', 'WeaponName', 'NpcName']) {
      const rows = readJson(`${table}.json`)
      expect(Object.values(rows).some((v) => v.toLowerCase() === 'dlc dummy')).toBe(false)
    }
  })
})

describe('searchGameText', () => {
  const tables = {
    TalkMsg: { '1': 'But you, I am afraid, are maidenless.', '2': 'Farewell.' },
    GoodsInfo: { '9': 'A crimson flask.' },
  }

  it('finds a phrase across tables', () => {
    const hits = searchGameText(tables, 'maidenless')
    expect(hits).toEqual([{ table: 'TalkMsg', id: '1', text: 'But you, I am afraid, are maidenless.' }])
  })

  it('ignores short queries and caps results', () => {
    expect(searchGameText(tables, 'yo')).toEqual([])
    const many = { T: Object.fromEntries(Array.from({ length: 100 }, (_, i) => [String(i), 'aaaa'])) }
    expect(searchGameText(many, 'aaaa', 10).length).toBe(10)
  })
})
