import { bitsFromBase64, bitsToBase64, detectFeatures, type DetectOptions, type Feature } from './ps5MapFeatures'
import type { GrayImage } from './ps5Image'

/**
 * Task 135 §1 — the downscaled reference maps the photo is registered against.
 *
 * The engine's tiled pyramid (`vendor/elden-ring-map/web/tiles`) is the canonical
 * atlas art, but it is gitignored and only present on a machine that ran
 * `npm run map:setup`. The app therefore ships the committed static plates
 * (`public/sourced/maps/m*.jpg`, the same art the Atlas draws) and a small JSON of
 * precomputed keypoints, so the browser never recomputes them. `buildMapReference`
 * is the one-time generator; the eval and the app's offline fallback share it.
 */

export type MapWorld = 'overworld' | 'underground'

/**
 * A committed keypoint is packed as `[x, y, angle, descriptor]` (no field names,
 * no score/scale — the matcher does not use them), which keeps the index small.
 */
export type RefFeature = [number, number, number, string]

export type MapReference = {
  world: MapWorld
  /** Plate pixel dimensions; percent coords in `graces.ts` scale by these. */
  width: number
  height: number
  features: RefFeature[]
}

export type MapReferenceFile = {
  version: number
  generatedAt: string
  worlds: Partial<Record<MapWorld, MapReference>>
}

/** The committed static plates (fallback for the tile pyramid) and their size. */
export const MAP_PLATES: Record<MapWorld, { src: string; width: number; height: number }> = {
  overworld: { src: '/sourced/maps/m0-overworld.jpg', width: 4096, height: 3880 },
  underground: { src: '/sourced/maps/m1-underground.jpg', width: 4096, height: 3880 },
}

/** Committed keypoint index the app fetches (generated by the §1 build test). */
export const MAP_REF_KEYPOINTS_SRC = '/sourced/maps/map-ref-keypoints.json'

export const REFERENCE_DETECT_OPTS: DetectOptions = {
  maxDimension: 2048,
  levels: 5,
  maxFeaturesPerLevel: 700,
  threshold: 16,
}

export function toRefFeatures(features: Feature[]): RefFeature[] {
  return features.map((f) => [
    Math.round(f.kp.x * 10) / 10,
    Math.round(f.kp.y * 10) / 10,
    Math.round(f.kp.angle * 1000) / 1000,
    bitsToBase64(f.bits),
  ])
}

export function fromRefFeatures(ref: MapReference): Feature[] {
  return ref.features.map(([x, y, angle, d]) => ({
    kp: { x, y, scale: 1, angle, score: 0 },
    bits: bitsFromBase64(d),
  }))
}

export function buildMapReference(world: MapWorld, gray: GrayImage, opts: DetectOptions = REFERENCE_DETECT_OPTS): MapReference {
  const plate = MAP_PLATES[world]
  return {
    world,
    width: gray.width || plate.width,
    height: gray.height || plate.height,
    features: toRefFeatures(detectFeatures(gray, opts)),
  }
}

export function emptyReferenceFile(): MapReferenceFile {
  return { version: 1, generatedAt: new Date().toISOString(), worlds: {} }
}

let cache: MapReferenceFile | null = null

/** Fetch the committed keypoint index (browser). Missing file → empty index. */
export async function loadMapReferenceFile(): Promise<MapReferenceFile> {
  if (cache) return cache
  try {
    const res = await fetch(MAP_REF_KEYPOINTS_SRC)
    if (!res.ok) throw new Error(String(res.status))
    cache = (await res.json()) as MapReferenceFile
  } catch {
    cache = emptyReferenceFile()
  }
  return cache
}

/**
 * Decode the committed plate on the canvas and build the keypoints on the fly.
 * Used only when the committed index is unavailable; this is why the index is
 * committed — the browser should not have to detect ~8,000 keypoints per load.
 */
export async function buildReferenceFromPlate(world: MapWorld, loadGray: () => Promise<GrayImage>): Promise<MapReference> {
  return buildMapReference(world, await loadGray())
}
