/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as WeaveRouteImport } from './routes/weave'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaveRoute = WeaveRouteImport.update({
  id: '/weave',
  path: '/weave',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/checklist': typeof ChecklistRoute
  '/chronicle': typeof ChronicleRoute
  '/codex': typeof CodexRoute
  '/forge': typeof ForgeRoute
  '/guide': typeof GuideRoute
  '/quests': typeof QuestsRoute
  '/weave': typeof WeaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/checklist': typeof ChecklistRoute
  '/chronicle': typeof ChronicleRoute
  '/codex': typeof CodexRoute
  '/forge': typeof ForgeRoute
  '/guide': typeof GuideRoute
  '/quests': typeof QuestsRoute
  '/weave': typeof WeaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/checklist': typeof ChecklistRoute
  '/chronicle': typeof ChronicleRoute
  '/codex': typeof CodexRoute
  '/forge': typeof ForgeRoute
  '/guide': typeof GuideRoute
  '/quests': typeof QuestsRoute
  '/weave': typeof WeaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/checklist'
    | '/chronicle'
    | '/codex'
    | '/forge'
    | '/guide'
    | '/quests'
    | '/weave'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/checklist'
    | '/chronicle'
    | '/codex'
    | '/forge'
    | '/guide'
    | '/quests'
    | '/weave'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/checklist'
    | '/chronicle'
    | '/codex'
    | '/forge'
    | '/guide'
    | '/quests'
    | '/weave'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  ChecklistRoute: typeof ChecklistRoute
  ChronicleRoute: typeof ChronicleRoute
  CodexRoute: typeof CodexRoute
  ForgeRoute: typeof ForgeRoute
  GuideRoute: typeof GuideRoute
  QuestsRoute: typeof QuestsRoute
  WeaveRoute: typeof WeaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weave': {
      id: '/weave'
      path: '/weave'
      fullPath: '/weave'
      preLoaderRoute: typeof WeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  ChecklistRoute: ChecklistRoute,
  ChronicleRoute: ChronicleRoute,
  CodexRoute: CodexRoute,
  ForgeRoute: ForgeRoute,
  GuideRoute: GuideRoute,
  QuestsRoute: QuestsRoute,
  WeaveRoute: WeaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
